# Generated by Tses 2026-07-12T12:24:00Z
# Generated by Django 5.2.14 on 2026-07-12 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('purpose', models.CharField(choices=[('SIGNUP_VERIFICATION', 'Signup Verification'), ('PASSWORD_RESET', 'Password Reset')], help_text='What this OTP authorizes.', max_length=32, verbose_name='Purpose')),
                ('code_hash', models.CharField(help_text='Hashed one-time code. The raw code is never stored.', max_length=128, verbose_name='Code Hash')),
                ('expires_at', models.DateTimeField(help_text='When this OTP stops being valid.', verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this OTP has already been successfully verified.', verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts against this OTP.', verbose_name='Attempts')),
                ('user', models.ForeignKey(help_text='User this OTP was issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='otp_user_purpose_used_idx')],
            },
        ),
    ]
