# Generated by Tses 2026-07-12T18:57:00Z
# Generated by Django 5.2.14 on 2026-07-12 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('purpose', models.CharField(choices=[('SIGNUP_VERIFICATION', 'Signup Verification'), ('PASSWORD_RESET', 'Password Reset')], help_text='What this token authorizes.', max_length=32, verbose_name='Purpose')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the raw token. The raw token is never stored.', max_length=64, unique=True, verbose_name='Token Hash')),
                ('expires_at', models.DateTimeField(help_text='When this token stops being valid.', verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has already been successfully verified.', verbose_name='Is Used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Reserved abuse-tracking counter. Kept for forward compatibility.', verbose_name='Attempts')),
                ('user', models.ForeignKey(help_text='User this token was issued for.', on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AddIndex(
            model_name='emailverificationtoken',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='evt_user_purpose_used_idx'),
        ),
    ]
