# Generated by Django 5.2.14 on 2026-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailverificationtoken_delete_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP_VERIFICATION', 'Signup Verification'), ('PASSWORD_RESET', 'Password Reset'), ('STAFF_INVITATION', 'Staff Invitation')], help_text='What this token authorizes.', max_length=32, verbose_name='Purpose'),
        ),
    ]
