# Generated by Django 5.2.14 on 2026-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emailverificationtoken_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='new_email',
            field=models.EmailField(blank=True, default='', help_text='Pending new email address, only populated for EMAIL_CHANGE-purpose tokens - applied to User.email once this token is confirmed.', max_length=254, verbose_name='New Email'),
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='purpose',
            field=models.CharField(choices=[('SIGNUP_VERIFICATION', 'Signup Verification'), ('PASSWORD_RESET', 'Password Reset'), ('WITHDRAWAL_CONFIRMATION', 'Withdrawal Confirmation'), ('STAFF_INVITATION', 'Staff Invitation'), ('EMAIL_CHANGE', 'Email Change')], help_text='What this token authorizes.', max_length=32, verbose_name='Purpose'),
        ),
    ]
