# Generated by Django 5.2.14 on 2026-08-07 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_emailverificationtoken_new_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "current_jti",
                    models.CharField(
                        db_index=True,
                        help_text="jti of whichever refresh token is currently valid for this session. Updated on every rotation.",
                        max_length=255,
                        verbose_name="Current JTI",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Bumped on login and on every token refresh.",
                        verbose_name="Last Seen At",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Revoked At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this session belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-last_seen_at"],
            },
        ),
    ]
