# Generated by Django 5.2.14 on 2026-08-07 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_usersession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "challenge_token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hex digest of the raw challenge token.",
                        max_length=64,
                        unique=True,
                        verbose_name="Challenge Token Hash",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Consumed At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this challenge was issued for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Challenge",
                "verbose_name_plural": "MFA Challenges",
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "secret_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted base32 TOTP secret. Never stored plaintext.",
                        verbose_name="Encrypted TOTP Secret",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="False until the enrollment confirm step succeeds.",
                        verbose_name="Is Enabled",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enrolled At"
                    ),
                ),
                (
                    "last_used_window",
                    models.BigIntegerField(
                        blank=True,
                        help_text="30-second time-step index of the most recently accepted code - replay guard, rejects a second submission in the same window.",
                        null=True,
                        verbose_name="Last Used Window",
                    ),
                ),
                (
                    "failed_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed Attempts"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this MFA device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_device",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Device",
                "verbose_name_plural": "MFA Devices",
            },
        ),
        migrations.CreateModel(
            name="MFARecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "code_encrypted",
                    models.TextField(
                        help_text="Fernet-encrypted recovery code. Never stored plaintext.",
                        verbose_name="Encrypted Code",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set the first time this code is consumed; null = unused.",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this recovery code belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Recovery Code",
                "verbose_name_plural": "MFA Recovery Codes",
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"], name="mfa_code_user_used_idx"
                    )
                ],
            },
        ),
    ]
