# Generated by Django 5.2.14 on 2026-09-07 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_mfachallenge_mfadevice_mfarecoverycode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "Google")],
                        help_text="External identity provider that issued the subject.",
                        max_length=20,
                        verbose_name="Provider",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Immutable provider-specific subject identifier.",
                        max_length=255,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Verified email reported when the identity was linked.",
                        max_length=254,
                        verbose_name="Provider Email",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Local user account authenticated by this external identity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Identity",
                "verbose_name_plural": "External Identities",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"),
                        name="unique_external_provider_subject",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "provider"),
                        name="unique_external_provider_per_user",
                    ),
                ],
            },
        ),
    ]
