# Generated by Django 5.2.14 on 2026-10-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_externalidentity'),
        ('wallet', '0008_alter_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='reference_request',
            field=models.ForeignKey(blank=True, help_text='The domain object this token authorizes an action on (currently a WithdrawalRequest), so an OTP issued for one request cannot confirm another. Only populated for request-scoped purposes such as WITHDRAWAL_CONFIRMATION.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='wallet.withdrawalrequest', verbose_name='Reference Request'),
        ),
    ]
