# Generated by Django 5.2.14 on 2026-10-09 17:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0019_course_revision_seat_course_video_attached_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('BLOCKED', 'Blocked by budget'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=10, verbose_name='Status')),
                ('quote_amount', models.DecimalField(decimal_places=2, help_text='Estimated cost of the whole run in USD, made before any spend.', max_digits=10, verbose_name='Quote')),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='The per-course budget in force when the run was quoted, in USD.', max_digits=10, verbose_name='Budget')),
                ('spent_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Actual spend so far, the sum of this run's ProductionCost rows.", max_digits=12, verbose_name='Spent')),
                ('status_reason', models.CharField(blank=True, default='', help_text='Why the run is blocked, failed or cancelled.', max_length=500, verbose_name='Status Reason')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Times a worker has started this run.', verbose_name='Attempts')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('dispatched_at', models.DateTimeField(blank=True, help_text='When the run was last handed to a worker, so the sweep does not re-send it.', null=True, verbose_name='Dispatched At')),
                ('heartbeat_at', models.DateTimeField(blank=True, help_text='Last sign of life from the worker; a stale one is re-dispatched.', null=True, verbose_name='Heartbeat At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('course', models.ForeignKey(help_text='Course being produced.', on_delete=django.db.models.deletion.CASCADE, related_name='production_runs', to='courses.course', verbose_name='Course')),
                ('requested_by', models.ForeignKey(blank=True, help_text="Whose action handed the course to the engine: the reviewer who approved a crawler course's text, or the creator who declined to make the video. The run's activity is logged on their record.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_production_runs', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Production Run',
                'verbose_name_plural': 'Production Runs',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProductionScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order')),
                ('scene_type', models.CharField(choices=[('TITLE', 'Title card'), ('BULLETS', 'Key points'), ('DIAGRAM', 'Diagram'), ('CODE', 'Code'), ('IMAGE', 'Illustration'), ('QUOTE', 'Quote or definition'), ('COMPARISON', 'Comparison'), ('RECAP', 'Recap')], help_text='Template the scene is rendered with.', max_length=12, verbose_name='Scene Type')),
                ('narration', models.TextField(help_text='Exact sentences from the approved script spoken over this scene.', verbose_name='Narration')),
                ('on_screen_text', models.CharField(blank=True, default='', help_text='Short text shown on screen, signalling the key point.', max_length=500, verbose_name='On-screen Text')),
                ('visual_brief', models.TextField(blank=True, default='', help_text='What the scene shows, for the visual step.', verbose_name='Visual Brief')),
                ('script_hash', models.CharField(help_text='SHA-256 of the lesson script the scene was planned from. A changed script means the storyboard is stale and is planned again.', max_length=64, verbose_name='Script Hash')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_scenes', to='courses.lesson', verbose_name='Lesson')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='production.productionrun', verbose_name='Run')),
            ],
            options={
                'verbose_name': 'Production Scene',
                'verbose_name_plural': 'Production Scenes',
                'ordering': ['lesson_id', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['status', '-created_datetime'], name='prodrun_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productionrun',
            index=models.Index(fields=['course', '-created_datetime'], name='prodrun_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('QUEUED', 'RUNNING', 'BLOCKED'))), fields=('course',), name='production_one_active_run_per_course'),
        ),
        migrations.AddConstraint(
            model_name='productionscene',
            constraint=models.UniqueConstraint(fields=('run', 'lesson', 'order'), name='production_scene_order_uniq'),
        ),
    ]
