# Generated by Django 5.2.14 on 2026-10-09 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_slug'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='instructions',
            field=models.JSONField(blank=True, default=dict, help_text='For a rework run, what reviewers asked the engine to redo: {"lessons": {"<lesson id>": ["REVOICE", ...]}, "flags": ["<flag id>", ...]}. Empty for a first production.', verbose_name='Rework Instructions'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='kind',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PACKAGE', 'Final package')], default='VIDEO', help_text='Video production (and rework), or the final package of a published course.', max_length=10, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='productionscene',
            name='bullets',
            field=models.JSONField(blank=True, default=list, help_text="Short lines drawn on the scene: key points, recap items, diagram steps (in order), or comparison rows written 'left | right'.", verbose_name='Bullets'),
        ),
        migrations.AddField(
            model_name='productionscene',
            name='code',
            field=models.TextField(blank=True, default='', help_text='The code shown on a CODE scene.', verbose_name='Code'),
        ),
        migrations.CreateModel(
            name='ChannelMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('channel', models.CharField(choices=[('SOLUDESK', 'SoluDesk'), ('UDEMY', 'Udemy'), ('COURSERA', 'Coursera')], max_length=10, verbose_name='Channel')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Version')),
                ('delivery_method', models.CharField(choices=[('API_PUSH', 'API push'), ('UPLOAD_KIT', 'Upload kit')], max_length=10, verbose_name='Delivery Method')),
                ('target_schema', models.JSONField(default=dict, help_text='JSON Schema of what the channel accepts.', verbose_name='Target Schema')),
                ('field_map', models.JSONField(default=dict, help_text="Target field path -> rule. A rule is {'from': '<package path>'}, optionally with 'transform': [...] and 'default'; {'const': value}; or {'each': '<package list path>', 'map': {<nested field map>}}.", verbose_name='Field Map')),
                ('response_id_path', models.CharField(blank=True, default='', help_text="API push only: where the channel's course id sits in its response, e.g. 'data.id'.", max_length=100, verbose_name='Response Id Path')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Channel Mapping',
                'verbose_name_plural': 'Channel Mappings',
                'ordering': ['channel', '-version'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'version'), name='production_mapping_version_uniq'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('channel',), name='production_mapping_one_active')],
            },
        ),
        migrations.CreateModel(
            name='ProductionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('key', models.CharField(help_text='SHA-256 of everything that went into the file.', max_length=64, unique=True, verbose_name='Input Hash')),
                ('kind', models.CharField(choices=[('NARRATION', 'Scene narration'), ('SLIDE', 'Scene visual'), ('LESSON_VIDEO', 'Lesson video'), ('TRAILER', 'Course trailer'), ('THUMBNAIL', 'Course thumbnail'), ('PACKAGE', 'Canonical course package'), ('SCORM_12', 'SCORM 1.2 export'), ('SCORM_2004', 'SCORM 2004 export'), ('UPLOAD_KIT', 'Channel upload kit')], max_length=12, verbose_name='Kind')),
                ('file_key', models.CharField(help_text='Object key in storage.', max_length=500, verbose_name='File Key')),
                ('content_type', models.CharField(max_length=100, verbose_name='Content Type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Size')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('data', models.JSONField(blank=True, default=dict, help_text='What later steps need from this file: narration timings, the measured quality evidence, the caption and transcript keys.', verbose_name='Data')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_assets', to='courses.course', verbose_name='Course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_assets', to='courses.lesson', verbose_name='Lesson')),
            ],
            options={
                'verbose_name': 'Production Asset',
                'verbose_name_plural': 'Production Assets',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['course', 'kind', '-created_datetime'], name='prodasset_course_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='PronunciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('term', models.CharField(max_length=100, verbose_name='Term')),
                ('spoken_as', models.CharField(help_text="What the voice is given instead, e.g. 'koo-ber-NET-eez'.", max_length=200, verbose_name='Spoken As')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Pronunciation',
                'verbose_name_plural': 'Pronunciations',
                'ordering': ['term'],
                'constraints': [models.UniqueConstraint(fields=('course', 'term'), name='production_pronunciation_uniq')],
            },
        ),
    ]
