# Generated by Django 5.2.14 on 2026-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_seed_channel_mappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionasset',
            name='kind',
            field=models.CharField(choices=[('NARRATION', 'Scene narration'), ('SLIDE', 'Scene visual'), ('BROLL', 'B-roll clip'), ('LESSON_VIDEO', 'Lesson video'), ('TRAILER', 'Course trailer'), ('THUMBNAIL', 'Course thumbnail'), ('PACKAGE', 'Canonical course package'), ('SCORM_12', 'SCORM 1.2 export'), ('SCORM_2004', 'SCORM 2004 export'), ('UPLOAD_KIT', 'Channel upload kit')], max_length=12, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='productionscene',
            name='scene_type',
            field=models.CharField(choices=[('TITLE', 'Title card'), ('BULLETS', 'Key points'), ('DIAGRAM', 'Diagram'), ('CODE', 'Code'), ('IMAGE', 'Illustration'), ('QUOTE', 'Quote or definition'), ('COMPARISON', 'Comparison'), ('RECAP', 'Recap'), ('BROLL', 'Motion footage')], help_text='Template the scene is rendered with.', max_length=12, verbose_name='Scene Type'),
        ),
    ]
