# Generated by Tses 2026-07-09T12:37:38Z
# Generated by Django 5.2.14 on 2026-06-22 21:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('type', models.CharField(choices=[('SMS', 'Sms'), ('EMAIL', 'Email'), ('IN_APP', 'In App'), ('PUSH', 'Push')], help_text='Type of notification', max_length=32, verbose_name='Type')),
                ('title', models.CharField(help_text='Title of the notification', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Content of the notification', verbose_name='Content')),
                ('content_type', models.CharField(choices=[('TEXT', 'Text'), ('HTML', 'Html'), ('JSON', 'Json')], help_text='Content type of the notification', max_length=32, verbose_name='Content Type')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read', verbose_name='Is Read')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for the notification, such as payload data or media links', null=True, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
