# Generated by Tses 2026-07-09T12:37:38Z
# Generated by Django 5.2.14 on 2026-06-22 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', related_query_name='received_notification', to=settings.AUTH_USER_MODEL, verbose_name='Receiver'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_read', 'created_datetime'], name='notif_receiver_read_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_datetime'], name='notif_type_created_dt_idx'),
        ),
    ]
