# Generated by Django 5.2.14 on 2026-07-19 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('new_course_assigned', models.BooleanField(default=True, help_text='Notify when a course is assigned to this reviewer.', verbose_name='New Course Assigned')),
                ('escalation_assigned', models.BooleanField(default=True, help_text='Notify when an escalation is assigned (QA Reviewer only).', verbose_name='Escalation Assigned')),
                ('creator_feedback', models.BooleanField(default=True, help_text='Notify when a creator appeals a course decision.', verbose_name='Creator Feedback')),
                ('sla_amber_warning', models.BooleanField(default=True, help_text='Notify when a course in the queue hits the amber threshold.', verbose_name='SLA Amber Warning')),
                ('sla_red_critical_alert', models.BooleanField(default=True, help_text='Notify when a course hits the critical threshold.', verbose_name='SLA Red Critical Alert')),
                ('sla_breached', models.BooleanField(default=True, help_text='Notify immediately when the SLA window is missed.', verbose_name='SLA Breached')),
                ('user', models.OneToOneField(help_text='User these notification preferences belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
