# Generated by Django 5.2.14 on 2026-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='account_deletion_detection_alert',
            field=models.BooleanField(default=True, help_text='Reserved for a future suspicious-deletion detection system - no trigger exists yet, same idiom as the PRODUCTION/ALERT activity categories.', verbose_name='Account/Course Deletion Detection Alert'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='kyc_submission_alert',
            field=models.BooleanField(default=True, help_text='Notify Admins/Super Admins when a new KYC submission arrives.', verbose_name='KYC Submission Alert'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='mie_pipeline_alert',
            field=models.BooleanField(default=True, help_text='Reserved for the AI Auto-Production Engine, which is not implemented in this backend - inert while AI Creator is unavailable.', verbose_name='MIE Pipeline Alert'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='mie_recommendation_alert',
            field=models.BooleanField(default=True, help_text='Reserved for the Market Intelligence Engine, which is not implemented in this backend - inert while AI Creator is unavailable.', verbose_name='MIE Recommendation Alert'),
        ),
    ]
