# Generated by Django 5.2.14 on 2026-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0004_notificationpreference_account_deletion_detection_alert_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="in_app_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master toggle for in-app notifications. Off suppresses all in-app alerts regardless of the per-event toggles above.",
                verbose_name="In-App Notifications Enabled",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sla_amber_threshold_hours_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides PlatformSettings.sla_amber_threshold_hours for this reviewer. Null uses the platform default.",
                null=True,
                verbose_name="SLA Amber Threshold Hours Override",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sla_red_threshold_hours_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Overrides PlatformSettings.sla_red_threshold_hours for this reviewer. Null uses the platform default.",
                null=True,
                verbose_name="SLA Red Threshold Hours Override",
            ),
        ),
    ]
