# Generated by Django 5.2.14 on 2026-09-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0005_notificationpreference_in_app_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="in_app_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master toggle for in-app notifications. Off suppresses every in-app notification except critical operational alerts (see Notification.emit_in_app_notification).",
                verbose_name="In-App Notifications Enabled",
            ),
        ),
    ]
