# Generated by Django 5.2.14 on 2026-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notificationpreference_in_app_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='course_update',
            field=models.BooleanField(default=True, help_text='Notify admins (holders of courses.assign) when someone else submits, approves, rejects or publishes a course.', verbose_name='Course Update'),
        ),
    ]
