# Generated by Django 5.2.14 on 2026-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notificationpreference_course_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='mie_pipeline_alert',
            field=models.BooleanField(default=True, help_text='Production Engine alerts: a production run blocked by the budget or failed. Sent to holders of `production.manage`.', verbose_name='MIE Pipeline Alert'),
        ),
    ]
