# Generated by Django 5.2.14 on 2026-08-22 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_module_description_module_learning_objectives_and_more"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityCheckCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Wizard section this criterion appears under, e.g. 'Course information', 'Course Outline', 'Thumbnail'.",
                        max_length=100,
                        verbose_name="Section",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Checklist item text, e.g. 'Course title', 'Learning objectives'.",
                        max_length=255,
                        verbose_name="Label",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position within the section.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False retires the criterion from new checks; history is kept.",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Check Criterion",
                "verbose_name_plural": "Quality Check Criteria",
                "ordering": ["section", "order_index"],
                "indexes": [
                    models.Index(fields=["section"], name="qc_criterion_section_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseQualityCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "is_checked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the course currently satisfies this criterion.",
                        verbose_name="Is Checked",
                    ),
                ),
                (
                    "warning_note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Shortfall message shown when the criterion is not met.",
                        max_length=500,
                        verbose_name="Warning Note",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this result was last computed.",
                        null=True,
                        verbose_name="Checked At",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this result belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_checks",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        help_text="The checklist item this result is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="reviews.qualitycheckcriterion",
                        verbose_name="Criterion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Quality Check",
                "verbose_name_plural": "Course Quality Checks",
                "ordering": ["criterion__section", "criterion__order_index"],
                "indexes": [
                    models.Index(fields=["course"], name="qc_result_course_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "criterion"),
                        name="unique_quality_check_per_criterion",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        help_text="Machine-readable issue category, e.g. 'script_length', 'missing_media', 'quiz_incomplete'.",
                        max_length=50,
                        verbose_name="Flag Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short headline shown in the issues list.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "system_message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-generated detail, e.g. '306/500 words below minimum'.",
                        max_length=500,
                        verbose_name="System Message",
                    ),
                ),
                (
                    "reviewer_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reviewer's guidance for resolving the issue.",
                        verbose_name="Reviewer Note",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the creator has addressed this issue.",
                        verbose_name="Is Resolved",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the issue was marked resolved.",
                        null=True,
                        verbose_name="Resolved At",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lesson this issue is scoped to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_flags",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        help_text="Module this issue is scoped to, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_flags",
                        to="courses.module",
                        verbose_name="Module",
                    ),
                ),
                (
                    "review_action",
                    models.ForeignKey(
                        help_text="The review decision this flag was raised in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="reviews.reviewaction",
                        verbose_name="Review Action",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Flag",
                "verbose_name_plural": "Review Flags",
                "ordering": ["review_action", "created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["review_action"], name="review_flag_action_idx"
                    ),
                    models.Index(fields=["lesson"], name="review_flag_lesson_idx"),
                ],
            },
        ),
    ]
