# Generated by Django 5.2.14 on 2026-09-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_retire_lesson_quiz_quality_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewaction',
            name='stage',
            field=models.CharField(choices=[('CONTENT', 'First Review'), ('SECOND_REVIEW', 'Second Review'), ('VERIFICATION', 'Verification'), ('QA', 'QA Verification')], default='CONTENT', help_text='Quality gate at which this decision was made.', max_length=20, verbose_name='Review Stage'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='stage',
            field=models.CharField(choices=[('CONTENT', 'First Review'), ('SECOND_REVIEW', 'Second Review'), ('VERIFICATION', 'Verification'), ('QA', 'QA Verification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='stage',
            field=models.CharField(choices=[('CONTENT', 'First Review'), ('SECOND_REVIEW', 'Second Review'), ('VERIFICATION', 'Verification'), ('QA', 'QA Verification')], max_length=20),
        ),
    ]
