# Generated by Tses 2026-07-09T12:37:38Z
from django.db import models


class NotificationType(models.TextChoices):
    """Supported delivery channels for scaffold notifications.

    Projects can add more channels here, such as webhook or WhatsApp delivery,
    as long as corresponding service-layer implementations are introduced.
    """

    SMS = "SMS"
    EMAIL = "EMAIL"
    IN_APP = "IN_APP"
    PUSH = "PUSH"


class NotificationContentType(models.TextChoices):
    """Content formats a notification payload may use.

    Extend this when a project needs richer rendering modes, but keep the values
    stable so clients can branch on them reliably.
    """

    TEXT = "TEXT"
    HTML = "HTML"
    JSON = "JSON"
