# Generated by Tses 2026-07-09T12:37:38Z
import json
import logging

from django.contrib.auth import get_user_model
from django.db import IntegrityError, models
from django.utils.translation import gettext_lazy as _
from rest_framework import exceptions as rest_exceptions

from api.notification import enums as notification_enums
from api.notification.services import email_service
from core.mixins import DateHistoryModelMixin, UUIDPrimaryKeyModelMixin

logger = logging.getLogger(__name__)


class Notification(UUIDPrimaryKeyModelMixin, DateHistoryModelMixin):
    """Persist notifications independently from their delivery mechanism.

    The model is intentionally transport-agnostic. Projects can keep in-app
    notifications here, while implementing email, SMS, and push delivery in
    dedicated services, tasks, or adapters.
    """

    type = models.CharField(
        verbose_name=_("Type"),
        max_length=32,
        choices=notification_enums.NotificationType.choices,
        help_text=_("Type of notification"),
    )
    title = models.CharField(
        verbose_name=_("Title"),
        max_length=255,
        help_text=_("Title of the notification"),
    )
    content = models.TextField(
        verbose_name=_("Content"),
        help_text=_("Content of the notification"),
    )
    content_type = models.CharField(
        verbose_name=_("Content Type"),
        max_length=32,
        choices=notification_enums.NotificationContentType.choices,
        help_text=_("Content type of the notification"),
    )
    is_read = models.BooleanField(
        verbose_name=_("Is Read"),
        default=False,
        help_text=_("Whether the notification has been read"),
    )
    metadata = models.JSONField(
        verbose_name=_("Metadata"),
        null=True,
        blank=True,
        default=dict,
        help_text=_(
            "Additional metadata for the notification, such as payload data or media links"
        ),
    )
    receiver = models.ForeignKey(
        "users.User",
        verbose_name=_("Receiver"),
        on_delete=models.CASCADE,
        related_name="received_notifications",
        related_query_name="received_notification",
        help_text=_("User receiving the notification"),
    )

    class Meta:
        verbose_name = _("Notification")
        verbose_name_plural = _("Notifications")
        ordering = ["-created_datetime"]
        indexes = [
            models.Index(
                fields=["receiver", "is_read", "created_datetime"],
                name="notif_receiver_read_dt_idx",
            ),
            models.Index(
                fields=["type", "created_datetime"],
                name="notif_type_created_dt_idx",
            ),
        ]

    def __str__(self):
        """Use the notification title as the default human-readable label."""

        return self.title

    @classmethod
    def create_notification(cls, **kwargs):
        """Create a single notification record with consistent error handling.

        Call this from service-layer code when a project wants a lightweight
        persistence helper without coupling to transport-specific delivery code.
        """

        try:
            return cls.objects.create(**kwargs)
        except IntegrityError as exc:
            logger.exception("Error creating notification: %s", exc)
            raise rest_exceptions.ValidationError(
                "Error creating notification"
            ) from exc

    @classmethod
    def get_notifications(cls, **kwargs):
        """Return a filtered queryset for project-specific list views or services."""

        return cls.objects.filter(**kwargs)

    @staticmethod
    def _serialize_for_json(value):
        """Convert complex values into JSON-safe metadata payloads.

        Override this if a project needs richer serialization rules for custom
        domain objects stored in notification metadata.
        """

        user_model = get_user_model()
        if isinstance(value, user_model):
            return {
                "pk": str(value.pk),
                "email": value.email,
                "first_name": getattr(value, "first_name", ""),
                "last_name": getattr(value, "last_name", ""),
            }
        if isinstance(value, models.Model):
            return getattr(value, "pk", str(value))
        if isinstance(value, (list, tuple, set)):
            return [Notification._serialize_for_json(item) for item in value]
        if isinstance(value, dict):
            return {
                key: Notification._serialize_for_json(val) for key, val in value.items()
            }
        if isinstance(value, (str, int, float, bool)) or value is None:
            return value
        try:
            json.dumps(value)
            return value
        except TypeError:
            return str(value)

    @staticmethod
    def _resolve_user(receiver):
        """Accept either a user instance or primary key for notification receivers."""

        user_model = get_user_model()
        if isinstance(receiver, user_model):
            return receiver
        try:
            return user_model.objects.get(pk=receiver)
        except user_model.DoesNotExist as exc:
            raise rest_exceptions.ValidationError(
                f"Receiver with id {receiver} not found"
            ) from exc

    @classmethod
    def emit_email_notification(
        cls,
        *,
        receivers,
        subject,
        template_name,
        context=None,
        metadata=None,
        from_email=None,
        cc_emails=None,
        bcc_emails=None,
        reply_to=None,
        attachments=None,
        fail_silently=False,
    ):
        """Send a templated email via api.notification.services.email_service.

        Accepts the same receivers shapes as emit_in_app_notification (a User
        instance, a user pk, or a raw email address string), plus any mix of
        those in a list.
        """

        if not receivers:
            raise rest_exceptions.ValidationError("At least one receiver is required")

        if not isinstance(receivers, (list, tuple, set)):
            receivers = [receivers]

        email_addresses = [cls._resolve_email(receiver) for receiver in receivers]

        return email_service.send_templated_email(
            receivers=email_addresses,
            subject=subject,
            template_name=template_name,
            context=context,
            from_email=from_email,
            cc_emails=cc_emails,
            bcc_emails=bcc_emails,
            reply_to=reply_to,
            attachments=attachments,
            fail_silently=fail_silently,
        )

    @classmethod
    def _resolve_email(cls, receiver):
        """Resolve a receiver (User instance, user pk, or raw email) to an email address."""

        user_model = get_user_model()
        if isinstance(receiver, user_model):
            return receiver.email
        if isinstance(receiver, str) and "@" in receiver:
            return receiver
        return cls._resolve_user(receiver).email

    @classmethod
    def emit_sms_notification(cls, sender, receivers: list, title, content):
        """Extension point for SMS delivery implementations."""

        raise NotImplementedError(
            "SMS notification delivery should be implemented in a service layer"
        )

    @classmethod
    def emit_in_app_notification(
        cls,
        *,
        receivers,
        title,
        content,
        metadata=None,
        content_type=notification_enums.NotificationContentType.TEXT,
    ):
        """Create one or more persisted in-app notifications.

        This is the only delivery helper implemented directly in the scaffold,
        because it maps cleanly to database persistence without external provider
        dependencies. Teams can wrap or override it if their in-app flow needs
        fan-out rules, deduplication, or asynchronous dispatch.
        """

        if not receivers:
            raise rest_exceptions.ValidationError("At least one receiver is required")

        if not isinstance(receivers, (list, tuple, set)):
            receivers = [receivers]

        serialized_metadata = cls._serialize_for_json(metadata or {})
        resolved_receivers = [cls._resolve_user(receiver) for receiver in receivers]
        notifications = [
            cls(
                type=notification_enums.NotificationType.IN_APP,
                title=title,
                content=content,
                content_type=content_type,
                metadata=serialized_metadata,
                receiver=receiver,
            )
            for receiver in resolved_receivers
        ]
        return cls.objects.bulk_create(notifications)

    @classmethod
    def emit_push_notification(cls):
        """Extension point for push delivery implementations."""

        raise NotImplementedError(
            "Push notification delivery should be implemented in a service layer"
        )

    @classmethod
    def get_notification(cls, **kwargs):
        """Return a single notification or raise a scaffold-friendly 404 error."""

        try:
            return cls.objects.get(**kwargs)
        except cls.DoesNotExist as exc:
            raise rest_exceptions.NotFound("Notification not found") from exc


class NotificationPreference(UUIDPrimaryKeyModelMixin, DateHistoryModelMixin):
    """Per-user toggles for which alert types a Creator Reviewer wants to
    receive. Preference storage only - it does not implement the underlying
    SLA-threshold detection/alerting system itself (not built yet); toggling
    sla_breached off, for instance, has no effect until that system exists.

    Lazily provisioned via notification_preference_service.get_or_create,
    mirroring CreatorProfile/ReviewerAvailability - no row exists until a
    user first opens their Notification settings.
    """

    user = models.OneToOneField(
        "users.User",
        verbose_name=_("User"),
        on_delete=models.CASCADE,
        related_name="notification_preference",
        help_text=_("User these notification preferences belong to."),
    )
    new_course_assigned = models.BooleanField(
        verbose_name=_("New Course Assigned"),
        default=True,
        help_text=_("Notify when a course is assigned to this reviewer."),
    )
    escalation_assigned = models.BooleanField(
        verbose_name=_("Escalation Assigned"),
        default=True,
        help_text=_("Notify when an escalation is assigned (QA Reviewer only)."),
    )
    creator_feedback = models.BooleanField(
        verbose_name=_("Creator Feedback"),
        default=True,
        help_text=_("Notify when a creator appeals a course decision."),
    )
    sla_amber_warning = models.BooleanField(
        verbose_name=_("SLA Amber Warning"),
        default=True,
        help_text=_("Notify when a course in the queue hits the amber threshold."),
    )
    sla_red_critical_alert = models.BooleanField(
        verbose_name=_("SLA Red Critical Alert"),
        default=True,
        help_text=_("Notify when a course hits the critical threshold."),
    )
    sla_breached = models.BooleanField(
        verbose_name=_("SLA Breached"),
        default=True,
        help_text=_("Notify immediately when the SLA window is missed."),
    )
    kyc_submission_alert = models.BooleanField(
        verbose_name=_("KYC Submission Alert"),
        default=True,
        help_text=_("Notify Admins/Super Admins when a new KYC submission arrives."),
    )
    account_deletion_detection_alert = models.BooleanField(
        verbose_name=_("Account/Course Deletion Detection Alert"),
        default=True,
        help_text=_(
            "Reserved for a future suspicious-deletion detection system - no "
            "trigger exists yet, same idiom as the PRODUCTION/ALERT activity "
            "categories."
        ),
    )
    mie_recommendation_alert = models.BooleanField(
        verbose_name=_("MIE Recommendation Alert"),
        default=True,
        help_text=_(
            "Reserved for the Market Intelligence Engine, which is not "
            "implemented in this backend - inert while AI Creator is unavailable."
        ),
    )
    mie_pipeline_alert = models.BooleanField(
        verbose_name=_("MIE Pipeline Alert"),
        default=True,
        help_text=_(
            "Reserved for the AI Auto-Production Engine, which is not "
            "implemented in this backend - inert while AI Creator is unavailable."
        ),
    )
    in_app_enabled = models.BooleanField(
        verbose_name=_("In-App Notifications Enabled"),
        default=True,
        help_text=_(
            "Master toggle for in-app notifications. Off suppresses all "
            "in-app alerts regardless of the per-event toggles above."
        ),
    )
    sla_amber_threshold_hours_override = models.PositiveIntegerField(
        verbose_name=_("SLA Amber Threshold Hours Override"),
        null=True,
        blank=True,
        help_text=_(
            "Overrides PlatformSettings.sla_amber_threshold_hours for this "
            "reviewer. Null uses the platform default."
        ),
    )
    sla_red_threshold_hours_override = models.PositiveIntegerField(
        verbose_name=_("SLA Red Threshold Hours Override"),
        null=True,
        blank=True,
        help_text=_(
            "Overrides PlatformSettings.sla_red_threshold_hours for this "
            "reviewer. Null uses the platform default."
        ),
    )

    class Meta:
        verbose_name = _("Notification Preference")
        verbose_name_plural = _("Notification Preferences")

    def __str__(self):
        """Use the owning user's id as the human-readable label."""

        return f"NotificationPreference({self.user_id})"
