# Generated by Tses 2026-07-09T12:37:38Z
from rest_framework import serializers

from api.notification.models import NotificationPreference


class NotificationPreferenceSerializer(serializers.ModelSerializer):
    """Read-only representation of the current user's notification preferences."""

    class Meta:
        model = NotificationPreference
        fields = [
            "id",
            "new_course_assigned",
            "escalation_assigned",
            "creator_feedback",
            "sla_amber_warning",
            "sla_red_critical_alert",
            "sla_breached",
            "kyc_submission_alert",
            "account_deletion_detection_alert",
            "mie_recommendation_alert",
            "mie_pipeline_alert",
            "in_app_enabled",
            "course_update",
            "sla_amber_threshold_hours_override",
            "sla_red_threshold_hours_override",
        ]
        read_only_fields = fields


class NotificationPreferenceUpdateSerializer(serializers.Serializer):
    """Write serializer for PATCH /users/me/notification-preferences/.
    Every field is optional so a client can toggle just one at a time."""

    new_course_assigned = serializers.BooleanField(
        required=False,
        help_text="Notify when a course is assigned to this reviewer.",
    )
    escalation_assigned = serializers.BooleanField(
        required=False,
        help_text="Reserved: nothing sends escalation notifications yet.",
    )
    creator_feedback = serializers.BooleanField(
        required=False,
        help_text="Notify appeal deciders when a creator appeals a rejection.",
    )
    sla_amber_warning = serializers.BooleanField(
        required=False,
        help_text="Reserved: nothing sends amber SLA warnings yet.",
    )
    sla_red_critical_alert = serializers.BooleanField(
        required=False,
        help_text=(
            "Notify course approvers when a course passes the red SLA "
            "threshold. This is the admin 'Review SLA Breach Alert' toggle."
        ),
    )
    sla_breached = serializers.BooleanField(
        required=False,
        help_text="Reserved: nothing sends SLA-breached notifications yet.",
    )
    kyc_submission_alert = serializers.BooleanField(
        required=False,
        help_text="Notify account approvers when a new KYC submission arrives.",
    )
    account_deletion_detection_alert = serializers.BooleanField(
        required=False,
        help_text="Reserved: no deletion-detection system exists yet.",
    )
    mie_recommendation_alert = serializers.BooleanField(
        required=False,
        help_text="Reserved: nothing sends MIE recommendation alerts yet.",
    )
    mie_pipeline_alert = serializers.BooleanField(
        required=False,
        help_text="Reserved: nothing sends MIE pipeline alerts yet.",
    )
    in_app_enabled = serializers.BooleanField(
        required=False,
        help_text=(
            "Master toggle for in-app notifications. Off suppresses all but "
            "critical operational alerts."
        ),
    )
    course_update = serializers.BooleanField(
        required=False,
        help_text=(
            "Notify admins (holders of courses.assign) when someone else "
            "submits, approves, rejects or publishes a course."
        ),
    )
    sla_amber_threshold_hours_override = serializers.IntegerField(
        required=False,
        allow_null=True,
        min_value=1,
        help_text=(
            "This reviewer's amber SLA threshold in hours, used by the review "
            "queue's SLA-urgency sort. Null uses the platform default."
        ),
    )
    sla_red_threshold_hours_override = serializers.IntegerField(
        required=False,
        allow_null=True,
        min_value=1,
        help_text=(
            "This reviewer's red SLA threshold in hours, used by the review "
            "queue's SLA-urgency sort. Null uses the platform default."
        ),
    )

    def validate(self, attrs):
        if not attrs:
            raise serializers.ValidationError(
                "At least one notification preference must be provided."
            )
        return attrs


class NotificationReadSerializer(serializers.Serializer):
    """Serializer for marking a notification as read."""

    notification_id = serializers.UUIDField(
        required=True,
        help_text="UUID of the notification to update. Must belong to the authenticated user.",
    )
    read_status = serializers.BooleanField(
        required=True,
        help_text="Set to true to mark as read, or false to mark as unread.",
    )
