# Generated by Tses 2026-07-09T12:37:38Z
import asyncio
import json

from django.core import mail
from django.test import TestCase
from rest_framework import status
from rest_framework.test import APITestCase, APITransactionTestCase

from api.authentication.tests.factories import make_user
from api.notification.enums import NotificationType
from api.notification.models import Notification, NotificationPreference
from api.notification.services import (
    notification_preference_service,
    sla_threshold_service,
)
from api.platform.services import platform_settings_service
from api.users.models import UserActivityLog


class EmitEmailNotificationTests(TestCase):
    def test_sends_email_via_configured_templates(self):
        sent_count = Notification.emit_email_notification(
            receivers=["someone@example.com"],
            subject="Test Subject",
            template_name="emails/email_verification",
            context={
                "first_name": "Ada",
                "verification_link": "http://localhost:3000/verify-email?token=abc123",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(sent_count, 1)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("someone@example.com", mail.outbox[0].to)
        self.assertEqual(mail.outbox[0].subject, "Test Subject")
        self.assertIn(
            "http://localhost:3000/verify-email?token=abc123", mail.outbox[0].body
        )

    def test_resolves_user_instance_receiver_to_email(self):
        from api.authentication.tests.factories import make_user

        user = make_user(email="resolveme@example.com")

        Notification.emit_email_notification(
            receivers=[user],
            subject="Hello",
            template_name="emails/email_verification",
            context={
                "first_name": user.first_name,
                "verification_link": "http://localhost:3000/verify-email?token=xyz789",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("resolveme@example.com", mail.outbox[0].to)

    def test_raises_when_no_receivers(self):
        from rest_framework.exceptions import ValidationError

        with self.assertRaises(ValidationError):
            Notification.emit_email_notification(
                receivers=[], subject="X", template_name="emails/email_verification"
            )


class NotificationPreferenceServiceTests(TestCase):
    def test_get_or_create_returns_same_row_with_defaults_all_true(self):
        user = make_user()

        first = notification_preference_service.get_or_create_preference(user=user)
        second = notification_preference_service.get_or_create_preference(user=user)

        self.assertEqual(first.id, second.id)
        self.assertTrue(first.new_course_assigned)
        self.assertTrue(first.sla_breached)
        self.assertEqual(NotificationPreference.objects.filter(user=user).count(), 1)

    def test_update_only_touches_provided_fields(self):
        user = make_user()

        notification_preference_service.update_preference(
            user=user, new_course_assigned=False
        )
        result = notification_preference_service.get_or_create_preference(user=user)

        self.assertFalse(result.new_course_assigned)
        self.assertTrue(result.sla_breached)


class NotificationPreferenceApiTests(APITestCase):
    def test_requires_authentication(self):
        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_get_lazily_creates_defaults(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["new_course_assigned"])
        self.assertTrue(response.data["sla_breached"])

    def test_patch_toggles_one_preference(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_breached": False},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertFalse(response.data["sla_breached"])
        self.assertTrue(response.data["new_course_assigned"])

    def test_admin_facing_fields_default_true_and_round_trip(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertTrue(response.data["kyc_submission_alert"])
        self.assertTrue(response.data["account_deletion_detection_alert"])
        self.assertTrue(response.data["mie_recommendation_alert"])
        self.assertTrue(response.data["mie_pipeline_alert"])

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"kyc_submission_alert": False},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertFalse(response.data["kyc_submission_alert"])

    def test_patch_empty_body_rejected(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/", {}, format="json"
        )
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_patch_logs_configuration_activity(self):
        user = make_user()
        self.client.force_authenticate(user)

        self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_breached": False},
            format="json",
        )

        self.assertTrue(
            UserActivityLog.objects.filter(
                user=user, action="NOTIFICATION_PREFERENCES_UPDATED"
            ).exists()
        )

    def test_in_app_enabled_defaults_true_and_can_be_toggled(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertTrue(response.data["in_app_enabled"])

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"in_app_enabled": False},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertFalse(response.data["in_app_enabled"])

    def test_sla_threshold_overrides_default_null_and_round_trip(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertIsNone(response.data["sla_amber_threshold_hours_override"])
        self.assertIsNone(response.data["sla_red_threshold_hours_override"])

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_amber_threshold_hours_override": 12},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["sla_amber_threshold_hours_override"], 12)

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_amber_threshold_hours_override": None},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIsNone(response.data["sla_amber_threshold_hours_override"])


class NotificationStreamApiTests(APITransactionTestCase):
    def test_requires_authentication(self):
        response = self.client.get(
            "/api/v1/users/me/notifications/streamed-notifications/"
        )

        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_returns_sse_headers_for_authenticated_user(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get(
            "/api/v1/users/me/notifications/streamed-notifications/"
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response["Content-Type"].startswith("text/event-stream"))
        self.assertEqual(response["Cache-Control"], "no-cache")
        self.assertEqual(response["X-Accel-Buffering"], "no")
        asyncio.run(response.streaming_content.aclose())

    def test_initial_event_uses_persisted_notifications_with_scope_limit_and_order(
        self,
    ):
        user = make_user()
        other_user = make_user()
        self.client.force_authenticate(user)

        for index in range(25):
            Notification.objects.create(
                receiver=user,
                type=NotificationType.IN_APP,
                title=f"In-app {index}",
                content=f"In-app content {index}",
                content_type="TEXT",
                metadata={"index": index},
            )

        Notification.objects.create(
            receiver=user,
            type=NotificationType.EMAIL,
            title="Email notification",
            content="Should not appear in stream",
            content_type="TEXT",
        )
        Notification.objects.create(
            receiver=other_user,
            type=NotificationType.IN_APP,
            title="Other user's notification",
            content="Should not appear in stream",
            content_type="TEXT",
        )

        response = self.client.get(
            "/api/v1/users/me/notifications/streamed-notifications/"
        )

        async def _read_first_chunk(streaming_content):
            return await anext(streaming_content)

        first_chunk = asyncio.run(_read_first_chunk(response.streaming_content)).decode(
            "utf-8"
        )
        asyncio.run(response.streaming_content.aclose())

        self.assertTrue(first_chunk.startswith("data: "))
        self.assertTrue(first_chunk.endswith("\n\n"))

        payload = json.loads(first_chunk.removeprefix("data: ").strip())
        self.assertEqual(len(payload), 20)
        self.assertEqual(payload[0]["title"], "In-app 24")
        self.assertEqual(payload[-1]["title"], "In-app 5")
        self.assertTrue(all(item["title"].startswith("In-app") for item in payload))


class NotificationListApiTests(APITestCase):
    def test_returns_cursor_paginated_notifications(self):
        user = make_user()
        self.client.force_authenticate(user)

        for index in range(15):
            Notification.objects.create(
                receiver=user,
                type=NotificationType.IN_APP,
                title=f"Notification {index}",
                content=f"Content {index}",
                content_type="TEXT",
                metadata={"index": index},
            )

        response = self.client.get("/api/v1/users/me/notifications/", {"size": 10})

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data["data"]["results"]), 10)
        self.assertIn("next", response.data["data"]["paginator"])
        self.assertIsNotNone(response.data["data"]["paginator"]["next"])

    def test_filters_notifications_by_is_read(self):
        user = make_user()
        self.client.force_authenticate(user)

        Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Unread notification",
            content="Unread content",
            content_type="TEXT",
            is_read=False,
        )
        Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Read notification 1",
            content="Read content 1",
            content_type="TEXT",
            is_read=True,
        )
        Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Read notification 2",
            content="Read content 2",
            content_type="TEXT",
            is_read=True,
        )

        all_response = self.client.get("/api/v1/users/me/notifications/", {"size": 10})
        read_response = self.client.get(
            "/api/v1/users/me/notifications/", {"is_read": "true", "size": 10}
        )
        self.assertEqual(read_response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(read_response.data["data"]["results"]), 2)
        self.assertTrue(
            all(item["is_read"] for item in read_response.data["data"]["results"])
        )

        unread_response = self.client.get(
            "/api/v1/users/me/notifications/", {"is_read": "false", "size": 10}
        )
        self.assertEqual(unread_response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(unread_response.data["data"]["results"]), 1)
        self.assertEqual(len(read_response.data["data"]["results"]), 2)
        self.assertEqual(len(all_response.data["data"]["results"]), 3)
        self.assertFalse(unread_response.data["data"]["results"][0]["is_read"])

    def test_only_returns_authenticated_users_notifications(self):
        user = make_user()
        other_user = make_user()
        self.client.force_authenticate(user)

        own_first = Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Own notification 1",
            content="Own content 1",
            content_type="TEXT",
        )
        own_second = Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Own notification 2",
            content="Own content 2",
            content_type="TEXT",
        )

        for index in range(3):
            Notification.objects.create(
                receiver=other_user,
                type=NotificationType.IN_APP,
                title=f"Other notification {index}",
                content=f"Other content {index}",
                content_type="TEXT",
            )

        response = self.client.get("/api/v1/users/me/notifications/", {"size": 10})

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        results = response.data["data"]["results"]
        self.assertEqual(len(results), 2)
        returned_ids = {item["id"] for item in results}
        self.assertEqual(returned_ids, {own_first.id, own_second.id})


class NotificationReadToggleApiTests(APITestCase):
    def test_requires_authentication(self):
        response = self.client.post(
            "/api/v1/users/me/notifications/toggle-read/",
            {
                "notification_id": "6cb7adf1-5543-4f36-9cd3-c698f6577391",
                "read_status": True,
            },
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_marks_notification_as_read_for_authenticated_user(self):
        user = make_user()
        self.client.force_authenticate(user)
        notification = Notification.objects.create(
            receiver=user,
            type=NotificationType.IN_APP,
            title="Unread notification",
            content="Unread content",
            content_type="TEXT",
            is_read=False,
        )

        response = self.client.post(
            "/api/v1/users/me/notifications/toggle-read/",
            {"notification_id": str(notification.id), "read_status": True},
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["success"])
        self.assertEqual(
            response.data["message"],
            f"Notification {notification.id} marked as read.",
        )
        notification.refresh_from_db()
        self.assertTrue(notification.is_read)

    def test_returns_not_found_when_notification_does_not_belong_to_user(self):
        user = make_user()
        other_user = make_user()
        self.client.force_authenticate(user)
        other_notification = Notification.objects.create(
            receiver=other_user,
            type=NotificationType.IN_APP,
            title="Other user's notification",
            content="Other user's content",
            content_type="TEXT",
            is_read=False,
        )

        response = self.client.post(
            "/api/v1/users/me/notifications/toggle-read/",
            {"notification_id": str(other_notification.id), "read_status": True},
            format="json",
        )

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)
        self.assertEqual(response.data["errors"][0]["code"], "not_found")
        self.assertEqual(
            response.data["errors"][0]["message"],
            f"Notification {other_notification.id} not found for user {user.id}.",
        )


class SlaThresholdServiceTests(TestCase):
    def test_falls_back_to_platform_defaults_when_no_override(self):
        user = make_user()

        amber, red = sla_threshold_service.get_effective_thresholds(user=user)

        self.assertEqual(amber, 24)
        self.assertEqual(red, 48)

    def test_uses_reviewer_override_when_set(self):
        user = make_user()
        notification_preference_service.update_preference(
            user=user,
            sla_amber_threshold_hours_override=6,
            sla_red_threshold_hours_override=12,
        )

        amber, red = sla_threshold_service.get_effective_thresholds(user=user)

        self.assertEqual(amber, 6)
        self.assertEqual(red, 12)

    def test_platform_default_change_reflected_without_override(self):
        user = make_user()
        platform_settings_service.update_settings(sla_amber_threshold_hours=10)

        amber, _red = sla_threshold_service.get_effective_thresholds(user=user)

        self.assertEqual(amber, 10)
