# Generated by Tses 2026-07-09T12:37:38Z
from django.core import mail
from django.test import TestCase
from rest_framework import status
from rest_framework.test import APITestCase

from api.authentication.tests.factories import make_user
from api.notification.models import Notification, NotificationPreference
from api.notification.services import notification_preference_service
from api.users.models import UserActivityLog


class EmitEmailNotificationTests(TestCase):
    def test_sends_email_via_configured_templates(self):
        sent_count = Notification.emit_email_notification(
            receivers=["someone@example.com"],
            subject="Test Subject",
            template_name="emails/email_verification",
            context={
                "first_name": "Ada",
                "verification_link": "http://localhost:3000/verify-email?token=abc123",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(sent_count, 1)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("someone@example.com", mail.outbox[0].to)
        self.assertEqual(mail.outbox[0].subject, "Test Subject")
        self.assertIn(
            "http://localhost:3000/verify-email?token=abc123", mail.outbox[0].body
        )

    def test_resolves_user_instance_receiver_to_email(self):
        from api.authentication.tests.factories import make_user

        user = make_user(email="resolveme@example.com")

        Notification.emit_email_notification(
            receivers=[user],
            subject="Hello",
            template_name="emails/email_verification",
            context={
                "first_name": user.first_name,
                "verification_link": "http://localhost:3000/verify-email?token=xyz789",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("resolveme@example.com", mail.outbox[0].to)

    def test_raises_when_no_receivers(self):
        from rest_framework.exceptions import ValidationError

        with self.assertRaises(ValidationError):
            Notification.emit_email_notification(
                receivers=[], subject="X", template_name="emails/email_verification"
            )


class NotificationPreferenceServiceTests(TestCase):
    def test_get_or_create_returns_same_row_with_defaults_all_true(self):
        user = make_user()

        first = notification_preference_service.get_or_create_preference(user=user)
        second = notification_preference_service.get_or_create_preference(user=user)

        self.assertEqual(first.id, second.id)
        self.assertTrue(first.new_course_assigned)
        self.assertTrue(first.sla_breached)
        self.assertEqual(NotificationPreference.objects.filter(user=user).count(), 1)

    def test_update_only_touches_provided_fields(self):
        user = make_user()

        notification_preference_service.update_preference(
            user=user, new_course_assigned=False
        )
        result = notification_preference_service.get_or_create_preference(user=user)

        self.assertFalse(result.new_course_assigned)
        self.assertTrue(result.sla_breached)


class NotificationPreferenceApiTests(APITestCase):
    def test_requires_authentication(self):
        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_get_lazily_creates_defaults(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertTrue(response.data["new_course_assigned"])
        self.assertTrue(response.data["sla_breached"])

    def test_patch_toggles_one_preference(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_breached": False},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertFalse(response.data["sla_breached"])
        self.assertTrue(response.data["new_course_assigned"])

    def test_admin_facing_fields_default_true_and_round_trip(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.get("/api/v1/users/me/notification-preferences/")
        self.assertTrue(response.data["kyc_submission_alert"])
        self.assertTrue(response.data["account_deletion_detection_alert"])
        self.assertTrue(response.data["mie_recommendation_alert"])
        self.assertTrue(response.data["mie_pipeline_alert"])

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"kyc_submission_alert": False},
            format="json",
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertFalse(response.data["kyc_submission_alert"])

    def test_patch_empty_body_rejected(self):
        user = make_user()
        self.client.force_authenticate(user)

        response = self.client.patch(
            "/api/v1/users/me/notification-preferences/", {}, format="json"
        )
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_patch_logs_configuration_activity(self):
        user = make_user()
        self.client.force_authenticate(user)

        self.client.patch(
            "/api/v1/users/me/notification-preferences/",
            {"sla_breached": False},
            format="json",
        )

        self.assertTrue(
            UserActivityLog.objects.filter(
                user=user, action="NOTIFICATION_PREFERENCES_UPDATED"
            ).exists()
        )
