# Generated by Tses 2026-07-09T12:37:38Z
from django.core import mail
from django.test import TestCase

from api.notification.models import Notification


class EmitEmailNotificationTests(TestCase):
    def test_sends_email_via_configured_templates(self):
        sent_count = Notification.emit_email_notification(
            receivers=["someone@example.com"],
            subject="Test Subject",
            template_name="emails/email_verification",
            context={
                "first_name": "Ada",
                "verification_link": "http://localhost:3000/verify-email?token=abc123",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(sent_count, 1)
        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("someone@example.com", mail.outbox[0].to)
        self.assertEqual(mail.outbox[0].subject, "Test Subject")
        self.assertIn(
            "http://localhost:3000/verify-email?token=abc123", mail.outbox[0].body
        )

    def test_resolves_user_instance_receiver_to_email(self):
        from api.authentication.tests.factories import make_user

        user = make_user(email="resolveme@example.com")

        Notification.emit_email_notification(
            receivers=[user],
            subject="Hello",
            template_name="emails/email_verification",
            context={
                "first_name": user.first_name,
                "verification_link": "http://localhost:3000/verify-email?token=xyz789",
                "expiry_minutes": 10,
            },
        )

        self.assertEqual(len(mail.outbox), 1)
        self.assertIn("resolveme@example.com", mail.outbox[0].to)

    def test_raises_when_no_receivers(self):
        from rest_framework.exceptions import ValidationError

        with self.assertRaises(ValidationError):
            Notification.emit_email_notification(
                receivers=[], subject="X", template_name="emails/email_verification"
            )
