# Generated by Tses 2026-07-09T12:37:38Z
from drf_spectacular.utils import OpenApiResponse, extend_schema
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from api.authentication.services import activity_service
from api.notification.serializers import (
    NotificationPreferenceSerializer,
    NotificationPreferenceUpdateSerializer,
)
from api.notification.services import notification_preference_service
from api.users.enums import UserActivityActionEnums, UserActivityCategoryEnums
from includes.spectacular.responses import STANDARD_ERROR_RESPONSES


class NotificationPreferenceView(APIView):
    """GET/PATCH the current user's notification preferences.

    Lazily creates the row on first GET, same pattern as onboarding's
    OnboardingView and ReviewerAvailabilityView.
    """

    permission_classes = [IsAuthenticated]
    serializer_class = (
        NotificationPreferenceUpdateSerializer  # for schema generation only
    )

    @extend_schema(
        summary="Get notification preferences",
        description=(
            "Returns the current user's notification preferences, "
            "creating a default row on first call.\n\n"
            "**Auth:** Any authenticated user.\n\n"
            "**Prerequisites:** None."
        ),
        tags=["Notifications"],
        responses={
            200: OpenApiResponse(response=NotificationPreferenceSerializer),
            **STANDARD_ERROR_RESPONSES["auth"],
            **STANDARD_ERROR_RESPONSES["server"],
        },
    )
    def get(self, request):
        preference = notification_preference_service.get_or_create_preference(
            user=request.user
        )
        return Response(NotificationPreferenceSerializer(preference).data)

    @extend_schema(
        summary="Update notification preferences",
        description=(
            "Updates one or more of the current user's notification "
            "preferences. All fields are optional so a client can toggle "
            "just one at a time.\n\n"
            "**Auth:** Any authenticated user.\n\n"
            "**Prerequisites:** None."
        ),
        tags=["Notifications"],
        request=NotificationPreferenceUpdateSerializer,
        responses={
            200: OpenApiResponse(response=NotificationPreferenceSerializer),
            **STANDARD_ERROR_RESPONSES["validation"],
            **STANDARD_ERROR_RESPONSES["auth"],
            **STANDARD_ERROR_RESPONSES["server"],
        },
    )
    def patch(self, request):
        serializer = NotificationPreferenceUpdateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        preference = notification_preference_service.update_preference(
            user=request.user, **serializer.validated_data
        )
        activity_service.log_activity(
            user=request.user,
            category=UserActivityCategoryEnums.CONFIGURATION,
            action=UserActivityActionEnums.NOTIFICATION_PREFERENCES_UPDATED,
            summary="Updated notification preferences.",
            request=request,
        )
        return Response(NotificationPreferenceSerializer(preference).data)
