# Generated by Django 5.2.14 on 2026-08-06 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'outbox_events',
                'ordering': ['created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'paystack_webhook_events',
                'ordering': ['created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TransferOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending API Call'), ('PROCESSING', 'API Call In Progress'), ('SUBMITTED', 'Sent to Paystack'), ('FAILED', 'Failed Locally')], default='PENDING', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('wallet_id', models.UUIDField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'transfer_outbox_events',
                'ordering': ['created_datetime'],
            },
        ),
    ]
