# Generated by Django 5.2.14 on 2026-08-07 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wallet', '0005_alter_withdrawalrequest_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferoutboxevent',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_outbox_events', to='wallet.withdrawalrequest'),
        ),
    ]
