# Generated by Django 5.2.14 on 2026-08-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferoutboxevent_transfer_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OutboxEvent',
            new_name='SISSLOutboxEvent',
        ),
    ]
