# Generated by Django 5.2.14 on 2026-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transferoutboxevent_transfer_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferoutboxevent',
            old_name='paystack_transfer_code',
            new_name='transfer_code',
        ),
        migrations.AddField(
            model_name='transferoutboxevent',
            name='transfer_processor',
            field=models.CharField(blank=True, choices=[('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack')], max_length=20, null=True),
        ),
    ]
