# Generated by Django 5.2.14 on 2026-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_outboxevent_sissloutboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sissloutboxevent',
            name='event_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_ID', "Voter's ID"), ('BVN', 'Bank Verification Number (BVN)'), ('LIVENESS', 'Liveness Verification')], max_length=255),
        ),
        migrations.AlterModelTable(
            name='sissloutboxevent',
            table='sissl_outbox_events',
        ),
    ]
