# Generated by Django 5.2.14 on 2026-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_paystack_transfer_code_transferoutboxevent_transfer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferoutboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending API Call'), ('PROCESSING', 'API Call In Progress'), ('SUBMITTED', 'Sent to Processor'), ('FAILED', 'Failed Locally')], default='PENDING', max_length=20),
        ),
    ]
