# Generated by Django 5.2.14 on 2026-08-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sissloutboxevent_event_type_and_more'),
        ('users', '0022_alter_kycverification_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sissloutboxevent',
            name='kyc_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sissl_outbox_events', to='users.kycverification'),
        ),
    ]
