# Generated by Django 5.2.14 on 2026-08-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transferoutboxevent_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaystackWebhookEvent',
            new_name='WebhookEvent',
        ),
    ]
