# Generated by Django 5.2.14 on 2026-08-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_paystackwebhookevent_webhookevent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webhookevent',
            table='webhook_events',
        ),
    ]
