# Generated by Django 5.2.14 on 2026-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_webhookevent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack')], default='FLUTTERWAVE', max_length=200),
        ),
    ]
