# Generated by Django 5.2.14 on 2026-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_webhookevent_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferoutboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending API Call'), ('PROCESSING', 'API Call In Progress'), ('SUBMITTED', 'Sent to Processor'), ('FAILED', 'Failed Locally'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20),
        ),
    ]
