# Generated by Django 5.2.14 on 2026-08-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sissloutboxevent_kyc_request'),
        ('core', '0008_alter_transferoutboxevent_status'),
    ]

    operations = [
    ]
