# Generated by Django 5.2.14 on 2026-08-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260826_1802'),
        ('users', '0022_alter_kycverification_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sissloutboxevent',
            name='kyc_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sissl_outbox_event', to='users.kycverification'),
        ),
    ]
