# Generated by Django 5.2.14 on 2026-09-01 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sissloutboxevent_kyc_request'),
        ('users', '0023_kycverification_sissl_request_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('event_type', models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_ID', "Voter's ID"), ('BVN', 'Bank Verification Number (BVN)'), ('LIVENESS', 'Liveness Verification')], max_length=255)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('kyc_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_outbox_event', to='users.kycverification')),
            ],
            options={
                'db_table': 'kyc_outbox_events',
                'ordering': ['created_datetime'],
            },
        ),
        migrations.DeleteModel(
            name='SISSLOutboxEvent',
        ),
    ]
