# Generated by Django 5.2.14 on 2026-09-04 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kycoutboxevent_delete_sissloutboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouverifyWebhookOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('kyc_request_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Background task processing'), ('PROCESSING', 'Currently being processed'), ('FAILED', 'Failed Locally'), ('PROCESSED', 'Processed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'youverify_webhook_events',
                'ordering': ['created_datetime'],
            },
        ),
    ]
