# Generated by Django 5.2.14 on 2026-09-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_youverifywebhookoutboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='youverifywebhookoutboxevent',
            name='event_type',
            field=models.CharField(default='', help_text="Type of the YouVerify webhook event, such as 'identity.completed'", max_length=255),
            preserve_default=False,
        ),
    ]
