# Generated by Django 5.2.14 on 2026-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_youverifywebhookoutboxevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferoutboxevent',
            name='transfer_processor',
            field=models.CharField(blank=True, choices=[('FLUTTERWAVE', 'Flutterwave')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave')], default='FLUTTERWAVE', max_length=200),
        ),
    ]
