# Generated by Django 5.2.14 on 2026-09-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transferoutboxevent_transfer_processor_and_more'),
        ('payments', '0011_alter_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferoutboxevent',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transferoutboxevent',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
