# Generated by Django 5.2.14 on 2026-08-20 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Canonical version label, e.g. '1.0'.",
                        max_length=10,
                        unique=True,
                        verbose_name="Label",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether new course publications may use this version label. Set to False to freeze an old version.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Version",
                "verbose_name_plural": "Course Versions",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Course title.", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Course description including target audience, prerequisites, and outcomes.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("IN_REVIEW", "In Review"),
                            ("NEEDS_REVISION", "Needs Revision"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        help_text="Current lifecycle status of the course.",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "creator_price_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Category creator_price captured at submission time. Null until submitted.",
                        max_digits=10,
                        null=True,
                        verbose_name="Creator Price Snapshot",
                    ),
                ),
                (
                    "preview_video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="1-2 minute course overview video URL, required before submission (BR-015).",
                        verbose_name="Preview Video URL",
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Course thumbnail image URL, distinct from preview_video_url's cover video.",
                        verbose_name="Thumbnail URL",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        default="",
                        help_text="Self-reported difficulty level for this course.",
                        max_length=15,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Course-level list of measurable learning objective strings.",
                        verbose_name="Learning Objectives",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-text tags for search/discovery.",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "planned_duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Creator-declared course duration (entered as H/M/S), distinct from duration_estimate_minutes which is computed from actual lessons.",
                        verbose_name="Planned Duration (seconds)",
                    ),
                ),
                (
                    "duration_estimate_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Computed sum of Lesson.duration_minutes across the course, kept in sync by course_service.recalculate_duration_estimate.",
                        verbose_name="Duration Estimate (minutes)",
                    ),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        help_text="When the creator accepted the category Terms and Conditions (BR-005).",
                        verbose_name="Terms Accepted At",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Published At"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rejected At"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this course belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Course Creator who owns this course.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Topic this course belongs to, nested under category. Optional for backward compatibility with category-only courses; when set, its price is used instead of the category's at submission time.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="catalog.topic",
                        verbose_name="Topic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Canonical CourseVersion label this course publishes under (SCCS PRD Section 15). Set at publish time; a PublishedCourseSnapshot records the course tree at that label.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="courses",
                        to="courses.courseversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Module title.", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Display order of this module within the course.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "lock_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current edit lock auto-expires.",
                        null=True,
                        verbose_name="Lock Expires At",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this module belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User currently holding the edit lock on this module, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Locked By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Lesson title.", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Display order of this lesson within the module.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "script",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Lesson narration/content script, 500-1500 words (SCCS PRD Section 6.2).",
                        verbose_name="Script",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional lesson video link, same pattern as Course.preview_video_url.",
                        verbose_name="Video URL",
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of measurable learning objective strings, 2-5 per lesson.",
                        verbose_name="Learning Objectives",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Estimated lesson duration in minutes.",
                        verbose_name="Duration Minutes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="Module this lesson belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LESSON", "Lesson"),
                            ("MODULE", "Module"),
                            ("COURSE", "Course"),
                        ],
                        help_text="Which entity level this assessment is attached to.",
                        max_length=10,
                        verbose_name="Level",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Assessment title.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text="List of multiple-choice question objects.",
                        verbose_name="Questions",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_assessment",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "module",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="courses.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.CreateModel(
            name="PublishedCourseSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        help_text="When this version was published.",
                        verbose_name="Published At",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Course/module/lesson tree as it existed at publish time.",
                        verbose_name="Snapshot",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this version snapshot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        help_text="CourseVersion lookup record this snapshot is published under.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_snapshots",
                        to="courses.courseversion",
                        verbose_name="Version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Published Course Snapshot",
                "verbose_name_plural": "Published Course Snapshots",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")],
                        help_text="The decision made by the reviewer.",
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured reviewer feedback.",
                        verbose_name="Feedback",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this review action was taken on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_actions",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="Reviewer who took this action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Action",
                "verbose_name_plural": "Review Actions",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CourseAppeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email supplied on the appeal form.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "web_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional supporting link.",
                        verbose_name="Web Link",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Whether this appeal is pending, approved, or rejected.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Reviewer's reasoning for the decision.",
                        verbose_name="Decision Notes",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The rejected course this appeal disputes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Super Admin who decided this appeal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Course Creator who filed this appeal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_appeals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Appeal",
                "verbose_name_plural": "Course Appeals",
                "ordering": ["-created_datetime"],
                "indexes": [
                    models.Index(fields=["status"], name="course_appeal_status_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "submitted_at"], name="course_status_submitted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["creator", "status"], name="course_creator_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "order"], name="module_course_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="unique_module_order_per_course"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["module", "order"], name="lesson_module_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("module", "order"), name="unique_lesson_order_per_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", True),
                        ("lesson__isnull", False),
                        ("module__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("lesson__isnull", True),
                        ("module__isnull", False),
                    ),
                    models.Q(
                        ("course__isnull", False),
                        ("lesson__isnull", True),
                        ("module__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="assessment_exactly_one_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewaction",
            index=models.Index(
                fields=["course", "-created_datetime"],
                name="reviewaction_course_dt_idx",
            ),
        ),
    ]
