# Generated by Django 5.2.14 on 2026-07-15 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='', help_text='Self-reported difficulty level for this course.', max_length=15, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Course-level list of measurable learning objective strings.', verbose_name='Learning Objectives'),
        ),
        migrations.AddField(
            model_name='course',
            name='planned_duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Creator-declared course duration (entered as H/M/S), distinct from duration_estimate_minutes which is computed from actual lessons.', verbose_name='Planned Duration (seconds)'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Free-text tags for search/discovery.', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', help_text="Course thumbnail image URL, distinct from preview_video_url's cover video.", verbose_name='Thumbnail URL'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('name', models.CharField(help_text='Topic display name.', max_length=150, verbose_name='Name')),
                ('creator_price', models.DecimalField(decimal_places=2, help_text='Fixed price paid to a creator for an approved course in this topic.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Creator Price')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', help_text='Whether the topic currently accepts new course submissions.', max_length=10, verbose_name='Status')),
                ('category', models.ForeignKey(help_text='Category this topic belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.category', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(blank=True, help_text="Topic this course belongs to, nested under category. Optional for backward compatibility with category-only courses; when set, its price is used instead of the category's at submission time.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.topic', verbose_name='Topic'),
        ),
        migrations.CreateModel(
            name='CategoryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('name', models.CharField(help_text='Requested category name.', max_length=150, verbose_name='Name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Whether this request is pending, approved, or rejected.', max_length=10, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('requested_by', models.ForeignKey(help_text='Creator who requested this category.', on_delete=django.db.models.deletion.CASCADE, related_name='category_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('resulting_category', models.ForeignKey(blank=True, help_text='The Category created when this request was approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.category', verbose_name='Resulting Category')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Category Request',
                'verbose_name_plural': 'Category Requests',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['status'], name='category_request_status_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category', 'status'], name='topic_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_topic_name_per_category'),
        ),
    ]
