# Generated by Django 5.2.14 on 2026-08-22 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_delete_reviewaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="quality_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Overall quality score 0-100, rendered as the % bar in the course table. Null until the course has been quality-checked.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Quality Score",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CREATOR_UPLOADED", "Creator Uploaded"),
                    ("AI_GENERATED", "AI Generated"),
                    ("DEVELOPER_API", "Developer API"),
                ],
                default="CREATOR_UPLOADED",
                help_text="Where this course's content originated - the Type badge shown on course details.",
                max_length=20,
                verbose_name="Source Type",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[("VIDEO", "Video"), ("QUIZ", "Quiz"), ("TEXT", "Text")],
                default="TEXT",
                help_text="The lesson's primary media format - matches the three 'Add lesson' buttons (Video, Quiz, Text) in the builder.",
                max_length=10,
                verbose_name="Content Type",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="embedded_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Pasted embed link for external players (Vimeo, YouTube, Wistia, Typeform, etc.) from the 'Add Media' block.",
                verbose_name="Embedded Link",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_script_file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Uploaded subtitle/transcript file path (.srt) for the lesson video.",
                max_length=500,
                verbose_name="Video Script File",
            ),
        ),
    ]
