# Generated by Django 5.2.14 on 2026-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_move_category_to_categories_app"),
        ("courses", "0003_coursecollaborator"),
    ]

    operations = []
