# Generated by Django 5.2.14 on 2026-08-22 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_quality_score_course_source_type_and_more"),
        ("quizzes", "0002_quiz_created_by_quiz_updated_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Module summary, filled in at the 'Course Modules' step after the outline is set.",
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="learning_objectives",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Module-level learning objective strings - what the learner gains from this module as a whole, distinct from the per-lesson objectives.",
                verbose_name="Learning Objectives",
            ),
        ),
        migrations.CreateModel(
            name="CourseThumbnail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")],
                        default="IMAGE",
                        help_text="Whether the thumbnail is a still image or a short video.",
                        max_length=10,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Upload"),
                            ("GOOGLE_DRIVE", "Google Drive"),
                            ("YOUTUBE", "YouTube"),
                            ("DROPBOX", "Dropbox"),
                            ("LINK", "Link"),
                        ],
                        default="UPLOAD",
                        help_text="Where the thumbnail came from - the 'Add Media' modal's options.",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Uploaded file path; populated only when source is UPLOAD.",
                        max_length=500,
                        verbose_name="File",
                    ),
                ),
                (
                    "external_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External URL (Google Drive, YouTube, Dropbox, pasted link); populated only when source is not UPLOAD.",
                        max_length=1000,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Source media width in pixels, when known.",
                        null=True,
                        verbose_name="Width",
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Source media height in pixels, when known.",
                        null=True,
                        verbose_name="Height",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one thumbnail per course is active at a time.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this thumbnail belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Thumbnail",
                "verbose_name_plural": "Course Thumbnails",
                "ordering": ["-is_active", "-created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["course", "is_active"], name="thumb_course_active_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("course",),
                        name="one_active_thumbnail_per_course",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("file__gt", ""), ("source", "UPLOAD")),
                            models.Q(
                                models.Q(("source", "UPLOAD"), _negated=True),
                                ("external_url__gt", ""),
                            ),
                            _connector="OR",
                        ),
                        name="thumbnail_has_file_xor_external_url",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonContentBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Block's position within the lesson body.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("HEADING_1", "Heading 1"),
                            ("HEADING_2", "Heading 2"),
                            ("PARAGRAPH", "Paragraph"),
                            ("NUMBERED_LIST", "Numbered List"),
                            ("BULLETED_LIST", "Bulleted List"),
                            ("BLOCKQUOTE", "Blockquote"),
                            ("DIVIDER", "Divider"),
                            ("IMAGE", "Image"),
                            ("VIDEO", "Video"),
                            ("EMBED", "Embed"),
                            ("QUIZ", "Quiz"),
                        ],
                        help_text="What kind of content this block holds.",
                        max_length=20,
                        verbose_name="Block Type",
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Prose payload for heading/paragraph/list/blockquote blocks.",
                        verbose_name="Text Content",
                    ),
                ),
                (
                    "media_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Media payload for image/video/embed blocks - uploaded path or external URL.",
                        max_length=500,
                        verbose_name="Media URL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson this block belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        help_text="The quiz this 'quiz' block embeds - only meaningful when block_type is QUIZ.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_blocks",
                        to="quizzes.quiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Content Block",
                "verbose_name_plural": "Lesson Content Blocks",
                "ordering": ["order", "created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "order"], name="block_lesson_order_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "order"), name="unique_block_order_per_lesson"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("block_type", "QUIZ")),
                            models.Q(("quiz__isnull", True)),
                            _negated=True,
                        ),
                        name="quiz_block_requires_quiz",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        help_text="Uploaded image file path, or the external URL for non-upload sources.",
                        max_length=500,
                        verbose_name="Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional caption shown under the image.",
                        max_length=255,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "Upload"),
                            ("GOOGLE_DRIVE", "Google Drive"),
                            ("YOUTUBE", "YouTube"),
                            ("DROPBOX", "Dropbox"),
                            ("LINK", "Link"),
                        ],
                        default="UPLOAD",
                        help_text="Where this image came from - the 'Add Media' modal's options.",
                        max_length=20,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order among the lesson's images.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson this image belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Image",
                "verbose_name_plural": "Lesson Images",
                "ordering": ["order", "created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "order"], name="lesson_image_order_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The requirement, e.g. 'Basic Python syntax knowledge'.",
                        max_length=500,
                        verbose_name="Text",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order among the lesson's requirements.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        help_text="Lesson this requirement belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Requirement",
                "verbose_name_plural": "Lesson Requirements",
                "ordering": ["order", "created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "order"], name="lesson_req_order_idx"
                    )
                ],
            },
        ),
    ]
