# Generated by Django 5.2.14 on 2026-07-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_rename_category_table"),
        ("courses", "0004_merge_20260720_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryrequest",
            name="resulting_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The Category created when this request was approved.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="categories.category",
                verbose_name="Resulting Category",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="category",
            field=models.ForeignKey(
                help_text="Category this topic belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="categories.category",
                verbose_name="Category",
            ),
        ),
    ]
