# Generated by Django 5.2.14 on 2026-08-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_module_description_module_learning_objectives_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("NEEDS_REVISION", "Needs Revision"),
                    ("QA_VERIFICATION", "QA Verification"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                help_text="Current lifecycle status of the course.",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
