# Generated by Django 5.2.14 on 2026-07-23 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_categoryrequest_resulting_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='Creator this topic is currently reserved for (PRD BR-007), if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reserved By'),
        ),
        migrations.AddField(
            model_name='topic',
            name='reserved_until',
            field=models.DateField(blank=True, help_text='Date the current reservation expires.', null=True, verbose_name='Reserved Until'),
        ),
        migrations.CreateModel(
            name='TopicReservationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Whether this request is pending, approved, or rejected.', max_length=10, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('requested_by', models.ForeignKey(help_text='Creator who requested this reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='topic_reservation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/Reviewer who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('topic', models.ForeignKey(help_text='Topic requested to be reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='courses.topic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Topic Reservation Request',
                'verbose_name_plural': 'Topic Reservation Requests',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['status'], name='topic_reservation_status_idx')],
            },
        ),
    ]
