# Generated by Django 5.2 on 2026-08-24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("courses", "0006_alter_course_status")]

    operations = [
        migrations.CreateModel(
            name="CourseDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SOLUDESK", "SoluDesk"),
                            ("UDEMY", "Udemy"),
                            ("COURSERA", "Coursera"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "learner_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "mie_suggested_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("PROMOTIONAL", "Promotional"),
                            ("B2B_ONLY", "B2B only"),
                        ],
                        default="ONE_TIME",
                        max_length=15,
                    ),
                ),
                (
                    "approval_rate",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "marketplace_fee_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "platform_revenue_per_enrollment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("mie_rationale", models.TextField(blank=True, default="")),
                ("comparable_courses", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUEUED", "Queued"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "external_course_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_channels",
                        to="courses.course",
                    ),
                ),
            ],
            options={"ordering": ["channel"]},
        ),
        migrations.AddConstraint(
            model_name="coursedistribution",
            constraint=models.UniqueConstraint(
                fields=("course", "channel"), name="unique_course_distribution_channel"
            ),
        ),
        migrations.AddIndex(
            model_name="coursedistribution",
            index=models.Index(
                fields=["channel", "status"], name="distribution_channel_status_ix"
            ),
        ),
    ]
