# Generated by Django 5.2 on 2026-09-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_coursedistribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FULL_COURSE", "Full course"),
                            ("ASSIST", "AI assist"),
                            ("THUMBNAIL", "Thumbnail"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("STRUCTURE_READY", "Structure ready"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=24,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=64)),
                ("request_payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("provider", models.CharField(blank=True, default="", max_length=40)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("cancel_requested", models.BooleanField(default=False)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generation_jobs",
                        to="courses.course",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_datetime"]},
        ),
        migrations.CreateModel(
            name="AIGenerationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="courses.aigenerationjob",
                    ),
                ),
            ],
            options={"ordering": ["order", "created_datetime"]},
        ),
        migrations.AddConstraint(
            model_name="aigenerationjob",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("idempotency_key", "")),
                fields=("creator", "idempotency_key"),
                name="unique_ai_generation_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="aigenerationitem",
            constraint=models.UniqueConstraint(
                fields=("job", "key"), name="unique_ai_generation_item_key"
            ),
        ),
        migrations.AlterField(
            model_name="coursethumbnail",
            name="source",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Upload"),
                    ("GOOGLE_DRIVE", "Google Drive"),
                    ("YOUTUBE", "YouTube"),
                    ("DROPBOX", "Dropbox"),
                    ("LINK", "Link"),
                    ("AI_GENERATED", "AI Generated"),
                ],
                default="UPLOAD",
                help_text="Where the thumbnail came from - the 'Add Media' modal's options.",
                max_length=20,
                verbose_name="Source",
            ),
        ),
        migrations.AlterField(
            model_name="lessonimage",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Upload"),
                    ("GOOGLE_DRIVE", "Google Drive"),
                    ("YOUTUBE", "YouTube"),
                    ("DROPBOX", "Dropbox"),
                    ("LINK", "Link"),
                    ("AI_GENERATED", "AI Generated"),
                ],
                default="UPLOAD",
                help_text="Where this image came from - the 'Add Media' modal's options.",
                max_length=20,
                verbose_name="Source Type",
            ),
        ),
    ]
