# Generated by Django 5.2.14 on 2026-08-04 13:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_rework_topic_reservation_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration_estimate_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Computed sum of Lesson.duration_minutes across the course, kept in sync by course_service.recalculate_duration_estimate.",
                verbose_name="Duration Estimate (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="version",
            field=models.CharField(
                default="1.0",
                help_text="Course version number (SCCS PRD Section 15). A CourseVersion snapshot is recorded at this value when the course is published.",
                max_length=10,
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional lesson video link, same pattern as Course.preview_video_url.",
                verbose_name="Video URL",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="lock_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current edit lock auto-expires.",
                null=True,
                verbose_name="Lock Expires At",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User currently holding the edit lock on this module, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Locked By",
            ),
        ),
        migrations.CreateModel(
            name="CourseVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="Semantic version at publish time, e.g. '1.0'.",
                        max_length=10,
                        verbose_name="Version Number",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        help_text="When this version was published.",
                        verbose_name="Published At",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Course/module/lesson tree as it existed at publish time.",
                        verbose_name="Snapshot",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this version snapshot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Version",
                "verbose_name_plural": "Course Versions",
                "ordering": ["-published_at"],
            },
        ),
    ]
