# Generated by Django 5.2.14 on 2026-08-06 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_duration_estimate_minutes_course_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('email', models.EmailField(help_text='Contact email supplied on the appeal form.', max_length=254, verbose_name='Email')),
                ('web_link', models.URLField(blank=True, help_text='Optional supporting link.', verbose_name='Web Link')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Whether this appeal is pending, approved, or rejected.', max_length=10, verbose_name='Status')),
                ('decision_notes', models.TextField(blank=True, help_text="Reviewer's reasoning for the decision.", verbose_name='Decision Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('course', models.ForeignKey(help_text='The rejected course this appeal disputes.', on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='courses.course', verbose_name='Course')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/Super Admin who decided this appeal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('submitted_by', models.ForeignKey(help_text='Course Creator who filed this appeal.', on_delete=django.db.models.deletion.CASCADE, related_name='course_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Course Appeal',
                'verbose_name_plural': 'Course Appeals',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['status'], name='course_appeal_status_idx')],
            },
        ),
    ]
