# Generated by Django 5.2.14 on 2026-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_aigenerationitem_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrequirement",
            name="text",
            field=models.CharField(
                help_text="The requirement, e.g. 'Basic Python syntax knowledge'. Limited to 2000 characters.",
                max_length=2000,
                verbose_name="Text",
            ),
        ),
    ]
