# Generated by Django 5.2.14 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_raise_lesson_requirement_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="1-2 minute course overview video URL, required before submission (BR-015).",
                max_length=2000,
                verbose_name="Preview Video URL",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Course thumbnail image URL, distinct from preview_video_url's cover video.",
                max_length=2000,
                verbose_name="Thumbnail URL",
            ),
        ),
        migrations.AlterField(
            model_name="coursethumbnail",
            name="external_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External URL (Google Drive, YouTube, Dropbox, pasted link); populated only when source is not UPLOAD.",
                max_length=2000,
                verbose_name="External URL",
            ),
        ),
        migrations.AlterField(
            model_name="coursethumbnail",
            name="file",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Uploaded file path; populated only when source is UPLOAD.",
                max_length=2000,
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="embedded_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Pasted embed link for external players (Vimeo, YouTube, Wistia, Typeform, etc.) from the 'Add Media' block.",
                max_length=2000,
                verbose_name="Embedded Link",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional lesson video link, same pattern as Course.preview_video_url.",
                max_length=2000,
                verbose_name="Video URL",
            ),
        ),
        migrations.AlterField(
            model_name="lessoncontentblock",
            name="media_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Media payload for image/video/embed blocks - uploaded path or external URL.",
                max_length=2000,
                verbose_name="Media URL",
            ),
        ),
        migrations.AlterField(
            model_name="lessonimage",
            name="image",
            field=models.CharField(
                help_text="Uploaded image file path, or the external URL for non-upload sources.",
                max_length=2000,
                verbose_name="Image",
            ),
        ),
    ]
