# Generated by Codex on 2026-09-14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_topic_status"),
        ("courses", "0011_raise_course_media_url_lengths"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("CREATOR_UPLOADED", "Creator Uploaded"),
                    ("AI_GENERATED", "AI Generated"),
                    ("DOCUMENT_IMPORTED", "Document Imported"),
                    ("DEVELOPER_API", "Developer API"),
                ],
                default="CREATOR_UPLOADED",
                help_text=(
                    "Where this course's content originated - the Type badge shown "
                    "on course details."
                ),
                max_length=20,
                verbose_name="Source Type",
            ),
        ),
        migrations.CreateModel(
            name="CourseImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PARSING", "Parsing"),
                            ("MAPPING", "Mapping"),
                            ("READY_FOR_REVIEW", "Ready for Review"),
                            ("CONFIRMING", "Confirming"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        help_text="Current processing state of this import job.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Approximate completion percentage, from 0 to 100.",
                        verbose_name="Progress",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable processing stage for the frontend.",
                        max_length=80,
                        verbose_name="Stage",
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        help_text="Durable private object-storage key returned by upload presign.",
                        max_length=500,
                        verbose_name="File Key",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        help_text="Original uploaded document filename.",
                        max_length=255,
                        verbose_name="Filename",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Uploaded document MIME type.",
                        max_length=120,
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        help_text="Uploaded document size in bytes.",
                        verbose_name="Size",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Course title captured at import start.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional course description captured at import start.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "detected_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detected course/module/lesson tree awaiting creator review.",
                        verbose_name="Detected Structure",
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Non-blocking parser warnings to show in the review UI.",
                        verbose_name="Warnings",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Terminal parser or confirmation error, if any.",
                        verbose_name="Error Message",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client-generated retry key; unique per creator when supplied.",
                        max_length=255,
                        verbose_name="Idempotency Key",
                    ),
                ),
                (
                    "cancel_requested",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the creator asked to cancel this job.",
                        verbose_name="Cancel Requested",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Started At")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Completed At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category selected for the eventual imported course.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_import_jobs",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Draft course created when this import is confirmed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_import_jobs",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="Creator who owns this import job.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional topic selected for the eventual imported course.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="course_import_jobs",
                        to="catalog.topic",
                        verbose_name="Topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Import Job",
                "verbose_name_plural": "Course Import Jobs",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.AddIndex(
            model_name="courseimportjob",
            index=models.Index(
                fields=["creator", "status"],
                name="courseimp_creator_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseimportjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("creator", "idempotency_key"),
                name="unique_course_import_idempotency_key",
            ),
        ),
    ]
