# Generated by Django 5.2.14 on 2026-09-14 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_categoryrequest_description'),
        ('courses', '0012_course_import_job_document_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review_stage',
            field=models.CharField(blank=True, choices=[('CONTENT', 'First Review'), ('SECOND_REVIEW', 'Second Review'), ('VERIFICATION', 'Verification'), ('QA', 'QA Verification')], default='', help_text='Content review seat the course is waiting at (Submitted) or held in (In Review). Blank outside content review - QA verification is tracked by status alone.', max_length=20, verbose_name='Review Stage'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'review_stage', 'submitted_at'], name='course_status_stage_sub_idx'),
        ),
    ]
