# Generated by Django 5.2.14 on 2026-09-18 05:01

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_draft_started_at(apps, schema_editor):
    """Age existing courses from their creation date, not this deploy.

    The field defaults to now(), so without this every course already on the
    platform would look freshly drafted and its creator would be locked out
    of submitting for the whole of draft_minimum_hold_hours.
    """

    apps.get_model("courses", "Course").objects.update(
        draft_started_at=F("created_datetime")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_aigenerationjob_recovery_telemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='draft_started_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this course first existed as a draft, for the minimum hold time. A rejection returns a course to Draft but does not reset this, so revisions can be resubmitted without waiting again.', null=True, verbose_name='Draft Started At'),
        ),
        migrations.AddField(
            model_name='course',
            name='flag_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Flag Reason'),
        ),
        migrations.AddField(
            model_name='course',
            name='flagged_at',
            field=models.DateTimeField(blank=True, help_text='When this course was auto-flagged for sitting too long without a review decision. Advisory only - it blocks nothing.', null=True, verbose_name='Flagged At'),
        ),
        migrations.AddField(
            model_name='course',
            name='sla_red_alerted_at',
            field=models.DateTimeField(blank=True, help_text='When admins were alerted that this course breached the review SLA. Set once per review cycle so the sweep cannot re-alert.', null=True, verbose_name='SLA Red Alerted At'),
        ),
        migrations.RunPython(
            backfill_draft_started_at, migrations.RunPython.noop
        ),
    ]
