# Generated by Django 5.2.14 on 2026-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_course_draft_started_at_course_flag_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="revision_seat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTENT", "First Review"),
                    ("SECOND_REVIEW", "Second Review"),
                    ("VERIFICATION", "Verification"),
                    ("QA", "QA Verification"),
                ],
                default="",
                help_text="The review seat that sent this course back for revision. A resubmission resumes at this seat instead of restarting the chain. Set only while the course is Needs Revision (staged review flow).",
                max_length=20,
                verbose_name="Revision Seat",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_attached_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the video was submitted for review (staged review flow). Null while the course is still text only: before this is set the course may carry no video, after it the video is required.",
                null=True,
                verbose_name="Video Attached At",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATOR", "Course Creator"),
                    ("PRODUCTION_ENGINE", "Production Engine"),
                    ("DEVELOPER", "Developer"),
                ],
                default="",
                help_text="Who supplies this course's video after its text passes the first review seat. Decides who may attach the video (staged review flow).",
                max_length=20,
                verbose_name="Video Provider",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview_video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="1-2 minute course overview video URL, required before submission (BR-015). With the staged review flow it is instead refused at submission and required when the video is submitted.",
                max_length=2000,
                verbose_name="Preview Video URL",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("IN_REVIEW", "In Review"),
                    ("NEEDS_REVISION", "Needs Revision"),
                    ("AWAITING_VIDEO", "Awaiting Video"),
                    ("QA_VERIFICATION", "QA Verification"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                help_text="Current lifecycle status of the course.",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
