# Generated by Django 5.2.14 on 2026-10-09 21:03

from django.db import migrations, models
from django.utils.text import slugify


def backfill_published_slugs(apps, schema_editor):
    """Give every already-published course its catalogue slug, the way
    course_service.catalogue_slug does at publish: the title, suffixed
    -2, -3... when taken. Oldest publication first, so it keeps the bare
    slug. Courses that already have one are left alone."""

    Course = apps.get_model("courses", "Course")
    taken = set(Course.objects.exclude(slug__isnull=True).values_list("slug", flat=True))
    courses = list(
        Course.objects.filter(status="PUBLISHED", slug__isnull=True)
        .order_by("published_at", "created_datetime")
        .only("id", "title")
    )
    for course in courses:
        base = slugify(course.title)[:270] or "course"
        slug, suffix = base, 2
        while slug in taken:
            slug = f"{base}-{suffix}"
            suffix += 1
        taken.add(slug)
        course.slug = slug
    Course.objects.bulk_update(courses, ["slug"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_revision_seat_course_video_attached_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public catalogue address, set once when the course is published and never changed, so shared links keep working.', max_length=280, null=True, unique=True, verbose_name='Slug'),
        ),
        # Reversing drops the column, which takes the slugs with it.
        migrations.RunPython(backfill_published_slugs, migrations.RunPython.noop),
    ]
