# Generated by Django 5.2.14 on 2026-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('OTP_REQUESTED', 'OTP_Requested'), ('OTP_VERIFIED', 'OTP_Verified'), ('OTP_FAILED', 'OTP_Failed'), ('OTP_LOCKED', 'OTP_Locked'), ('JOB_OFFER_ACCEPTED', 'Job Offer Accepted'), ('JOB_OFFER_REJECTED', 'Job Offer Rejected')], db_index=True, max_length=32)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
