# Generated by Django 5.2.14 on 2026-09-02 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_coursedistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('name', models.CharField(help_text="Display name, e.g. 'WellSaid Labs'.", max_length=100, unique=True, verbose_name='Name')),
                ('kind', models.CharField(choices=[('VOICE', 'Voice'), ('VIDEO', 'Video'), ('TEXT', 'Text'), ('FALLBACK', 'Fallback')], help_text='What this provider supplies.', max_length=10, verbose_name='Kind')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive providers stop being offered new jobs.', verbose_name='Is Active')),
                ('current_load_percent', models.PositiveSmallIntegerField(blank=True, help_text='Last known utilisation, 0-100. Null when never polled.', null=True, verbose_name='Current Load (%)')),
                ('current_queue_depth', models.PositiveIntegerField(blank=True, help_text='Last known jobs waiting at the provider.', null=True, verbose_name='Current Queue Depth')),
                ('readings_updated_at', models.DateTimeField(blank=True, help_text='When load/queue were last written, so staleness is visible.', null=True, verbose_name='Readings Updated At')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('name', models.CharField(help_text="Display name, e.g. 'API Gateway'.", max_length=100, unique=True, verbose_name='Name')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='NORMAL', help_text='How urgently degradation here needs attention.', max_length=10, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services keep their history but leave the table.', verbose_name='Is Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Row order on the System Health table.', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('learner_reference', models.CharField(help_text='Opaque learner identifier from the originating channel. Not a platform user id - learners do not have accounts here.', max_length=255, verbose_name='Learner Reference')),
                ('channel', models.CharField(blank=True, default='', help_text='Where the enrolment came from, e.g. the marketplace name.', max_length=20, verbose_name='Channel')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ACTIVE', help_text='Whether the learner is active, finished, or dropped out.', max_length=10, verbose_name='Status')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, help_text='Completion 0-100. Averaged for the completion-rate tile.', verbose_name='Progress (%)')),
                ('enrolled_at', models.DateTimeField(help_text='When the learner enrolled.', verbose_name='Enrolled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('course', models.ForeignKey(help_text='Course enrolled on.', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='opsenrol_course_idx'), models.Index(fields=['-enrolled_at'], name='opsenrol_when_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'learner_reference'), name='unique_learner_per_course')],
            },
        ),
        migrations.CreateModel(
            name='ProductionCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('category', models.CharField(choices=[('VOICE', 'Voice Generation'), ('VIDEO', 'Video Generation'), ('TEXT', 'Text Generation'), ('STORAGE', 'Storage'), ('REVIEW', 'Human Review'), ('OTHER', 'Other')], default='OTHER', help_text='What the money was spent on.', max_length=20, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Cost in platform currency. Four decimal places because per-token and per-second provider rates are fractions of a cent, and rounding each row would drift the daily total.', max_digits=12, verbose_name='Amount')),
                ('incurred_at', models.DateTimeField(help_text='When the spend happened. Separate from created_datetime so a late-arriving provider invoice lands on the right day.', verbose_name='Incurred At')),
                ('note', models.CharField(blank=True, default='', help_text="Free-text detail, e.g. the provider's line-item id.", max_length=255, verbose_name='Note')),
                ('course', models.ForeignKey(blank=True, help_text='Course this spend belongs to. Null for platform-wide costs not attributable to one course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_costs', to='courses.course', verbose_name='Course')),
                ('provider', models.ForeignKey(blank=True, help_text='External provider that billed this, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='operations.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Production Cost',
                'verbose_name_plural': 'Production Costs',
                'ordering': ['-incurred_at'],
                'indexes': [models.Index(fields=['-incurred_at'], name='opscost_incurred_idx'), models.Index(fields=['course', '-incurred_at'], name='opscost_course_idx'), models.Index(fields=['category'], name='opscost_category_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('stage', models.CharField(choices=[('TOPIC_INTAKE', 'Topic Intake'), ('CURRICULUM', 'Curriculum'), ('CONTENT_GENERATION', 'Content Generation'), ('ASSESSMENT_BUILDER', 'Assessment Builder'), ('MEDIA_PRODUCTION', 'Media Production'), ('PREVIEW_VIDEO', 'Preview Video'), ('ASSEMBLY_PACKAGING', 'Assembly and Packaging'), ('AUTO_QA', 'Auto-QA')], help_text='Which stage of production this job performs.', max_length=25, verbose_name='Stage')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='QUEUED', help_text='Where the job currently sits.', max_length=10, verbose_name='Status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Delivery attempts made, for the Failed/Retry tile.', verbose_name='Attempts')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished At')),
                ('last_error', models.CharField(blank=True, default='', help_text='Failure detail from the most recent attempt.', max_length=500, verbose_name='Last Error')),
                ('course', models.ForeignKey(help_text='Course being produced.', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_jobs', to='courses.course', verbose_name='Course')),
                ('provider', models.ForeignKey(blank=True, help_text='Provider handling this job, when one is involved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='operations.provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Pipeline Job',
                'verbose_name_plural': 'Pipeline Jobs',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['stage', 'status'], name='opsjob_stage_status_idx'), models.Index(fields=['status', '-created_datetime'], name='opsjob_status_idx'), models.Index(fields=['course', 'stage'], name='opsjob_course_stage_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceHealthSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], help_text='Result of the probe.', max_length=15, verbose_name='Status')),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Round-trip time. Null when the probe never connected.', null=True, verbose_name='Latency (ms)')),
                ('checked_at', models.DateTimeField(help_text='When the probe ran.', verbose_name='Checked At')),
                ('service', models.ForeignKey(help_text='Service this probe was against.', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='operations.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Health Sample',
                'verbose_name_plural': 'Service Health Samples',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service', '-checked_at'], name='opshealth_service_idx'), models.Index(fields=['-checked_at'], name='opshealth_checked_idx')],
            },
        ),
    ]
