# Generated by Django 5.2.14 on 2026-10-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_revision_seat_course_video_attached_at_and_more'),
        ('operations', '0003_seed_celery_ai_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Lesson the step worked on, for per-lesson steps.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_jobs', to='courses.lesson', verbose_name='Lesson'),
        ),
    ]
