# Generated by Django 5.2.14 on 2026-10-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_pipelinejob_lesson'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Production Engine run this step belongs to, when it is one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionrun', verbose_name='Production Run'),
        ),
    ]
