# Generated by Django 5.2.14 on 2026-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_pipelinejob_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='step',
            field=models.CharField(blank=True, default='', help_text='The Production Engine step within the stage, e.g. storyboard, narration, visuals, render, quality_check. Blank for other jobs.', max_length=20, verbose_name='Step'),
        ),
    ]
