# Generated by Django 5.2.14 on 2026-09-16 19:24

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('title', models.CharField(help_text="Badge name shown to staff and creators, e.g. 'Top'.", max_length=80, verbose_name='Title')),
                ('icon', models.CharField(help_text="Icon identifier from the client's badge icon set. Free text so the client owns its icons, as with Category.icon.", max_length=50, verbose_name='Icon')),
                ('color', models.CharField(help_text='Badge colour as a #RRGGBB hex string.', max_length=7, verbose_name='Color')),
                ('criterion', models.CharField(choices=[('COURSES_CREATED', 'Courses created'), ('COURSES_REVIEWED', 'Courses that passed content review'), ('COURSES_APPROVED', 'Courses approved'), ('COURSES_PUBLISHED', 'Courses published')], default='COURSES_CREATED', help_text='What `required_count` counts for each creator.', max_length=30, verbose_name='Criterion')),
                ('required_count', models.PositiveIntegerField(help_text='How many courses meeting the criterion earn this badge.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Required count')),
                ('auto_award', models.BooleanField(default=False, help_text='Award automatically when a creator meets the requirement. Off means staff award it by hand.', verbose_name='Auto award')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['criterion', '-required_count'],
            },
        ),
        migrations.CreateModel(
            name='CreatorBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('source', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CARRIED_OVER', 'Carried over from a deleted badge')], help_text='How the creator came to hold the badge.', max_length=20, verbose_name='Source')),
                ('awarded_at', models.DateTimeField(help_text='When the badge was awarded.', verbose_name='Awarded at')),
                ('awarded_by', models.ForeignKey(blank=True, help_text='Staff member who awarded it by hand; null when automatic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL, verbose_name='Awarded by')),
                ('badge', models.ForeignKey(help_text='The badge awarded.', on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='achievements.badge', verbose_name='Badge')),
                ('creator', models.ForeignKey(help_text='The creator holding the badge.', on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Creator badge',
                'verbose_name_plural': 'Creator badges',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['criterion', 'required_count', 'is_deleted'], name='badge_criterion_count_idx'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), condition=models.Q(('is_deleted', False)), name='badge_unique_live_title'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('criterion', 'required_count'), name='badge_unique_live_criterion_count'),
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.CheckConstraint(condition=models.Q(('required_count__gte', 1)), name='badge_required_count_positive'),
        ),
        migrations.AddIndex(
            model_name='creatorbadge',
            index=models.Index(fields=['creator', 'is_deleted'], name='creator_badge_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorbadge',
            index=models.Index(fields=['badge', 'is_deleted'], name='creator_badge_badge_idx'),
        ),
        migrations.AddConstraint(
            model_name='creatorbadge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('badge', 'creator'), name='creator_badge_unique_live_award'),
        ),
    ]
