# Generated by Django 5.2.14 on 2026-08-23 00:29

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0006_alter_course_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionRejectionReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short reason shown to admins; matched against past rejections.",
                        max_length=255,
                        unique=True,
                        verbose_name="Label",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Longer explanation of when this reason applies.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive reasons stay on historical rows but stop matching.",
                        verbose_name="Is Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Rejection Reason",
                "verbose_name_plural": "Submission Rejection Reasons",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Registration identity. Also the login handle for platform (OTP) access to the developer surfaces.",
                        max_length=254,
                        unique=True,
                        verbose_name="Developer Email",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        help_text="HTTPS endpoint that receives a signed POST for every event against this developer's submissions.",
                        verbose_name="Webhook URL",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        help_text="Where this account sits in its approval lifecycle.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("PAID_PER_SUBMISSION", "Paid Per Submission"),
                            ("BYPASS_PER_SUBMISSION", "Bypass Per Submission"),
                            ("BYPASS_ACCOUNT", "Account Bypass"),
                        ],
                        default="PAID_PER_SUBMISSION",
                        help_text="Payout arrangement for accepted submissions; changeable by a superadmin at any time.",
                        max_length=25,
                        verbose_name="Plan Type",
                    ),
                ),
                (
                    "api_key_prefix",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="First characters of the issued key (scb_live_...). Non-secret; used for DB lookup and masked display in /me.",
                        max_length=16,
                        verbose_name="API Key Prefix",
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="SHA-256 hex digest of the full key. Raw key is never stored.",
                        max_length=64,
                        verbose_name="API Key Hash",
                    ),
                ),
                (
                    "api_key_issued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the current key was generated (at approval or rotation).",
                        null=True,
                        verbose_name="API Key Issued At",
                    ),
                ),
                (
                    "api_key_last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful key authentication.",
                        null=True,
                        verbose_name="API Key Last Used At",
                    ),
                ),
                (
                    "signing_secret",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Shared secret for HMAC-SHA256 signatures on outbound webhooks. Verification-only credential; retrievable via /me.",
                        max_length=64,
                        verbose_name="Signing Secret",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the latest approve/reject/suspend decision was taken.",
                        null=True,
                        verbose_name="Decided At",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Superadmin who last approved this account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mie_developer_accounts_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Account",
                "verbose_name_plural": "Developer Accounts",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CourseSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="The submission body exactly as received - never rewritten.",
                        verbose_name="Endpoint 1 Payload",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title extracted from the payload; the key used by all three dedup checks.",
                        max_length=255,
                        verbose_name="Idea Title",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("DUPLICATE_IN_QUEUE", "Duplicate In Queue"),
                            ("DUPLICATE_EXISTING", "Duplicate Existing"),
                            ("PREVIOUSLY_REJECTED", "Previously Rejected"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_REVIEW",
                        help_text="Current pipeline state; visible in every queue surface.",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_note",
                    models.TextField(
                        blank=True,
                        help_text="Free-text detail accompanying the rejection.",
                        verbose_name="Rejection Note",
                    ),
                ),
                (
                    "demand_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Admin-entered market-demand signal used to prioritise the Recommendations queue.",
                        null=True,
                        verbose_name="Demand Score",
                    ),
                ),
                (
                    "estimated_monthly_earnings",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Admin-entered market-research estimate, in platform currency.",
                        max_digits=12,
                        null=True,
                        verbose_name="Estimated Monthly Earnings",
                    ),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the idea most recently entered the review queue.",
                        null=True,
                        verbose_name="Queued At",
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the latest approve/reject decision was taken.",
                        null=True,
                        verbose_name="Decided At",
                    ),
                ),
                (
                    "payout_bypass",
                    models.BooleanField(
                        default=False,
                        help_text="Per-submission no-payout marker applied by a superadmin when the creator will not be paid for this idea.",
                        verbose_name="Payout Bypass",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Superadmin responsible for the latest decision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mie_submissions_decided",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Decided By",
                    ),
                ),
                (
                    "resulting_course",
                    models.OneToOneField(
                        blank=True,
                        help_text="Course created when this idea was accepted. On reversal the course is flagged/unpublished, never deleted, so re-approval can relink instead of duplicating.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mie_submission",
                        to="courses.course",
                        verbose_name="Resulting Course",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        help_text="External account that submitted this idea.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="mie.developeraccount",
                        verbose_name="Developer",
                    ),
                ),
                (
                    "rejection_reason",
                    models.ForeignKey(
                        blank=True,
                        help_text="Taxonomy reason attached on rejection or dedup short-circuit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="mie.submissionrejectionreason",
                        verbose_name="Rejection Reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Submission",
                "verbose_name_plural": "Course Submissions",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION_QUEUED", "Submission Queued"),
                            (
                                "SUBMISSION_DUPLICATE_IN_QUEUE",
                                "Submission Duplicate In Queue",
                            ),
                            (
                                "SUBMISSION_DUPLICATE_EXISTING",
                                "Submission Duplicate Existing",
                            ),
                            (
                                "SUBMISSION_PREVIOUSLY_REJECTED",
                                "Submission Previously Rejected",
                            ),
                            ("SUBMISSION_APPROVED", "Submission Approved"),
                            ("SUBMISSION_REJECTED", "Submission Rejected"),
                        ],
                        help_text="What happened; maps 1:1 onto SubmissionStatus transitions.",
                        max_length=40,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Exact JSON body delivered (or to be delivered) to the dev.",
                        verbose_name="Payload",
                    ),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 hex digest included as X-MIE-Signature.",
                        max_length=128,
                        verbose_name="HMAC Signature",
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Delivery attempts made so far.",
                        verbose_name="Attempts",
                    ),
                ),
                (
                    "last_response_code",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="HTTP status returned by the developer's endpoint.",
                        null=True,
                        verbose_name="Last Response Code",
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        help_text="Transport or timeout error from the latest attempt.",
                        max_length=500,
                        verbose_name="Last Error",
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest moment the dispatcher may try again.",
                        null=True,
                        verbose_name="Next Retry At",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Submission whose state change this event announces.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="mie.coursesubmission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.AddConstraint(
            model_name="developeraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("api_key_hash", ""),
                    ("status__in", ("APPROVED", "SUSPENDED")),
                    _connector="OR",
                ),
                name="mie_dev_key_requires_active_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="developeraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("signing_secret", ""),
                    ("status__in", ("APPROVED", "SUSPENDED")),
                    _connector="OR",
                ),
                name="mie_dev_secret_requires_active_status",
            ),
        ),
        migrations.AddIndex(
            model_name="coursesubmission",
            index=models.Index(
                fields=["status", "-created_datetime"], name="mie_sub_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesubmission",
            index=models.Index(
                fields=["developer", "status"], name="mie_sub_dev_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursesubmission",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                condition=models.Q(("status", "PENDING_REVIEW")),
                name="unique_pending_title_in_queue",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursesubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("APPROVED", "REJECTED")), _negated=True),
                    ("decided_at__isnull", False),
                    _connector="OR",
                ),
                name="mie_decided_submission_has_decision",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["delivery_status", "next_retry_at"], name="mie_hook_retry_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookevent",
            index=models.Index(
                fields=["submission", "-created_datetime"], name="mie_hook_sub_idx"
            ),
        ),
    ]
