# Generated by Django 5.2.14 on 2026-08-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SUBMISSION_QUEUED", "Submission Queued"),
                    ("SUBMISSION_DUPLICATE_IN_QUEUE", "Submission Duplicate In Queue"),
                    ("SUBMISSION_DUPLICATE_EXISTING", "Submission Duplicate Existing"),
                    (
                        "SUBMISSION_PREVIOUSLY_REJECTED",
                        "Submission Previously Rejected",
                    ),
                    ("SUBMISSION_APPROVED", "Submission Approved"),
                    ("SUBMISSION_REJECTED", "Submission Rejected"),
                    (
                        "SUBMISSION_PAYOUT_BYPASS_UPDATED",
                        "Submission Payout Bypass Updated",
                    ),
                ],
                help_text="What happened; maps 1:1 onto SubmissionStatus transitions.",
                max_length=40,
                verbose_name="Event Type",
            ),
        ),
    ]
