# Generated by Django 5.2.14 on 2026-09-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mie', '0002_alter_webhookevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developeraccount',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256 hex digest of the full key. Raw key is never stored. Indexed: it is the lookup column every authentication uses.', max_length=64, verbose_name='API Key Hash'),
        ),
        migrations.AlterField(
            model_name='submissionrejectionreason',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive reasons stay on historical rows and can still be inherited by dedup; they only stop being selectable when an admin rejects.', verbose_name='Is Active'),
        ),
    ]
