# Generated by Django 5.2.14 on 2026-09-14 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_import_job_document_source'),
        ('mie', '0003_alter_developeraccount_api_key_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubmission',
            name='confidence_note',
            field=models.TextField(blank=True, help_text="Optional evidence for the idea's demand, extracted from the payload like the title so reviewers see it as its own field. The payload keeps its copy untouched.", verbose_name='Confidence Note'),
        ),
        migrations.AddField(
            model_name='developeraccount',
            name='source_type',
            field=models.CharField(choices=[('EXTERNAL', 'External'), ('SYSTEM', 'System')], default='EXTERNAL', editable=False, help_text='EXTERNAL for third-party developers, SYSTEM for platform-owned integrations. Not editable: only the provisioning command sets SYSTEM, so no registration path can opt into or out of the system-account guardrails.', max_length=10, verbose_name='Source Type'),
        ),
        migrations.AddIndex(
            model_name='coursesubmission',
            index=models.Index(fields=['developer', '-created_datetime'], name='mie_sub_dev_created_idx'),
        ),
    ]
