# Generated by Django 5.2.14 on 2026-09-15 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_categoryrequest_description'),
        ('courses', '0015_normalize_assessment_options'),
        ('mie', '0004_system_account_guardrails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubmission',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Platform category this idea belongs to, resolved from the name or slug the submitter sent. Null when they sent none, or one no category matches - the raw value stays in the payload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mie_submissions', to='catalog.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='description',
            field=models.TextField(blank=True, help_text="What the idea covers, extracted from the payload like the title. Shown in the reviewer's Topic details panel.", verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], help_text='Difficulty the submitter claims for the idea.', max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='searches_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly search volume behind the idea, as reported by the submitter. The crawler fills this from its own signals.', null=True, verbose_name='Searches Per Month'),
        ),
        migrations.AddIndex(
            model_name='coursesubmission',
            index=models.Index(fields=['status', '-demand_score'], name='mie_sub_status_score_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesubmission',
            index=models.Index(fields=['status', 'category'], name='mie_sub_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesubmission',
            index=models.Index(fields=['status', 'difficulty_level'], name='mie_sub_status_diff_idx'),
        ),
    ]
