# Generated by Django 5.2.14 on 2026-09-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_course_draft_started_at_course_flag_reason_and_more"),
        ("mie", "0005_coursesubmission_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesubmission",
            name="resulting_course",
            field=models.OneToOneField(
                blank=True,
                help_text="Course produced from this idea. Reversing the idea leaves the course untouched - publication is one-way on the course side - and keeps this link, so re-approval relinks instead of duplicating.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mie_submission",
                to="courses.course",
                verbose_name="Resulting Course",
            ),
        ),
    ]
