# Generated by Django 5.2.14 on 2026-09-30 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mie', '0006_alter_coursesubmission_resulting_course_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developeraccount',
            name='creator_user',
            field=models.OneToOneField(blank=True, help_text='No-login COURSE_CREATOR account that owns the courses this developer pushes, so they run the normal creator review, QA and publish flow. Provisioned on the first course push; never linked by email, so a registration cannot claim an existing platform account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mie_developer_account', to=settings.AUTH_USER_MODEL, verbose_name='Linked Creator Account'),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='event_type',
            field=models.CharField(choices=[('SUBMISSION_QUEUED', 'Submission Queued'), ('SUBMISSION_DUPLICATE_IN_QUEUE', 'Submission Duplicate In Queue'), ('SUBMISSION_DUPLICATE_EXISTING', 'Submission Duplicate Existing'), ('SUBMISSION_PREVIOUSLY_REJECTED', 'Submission Previously Rejected'), ('SUBMISSION_APPROVED', 'Submission Approved'), ('SUBMISSION_REJECTED', 'Submission Rejected'), ('SUBMISSION_PAYOUT_BYPASS_UPDATED', 'Submission Payout Bypass Updated'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_REVISION_REQUESTED', 'Course Revision Requested'), ('COURSE_PUBLISHED', 'Course Published')], help_text='What happened: an idea transition (SUBMISSION_*) or a move of the course pushed for it (COURSE_*).', max_length=40, verbose_name='Event Type'),
        ),
    ]
