# Generated by Django 5.2.14 on 2026-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mie", "0007_developeraccount_creator_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SUBMISSION_QUEUED", "Submission Queued"),
                    ("SUBMISSION_DUPLICATE_IN_QUEUE", "Submission Duplicate In Queue"),
                    ("SUBMISSION_DUPLICATE_EXISTING", "Submission Duplicate Existing"),
                    (
                        "SUBMISSION_PREVIOUSLY_REJECTED",
                        "Submission Previously Rejected",
                    ),
                    ("SUBMISSION_APPROVED", "Submission Approved"),
                    ("SUBMISSION_REJECTED", "Submission Rejected"),
                    (
                        "SUBMISSION_PAYOUT_BYPASS_UPDATED",
                        "Submission Payout Bypass Updated",
                    ),
                    ("COURSE_SUBMITTED", "Course Submitted"),
                    ("COURSE_TEXT_APPROVED", "Course Text Approved"),
                    ("COURSE_REVISION_REQUESTED", "Course Revision Requested"),
                    ("COURSE_PUBLISHED", "Course Published"),
                ],
                help_text="What happened: an idea transition (SUBMISSION_*) or a move of the course pushed for it (COURSE_*).",
                max_length=40,
                verbose_name="Event Type",
            ),
        ),
    ]
