# Generated by Django 5.2.14 on 2026-10-08 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mie", "0008_alter_webhookevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "deleted_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="datetime of object deletion",
                        null=True,
                        verbose_name="Deleted datetime",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Is deleted", verbose_name="Is deleted"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS URL that receives a signed POST for each event it takes.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "all_events",
                    models.BooleanField(
                        default=True,
                        help_text="True to receive every event type, including any added later. When false, only the types in event_types are sent.",
                        verbose_name="All Events",
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="WebhookEventType values this endpoint receives. Empty when all_events is true.",
                        verbose_name="Event Types",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        help_text="Developer account this endpoint belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="mie.developeraccount",
                        verbose_name="Developer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
                "ordering": ["created_datetime"],
            },
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="endpoint",
            field=models.ForeignKey(
                help_text="Endpoint this delivery goes to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="mie.webhookendpoint",
                verbose_name="Endpoint",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookendpoint",
            index=models.Index(
                fields=["developer", "is_deleted"], name="mie_hook_endpoint_dev_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="webhookendpoint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("developer", "url"),
                name="mie_hook_endpoint_live_url_uniq",
            ),
        ),
    ]
