# Generated by Tses 2026-07-11T15:21:00Z
# Generated by Django 5.2.14 on 2026-07-11 15:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current wallet balance. Must never go negative.', max_digits=12, verbose_name='Balance')),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3, verbose_name='Currency')),
                ('user', models.OneToOneField(help_text='User who owns this wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute transaction amount, always positive.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Whether this transaction credits or debits the wallet.', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Settlement status of the transaction.', max_length=10, verbose_name='Status')),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of the transaction.', max_length=255, verbose_name='Description')),
                ('course', models.ForeignKey(blank=True, help_text='Course this transaction is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='courses.course', verbose_name='Course')),
                ('wallet', models.ForeignKey(help_text='Wallet this transaction belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_user_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_datetime'], name='txn_wallet_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='txn_status_idx'),
        ),
    ]
