# Generated by Django 5.2.14 on 2026-07-20 22:27

import api.wallet.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _backfill_references(apps, schema_editor):
    """Give any pre-existing Transaction rows a unique reference before the
    field's unique constraint is enforced below - a single AddField with a
    callable default only evaluates it once, which would collide across
    existing rows (see the makemigrations warning this file was generated
    from)."""

    Transaction = apps.get_model('wallet', 'Transaction')
    for txn in Transaction.objects.filter(reference='').iterator():
        txn.reference = api.wallet.models._generate_reference()
        txn.save(update_fields=['reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for this transaction, if any.', max_digits=12, verbose_name='Fee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_name',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the payout account's holder name at transaction time, so the receipt stays accurate if the account is later edited/removed.", max_length=150, verbose_name='Recipient Account Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the payout account number at transaction time.', max_length=34, verbose_name='Recipient Account Number'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_provider_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the bank/mobile-money provider at transaction time.', max_length=100, verbose_name='Recipient Provider Name'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', help_text='Unique reference shown to the user, e.g. on a receipt.', max_length=32, verbose_name='Reference'),
        ),
        migrations.RunPython(_backfill_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default=api.wallet.models._generate_reference, help_text='Unique reference shown to the user, e.g. on a receipt.', max_length=32, unique=True, verbose_name='Reference'),
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('account_type', models.CharField(choices=[('LOCAL', 'Local Account'), ('MOBILE_MONEY', 'Mobile Money')], help_text='Whether this is a local bank account or a mobile money account.', max_length=15, verbose_name='Account Type')),
                ('provider_name', models.CharField(help_text='Bank name (LOCAL) or mobile money provider (MOBILE_MONEY).', max_length=100, verbose_name='Provider Name')),
                ('account_number', models.CharField(help_text='Bank account number or mobile money number.', max_length=34, verbose_name='Account Number')),
                ('account_name', models.CharField(help_text='Name on the account, as entered when adding it.', max_length=150, verbose_name='Account Name')),
                ('is_default', models.BooleanField(default=False, help_text='Preselected payout account on the withdrawal screen.', verbose_name='Is Default')),
                ('user', models.ForeignKey(help_text='User who owns this payout account.', on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payout Account',
                'verbose_name_plural': 'Payout Accounts',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='payout_account',
            field=models.ForeignKey(blank=True, help_text='Payout account this withdrawal was sent to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='wallet.payoutaccount', verbose_name='Payout Account'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested for withdrawal.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired')], default='PENDING_CONFIRMATION', help_text='State of this withdrawal request.', max_length=25, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('payout_account', models.ForeignKey(help_text='Payout account the funds will be sent to.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.payoutaccount', verbose_name='Payout Account')),
                ('transaction', models.OneToOneField(blank=True, help_text='Transaction created once this request is confirmed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='wallet.transaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(help_text='User requesting the withdrawal.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(help_text='Wallet the withdrawal will be debited from.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='payoutaccount',
            index=models.Index(fields=['user'], name='payout_acct_user_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', '-created_datetime'], name='wdr_user_dt_idx'),
        ),
    ]
