# Generated by Django 5.2.14 on 2026-08-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0009_course_duration_estimate_minutes_course_version_and_more'),
        ('wallet', '0002_transaction_fee_transaction_recipient_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='txn_wallet_dt_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet_type', 'wallet_id', '-created_datetime'], name='txn_wallet_dt_idx'),
        ),
    ]
