# Generated by Django 5.2.14 on 2026-08-07 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction'),
        ('wallet', '0004_copy_transactions_and_payout_accounts_to_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Transaction created once this request is confirmed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='payments.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_account',
            field=models.ForeignKey(help_text='Payout account the funds will be sent to.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='payments.bankaccount', verbose_name='Payout Account'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
