# Generated by Django 5.2.14 on 2026-09-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_withdrawalrequest_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayoutAccount',
        ),
    ]
