# Generated by Django 5.2.14 on 2026-09-17 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_delete_payoutaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='CREDIT adds to the wallet; DEBIT takes from it.', max_length=10, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount moved; always positive.', max_digits=12, verbose_name='Amount')),
                ('reason', models.CharField(help_text='Why the adjustment was made; shown to the creator.', max_length=500, verbose_name='Reason')),
                ('reference', models.CharField(help_text='Ledger reference shared by the two transaction entries.', max_length=100, unique=True, verbose_name='Reference')),
                ('idempotency_key', models.CharField(help_text='Client-supplied key; a retry with the same key returns this row.', max_length=64, unique=True, verbose_name='Idempotency key')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(help_text="The wallet's owner.", on_delete=django.db.models.deletion.PROTECT, related_name='wallet_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(help_text='The wallet adjusted.', on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet adjustment',
                'verbose_name_plural': 'Wallet adjustments',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['user', '-created_datetime'], name='wallet_adj_user_dt_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_adjustment_amount_positive')],
            },
        ),
    ]
