# Generated by Django 5.2.14 on 2026-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_walletadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='NGN', help_text='ISO 4217 currency code.', max_length=3, verbose_name='Currency'),
        ),
    ]
