from decouple import config

DIGITAL_OCEAN_ACCESS_KEY = config("DIGITAL_OCEAN_ACCESS_KEY")
DIGITAL_OCEAN_SECRET_KEY = config("DIGITAL_OCEAN_SECRET_KEY")
DIGITAL_OCEAN_BUCKET = config("DIGITAL_OCEAN_BUCKET")
DIGITAL_OCEAN_ENDPOINT = config("DIGITAL_OCEAN_ENDPOINT")
DIGITAL_OCEAN_REGION = config("DIGITAL_OCEAN_REGION")
