# Generated by Django 5.2.14 on 2026-08-21 07:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_seed_default_course_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question Text")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MULTIPLE_CHOICE", "Multiple Choice"),
                            ("ESSAY", "Essay"),
                        ],
                        help_text="Answer format; MULTIPLE_CHOICE requires options.",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Points awarded for a correct answer.",
                        verbose_name="Points",
                    ),
                ),
                (
                    "model_response_guide",
                    models.TextField(
                        blank=True,
                        help_text="Reference answer used when grading ESSAY questions.",
                        verbose_name="Model Response Guide",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display position within the quiz.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["order", "created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "option_text",
                    models.CharField(max_length=500, verbose_name="Option Text"),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Whether selecting this option earns the question's points.",
                        verbose_name="Is Correct",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display position within the question.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quizzes.question",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Option",
                "verbose_name_plural": "Question Options",
                "ordering": ["order", "created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("LESSON", "Lesson"),
                            ("MODULE", "Module"),
                            ("COURSE", "Course"),
                        ],
                        help_text="Which entity level this quiz is attached to.",
                        max_length=10,
                        verbose_name="Level",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Quiz title.", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional quiz instructions shown to learners.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minimum percentage required to pass.",
                        verbose_name="Passing Score",
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional time limit for completing the quiz.",
                        null=True,
                        verbose_name="Time Limit (minutes)",
                    ),
                ),
                (
                    "attempts_allowed",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many attempts a learner gets.",
                        verbose_name="Attempts Allowed",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Present questions in random order.",
                        verbose_name="Shuffle Questions",
                    ),
                ),
                (
                    "randomize_options",
                    models.BooleanField(
                        default=False,
                        help_text="Present answer options in random order.",
                        verbose_name="Randomize Options",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.lesson",
                        verbose_name="Lesson",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="courses.module",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quizzes",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quiz",
                verbose_name="Quiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", True),
                        ("lesson__isnull", False),
                        ("module__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("lesson__isnull", True),
                        ("module__isnull", False),
                    ),
                    models.Q(
                        ("course__isnull", False),
                        ("lesson__isnull", True),
                        ("module__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="quiz_exactly_one_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(("passing_score__lte", 100)),
                name="quiz_passing_score_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("points__gt", 0)), name="question_points_positive"
            ),
        ),
    ]
