# Generated by Django 5.2.14 on 2026-08-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_created_by_quiz_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionoption",
            name="explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this option is right or wrong, shown after answering.",
                verbose_name="Explanation",
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Display position within the question; maps to the A/B/C/D letter.",
                verbose_name="Order",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("quiz", "order"), name="unique_question_order_per_quiz"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_option_order_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="one_correct_option_per_question",
            ),
        ),
    ]
