# Generated by Django 5.2.14 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0004_question_created_by_question_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_CHOICE", "Single Choice"),
                    ("MULTIPLE_CHOICE", "Multiple Choice"),
                    ("ESSAY", "Essay"),
                ],
                help_text=(
                    "Answer format; SINGLE_CHOICE and MULTIPLE_CHOICE require "
                    "options."
                ),
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
