# Generated by Django 5.2.14 on 2026-09-14

from django.db import migrations, models


def copy_option_explanations_to_question(apps, schema_editor):
    Question = apps.get_model("quizzes", "Question")
    QuestionOption = apps.get_model("quizzes", "QuestionOption")

    questions = Question.objects.filter(explanation="").only("id", "explanation")
    for question in questions.iterator():
        option_explanations = list(
            QuestionOption.objects.filter(question_id=question.id)
            .exclude(explanation="")
            .order_by("order", "created_datetime")
            .values_list("option_text", "explanation")
        )
        if not option_explanations:
            continue

        explanation = "\n".join(
            f"{option_text}: {option_explanation}"
            for option_text, option_explanation in option_explanations
        )
        question.explanation = explanation
        question.save(update_fields=["explanation"])


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_add_single_choice_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Question-level feedback or explanation shown after answering.",
                verbose_name="Explanation",
            ),
        ),
        migrations.AlterField(
            model_name="questionoption",
            name="explanation",
            field=models.TextField(
                blank=True,
                default="",
                help_text=(
                    "Deprecated. Explanations now live on Question.explanation so "
                    "the feedback belongs to the whole question, not one option."
                ),
                verbose_name="Explanation",
            ),
        ),
        migrations.RunPython(
            copy_option_explanations_to_question,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
