# Generated by Django 5.2.14 on 2026-09-29 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CONTACT", "Contact us"),
                            ("TICKET", "Create ticket"),
                            ("APPEAL", "Request for an appeal"),
                        ],
                        max_length=10,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email as typed on the form.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 country code (contact form).",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="Title"),
                ),
                (
                    "web_link",
                    models.URLField(
                        blank=True,
                        help_text="Optional supporting link.",
                        verbose_name="Web Link",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Contact message, or the ticket/appeal description.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Appeals only: PRD dispute-resolution SLA (7 business days).",
                        null=True,
                        verbose_name="Due At",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Resolution Notes"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Resolved By",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signed-in submitter; empty for anonymous contact messages.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Request",
                "verbose_name_plural": "Support Requests",
                "ordering": ["-created_datetime"],
                "indexes": [
                    models.Index(
                        fields=["kind", "status"], name="support_kind_status_idx"
                    )
                ],
            },
        ),
    ]
