# Generated by Tses 2026-07-09T12:37:38Z
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from api.users.enums import UserActivityActionEnums, UserActivityCategoryEnums
from core.mixins import DateHistoryModelMixin, UUIDPrimaryKeyModelMixin


class UserActivityLog(UUIDPrimaryKeyModelMixin, DateHistoryModelMixin):
    """Store user-facing audit events in a generic, query-friendly format.

    This model is scaffolded as a reusable audit trail. Teams can extend the enum
    choices, add more request metadata, or attach domain-specific foreign keys
    without changing the overall logging pattern.
    """

    user = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="activity_logs",
        verbose_name=_("User"),
        help_text=_("User whose activity is being recorded."),
    )
    actor_user = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="performed_activity_logs",
        verbose_name=_("Actor User"),
        help_text=_("User who performed the activity, if applicable."),
    )
    category = models.CharField(
        verbose_name=_("Category"),
        max_length=30,
        choices=UserActivityCategoryEnums.choices,
        help_text=_("High-level category of the activity."),
    )
    action = models.CharField(
        verbose_name=_("Action"),
        max_length=80,
        choices=UserActivityActionEnums.choices,
        help_text=_("Specific activity action."),
    )
    summary = models.CharField(
        verbose_name=_("Summary"),
        max_length=255,
        help_text=_("Human-readable activity summary."),
    )
    details = models.JSONField(
        verbose_name=_("Details"),
        default=dict,
        blank=True,
        help_text=_("Structured activity payload."),
    )
    activity_datetime = models.DateTimeField(
        verbose_name=_("Activity Datetime"),
        help_text=_("When the activity occurred."),
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="user_activity_logs",
    )
    object_id = models.CharField(max_length=64, null=True, blank=True)
    target = GenericForeignKey("content_type", "object_id")
    ip_address = models.GenericIPAddressField(
        verbose_name=_("IP Address"),
        null=True,
        blank=True,
        help_text=_("Resolved source IP for the activity request."),
    )
    user_agent = models.TextField(
        verbose_name=_("User Agent"),
        blank=True,
        default="",
        help_text=_("Client user agent for the activity request."),
    )
    request_method = models.CharField(
        verbose_name=_("Request Method"),
        max_length=10,
        blank=True,
        default="",
        help_text=_("HTTP method for the request that produced the activity."),
    )
    request_path = models.CharField(
        verbose_name=_("Request Path"),
        max_length=500,
        blank=True,
        default="",
        help_text=_("HTTP path for the request that produced the activity."),
    )

    class Meta:
        verbose_name = "User Activity Log"
        verbose_name_plural = "User Activity Logs"
        ordering = ("-activity_datetime", "-created_datetime", "-id")
        indexes = [
            models.Index(
                fields=["user", "activity_datetime"],
                name="user_act_log_user_dt_idx",
            ),
            models.Index(
                fields=["actor_user", "activity_datetime"],
                name="user_act_log_actor_dt_idx",
            ),
            models.Index(
                fields=["category", "action", "activity_datetime"],
                name="user_act_log_cat_act_dt_idx",
            ),
            models.Index(
                fields=["content_type", "object_id"],
                name="user_act_log_target_idx",
            ),
        ]

    def __str__(self):
        """Return a compact identifier that is useful in admin and debugging."""

        return f"{self.user_id} {self.action} at {self.activity_datetime}"
