# Generated by Tses 2026-07-09T12:37:38Z
# Generated by Django 5.2.14 on 2026-06-22 21:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('created_by', models.ForeignKey(help_text='User who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('PROFILE', 'Profile')], help_text='High-level category of the activity.', max_length=30, verbose_name='Category')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed')], help_text='Specific activity action.', max_length=80, verbose_name='Action')),
                ('summary', models.CharField(help_text='Human-readable activity summary.', max_length=255, verbose_name='Summary')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured activity payload.', verbose_name='Details')),
                ('activity_datetime', models.DateTimeField(help_text='When the activity occurred.', verbose_name='Activity Datetime')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Resolved source IP for the activity request.', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client user agent for the activity request.', verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, default='', help_text='HTTP method for the request that produced the activity.', max_length=10, verbose_name='Request Method')),
                ('request_path', models.CharField(blank=True, default='', help_text='HTTP path for the request that produced the activity.', max_length=500, verbose_name='Request Path')),
                ('actor_user', models.ForeignKey(blank=True, help_text='User who performed the activity, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor User')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activity_logs', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User whose activity is being recorded.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ('-activity_datetime', '-created_datetime', '-id'),
                'indexes': [models.Index(fields=['user', 'activity_datetime'], name='user_act_log_user_dt_idx'), models.Index(fields=['actor_user', 'activity_datetime'], name='user_act_log_actor_dt_idx'), models.Index(fields=['category', 'action', 'activity_datetime'], name='user_act_log_cat_act_dt_idx'), models.Index(fields=['content_type', 'object_id'], name='user_act_log_target_idx')],
            },
        ),
    ]
