# Generated by Tses 2026-07-11T15:21:00Z
# Generated by Django 5.2.14 on 2026-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_created_by_alter_user_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('ADMIN', 'Admin')], default='COURSE_CREATOR', help_text='Primary role used for role-based permission checks.', max_length=20, verbose_name='Role'),
        ),
    ]
