# Generated by Tses 2026-07-12T18:57:00Z
# Generated by Django 5.2.14 on 2026-07-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
    ]
