# Generated by Django 5.2.14 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('STAFF_WRITER', 'Writer'), ('STAFF_VERIFIER', 'Verifier'), ('STAFF_APPROVER', 'Approver'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='COURSE_CREATOR', help_text='Primary role used for role-based permission checks.', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('SUPERADMIN_BOOTSTRAPPED', 'Super Admin Bootstrapped'), ('STAFF_INVITED', 'Staff Invited'), ('STAFF_INVITATION_ACCEPTED', 'Staff Invitation Accepted'), ('STAFF_REVOKED', 'Staff Revoked'), ('STAFF_REACTIVATED', 'Staff Reactivated')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'SUPER_ADMIN')), fields=('role',), name='unique_super_admin'),
        ),
    ]
