# Generated by Tses 2026-07-14T09:53:23Z
# Generated by Django 5.2.14 on 2026-07-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code.', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the Terms and Conditions.', null=True, verbose_name='Terms Accepted At'),
        ),
    ]
