# Generated by Django 5.2.14 on 2026-07-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_country_terms_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', help_text='Self-reported sex.', max_length=20, verbose_name='Sex'),
        ),
    ]
