# Generated by Django 5.2.14 on 2026-07-19 20:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text='Profile picture URL.', verbose_name='Avatar URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="IANA timezone identifier, e.g. 'Africa/Lagos'.", max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('COURSE_ASSIGNED', 'Course Assigned'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('COURSE_PUBLISHED', 'Course Published'), ('AVAILABILITY_UPDATED', 'Availability Updated'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'Authentication'), ('PROFILE', 'Profile'), ('COURSE', 'Course'), ('SUBMISSION', 'Submission'), ('APPROVAL', 'Approval'), ('PUBLISH', 'Publish'), ('CONFIGURATION', 'Configuration'), ('PRODUCTION', 'Production'), ('ALERT', 'Alert')], help_text='High-level category of the activity.', max_length=30, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='ReviewerAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('is_available', models.BooleanField(default=True, help_text='Whether new courses can be claimed/approved/rejected by this reviewer.', verbose_name='Is Available')),
                ('unavailability_reason', models.CharField(blank=True, choices=[('VACATION', 'Vacation'), ('SICK_LEAVE', 'Sick Leave'), ('PERSONAL', 'Personal'), ('TRAINING', 'Training'), ('OTHER', 'Other')], default='', help_text='Why this reviewer is unavailable, if applicable.', max_length=20, verbose_name='Unavailability Reason')),
                ('return_date', models.DateField(blank=True, help_text='Date this reviewer expects to become available again.', null=True, verbose_name='Return Date')),
                ('auto_return_enabled', models.BooleanField(default=True, help_text='Automatically treat as available once return_date has passed.', verbose_name='Auto Return Enabled')),
                ('user', models.OneToOneField(help_text='Reviewer this availability setting belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_availability', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reviewer Availability',
                'verbose_name_plural': 'Reviewer Availabilities',
            },
        ),
    ]
