# Generated by Django 5.2.14 on 2026-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role_alter_useractivitylog_action_and_more"),
        ("users", "0007_user_avatar_url_user_timezone_and_more"),
    ]

    operations = []
