# Generated by Django 5.2.14 on 2026-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_merge_20260720_1548"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("TOKEN_REFRESHED", "Token Refreshed"),
                    ("ACCOUNT_VERIFIED", "Account Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("ONBOARDING_COMPLETED", "Onboarding Completed"),
                    ("SUPERADMIN_BOOTSTRAPPED", "Super Admin Bootstrapped"),
                    ("STAFF_INVITED", "Staff Invited"),
                    ("STAFF_INVITATION_ACCEPTED", "Staff Invitation Accepted"),
                    ("STAFF_REVOKED", "Staff Revoked"),
                    ("STAFF_REACTIVATED", "Staff Reactivated"),
                    ("COURSE_ASSIGNED", "Course Assigned"),
                    ("COURSE_SUBMITTED", "Course Submitted"),
                    ("COURSE_APPROVED", "Course Approved"),
                    ("COURSE_REJECTED", "Course Rejected"),
                    ("COURSE_PUBLISHED", "Course Published"),
                    ("AVAILABILITY_UPDATED", "Availability Updated"),
                    (
                        "NOTIFICATION_PREFERENCES_UPDATED",
                        "Notification Preferences Updated",
                    ),
                ],
                help_text="Specific activity action.",
                max_length=80,
                verbose_name="Action",
            ),
        ),
    ]
