# Generated by Django 5.2.14 on 2026-07-21 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('SUPERADMIN_BOOTSTRAPPED', 'Super Admin Bootstrapped'), ('STAFF_INVITED', 'Staff Invited'), ('STAFF_INVITATION_ACCEPTED', 'Staff Invitation Accepted'), ('STAFF_REVOKED', 'Staff Revoked'), ('STAFF_REACTIVATED', 'Staff Reactivated'), ('COURSE_ASSIGNED', 'Course Assigned'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('COURSE_PUBLISHED', 'Course Published'), ('AVAILABILITY_UPDATED', 'Availability Updated'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_CONFIRMED', 'Withdrawal Confirmed')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'Authentication'), ('PROFILE', 'Profile'), ('COURSE', 'Course'), ('SUBMISSION', 'Submission'), ('APPROVAL', 'Approval'), ('PUBLISH', 'Publish'), ('CONFIGURATION', 'Configuration'), ('PRODUCTION', 'Production'), ('ALERT', 'Alert'), ('KYC', 'KYC'), ('WALLET', 'Wallet')], help_text='High-level category of the activity.', max_length=30, verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('country_of_issue', models.CharField(help_text="ISO 3166-1 alpha-2 code of the document's issuing country.", max_length=2, verbose_name='Country of Issue')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_ID', "Voter's ID")], help_text='Type of identity document submitted.', max_length=32, verbose_name='Document Type')),
                ('id_number', models.CharField(help_text="The identity document's number, as entered by the user.", max_length=64, verbose_name='ID Number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Review status of this submission.', max_length=10, verbose_name='Status')),
                ('rejection_reason', models.CharField(blank=True, default='', help_text='Why this submission was rejected, if applicable.', max_length=255, verbose_name='Rejection Reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_done', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(help_text='User this verification submission belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['user', '-created_datetime'], name='kyc_user_dt_idx')],
            },
        ),
    ]
