# Generated by Django 5.2.14 on 2026-08-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failed login attempts since the last successful login.', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='PENDING_VERIFICATION', help_text='Account activation/lifecycle status, independent of role.', max_length=25, verbose_name='Account Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('STAFF_WRITER', 'Writer'), ('STAFF_VERIFIER', 'Verifier'), ('STAFF_APPROVER', 'Approver'), ('AI_REVIEWER', 'AI Reviewer'), ('QA_REVIEWER', 'QA Reviewer'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='COURSE_CREATOR', help_text='Primary role used for role-based permission checks.', max_length=20, verbose_name='Role'),
        ),
    ]
