# Generated by Django 5.2.14 on 2026-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_user_locked_until_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_CREATED", "Account Created"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOCKOUT_TRIGGERED", "Account Locked (Repeated Failed Logins)"),
                    ("LOCKOUT_CLEARED", "Account Lockout Cleared"),
                    ("SESSIONS_REVOKED", "Sessions Revoked (All Devices)"),
                    ("TOKEN_REFRESHED", "Token Refreshed"),
                    ("ACCOUNT_VERIFIED", "Account Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("ONBOARDING_COMPLETED", "Onboarding Completed"),
                    ("SUPERADMIN_BOOTSTRAPPED", "Super Admin Bootstrapped"),
                    ("STAFF_INVITED", "Staff Invited"),
                    ("STAFF_INVITATION_ACCEPTED", "Staff Invitation Accepted"),
                    ("STAFF_REVOKED", "Staff Revoked"),
                    ("STAFF_REACTIVATED", "Staff Reactivated"),
                    ("ACCOUNT_SUSPENDED", "Account Suspended"),
                    ("ACCOUNT_REINSTATED", "Account Reinstated"),
                    ("ACCOUNT_DEACTIVATED", "Account Deactivated"),
                    ("COURSE_ASSIGNED", "Course Assigned"),
                    ("COURSE_SUBMITTED", "Course Submitted"),
                    ("COURSE_APPROVED", "Course Approved"),
                    ("COURSE_REJECTED", "Course Rejected"),
                    ("COURSE_PUBLISHED", "Course Published"),
                    ("AVAILABILITY_UPDATED", "Availability Updated"),
                    (
                        "NOTIFICATION_PREFERENCES_UPDATED",
                        "Notification Preferences Updated",
                    ),
                    ("KYC_SUBMITTED", "KYC Submitted"),
                    ("KYC_APPROVED", "KYC Approved"),
                    ("KYC_REJECTED", "KYC Rejected"),
                    ("WITHDRAWAL_REQUESTED", "Withdrawal Requested"),
                    ("WITHDRAWAL_CONFIRMED", "Withdrawal Confirmed"),
                ],
                help_text="Specific activity action.",
                max_length=80,
                verbose_name="Action",
            ),
        ),
    ]
