# Generated by Django 5.2.14 on 2026-08-07 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_CREATED", "Account Created"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("LOCKOUT_TRIGGERED", "Account Locked (Repeated Failed Logins)"),
                    ("SESSIONS_REVOKED", "Sessions Revoked (All Devices)"),
                    ("TOKEN_REFRESHED", "Token Refreshed"),
                    ("ACCOUNT_VERIFIED", "Account Verified"),
                    ("PASSWORD_RESET_COMPLETED", "Password Reset Completed"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("ONBOARDING_COMPLETED", "Onboarding Completed"),
                    ("SUPERADMIN_BOOTSTRAPPED", "Super Admin Bootstrapped"),
                    ("STAFF_INVITED", "Staff Invited"),
                    ("STAFF_INVITATION_ACCEPTED", "Staff Invitation Accepted"),
                    ("STAFF_REVOKED", "Staff Revoked"),
                    ("STAFF_REACTIVATED", "Staff Reactivated"),
                    ("COURSE_ASSIGNED", "Course Assigned"),
                    ("COURSE_SUBMITTED", "Course Submitted"),
                    ("COURSE_APPROVED", "Course Approved"),
                    ("COURSE_REJECTED", "Course Rejected"),
                    ("COURSE_PUBLISHED", "Course Published"),
                    ("AVAILABILITY_UPDATED", "Availability Updated"),
                    (
                        "NOTIFICATION_PREFERENCES_UPDATED",
                        "Notification Preferences Updated",
                    ),
                    ("QUEUE_PREFERENCES_UPDATED", "Queue Preferences Updated"),
                    ("ACTIVITY_LOG_EXPORTED", "Activity Log Exported"),
                    ("KYC_SUBMITTED", "KYC Submitted"),
                    ("KYC_APPROVED", "KYC Approved"),
                    ("KYC_REJECTED", "KYC Rejected"),
                    ("WITHDRAWAL_REQUESTED", "Withdrawal Requested"),
                    ("WITHDRAWAL_CONFIRMED", "Withdrawal Confirmed"),
                    ("APPEAL_SUBMITTED", "Appeal Submitted"),
                    ("APPEAL_APPROVED", "Appeal Approved"),
                    ("APPEAL_REJECTED", "Appeal Rejected"),
                ],
                help_text="Specific activity action.",
                max_length=80,
                verbose_name="Action",
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="category",
            field=models.CharField(
                choices=[
                    ("AUTH", "Authentication"),
                    ("PROFILE", "Profile"),
                    ("COURSE", "Course"),
                    ("SUBMISSION", "Submission"),
                    ("APPROVAL", "Approval"),
                    ("PUBLISH", "Publish"),
                    ("CONFIGURATION", "Configuration"),
                    ("PRODUCTION", "Production"),
                    ("ALERT", "Alert"),
                    ("KYC", "KYC"),
                    ("WALLET", "Wallet"),
                    ("PRIVACY", "Privacy"),
                ],
                help_text="High-level category of the activity.",
                max_length=30,
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="QueueBehaviourPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "default_sort_order",
                    models.CharField(
                        choices=[
                            ("OLDEST_FIRST", "Oldest First"),
                            ("NEWEST_FIRST", "Newest First"),
                            ("SLA_URGENCY", "SLA Urgency"),
                        ],
                        default="OLDEST_FIRST",
                        help_text="Default ordering applied to the review queue.",
                        max_length=20,
                        verbose_name="Default Sort Order",
                    ),
                ),
                (
                    "auto_advance_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Frontend-only: automatically advance to the next queue item after approving or rejecting a course.",
                        verbose_name="Auto Advance Enabled",
                    ),
                ),
                (
                    "track_filter",
                    models.CharField(
                        choices=[
                            ("ALL", "All Tracks"),
                            ("CREATOR_TRACK", "Creator Track"),
                            ("AI_TRACK", "AI Track"),
                        ],
                        default="ALL",
                        help_text="Default track filter applied to the review queue.",
                        max_length=20,
                        verbose_name="Track Filter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Reviewer this queue-behaviour preference belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_behaviour_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Behaviour Preference",
                "verbose_name_plural": "Queue Behaviour Preferences",
            },
        ),
    ]
