# Generated by Django 5.2.14 on 2026-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Street address, or similar.', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="User's phone number.", max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State, province or region.', max_length=50, verbose_name='State'),
        ),
    ]
