# Generated by Django 5.2.14 on 2026-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_useractivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOCKOUT_TRIGGERED', 'Account Locked (Repeated Failed Logins)'), ('LOCKOUT_CLEARED', 'Account Lockout Cleared'), ('SESSIONS_REVOKED', 'Sessions Revoked (All Devices)'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_STEP_UPDATED', 'Onboarding Step Updated'), ('POLICY_ACCEPTED', 'Policy Accepted'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('COURSE_BUILDER_ACCESS_GRANTED', 'Course Builder Access Granted'), ('SUPERADMIN_BOOTSTRAPPED', 'Super Admin Bootstrapped'), ('STAFF_INVITED', 'Staff Invited'), ('STAFF_INVITATION_ACCEPTED', 'Staff Invitation Accepted'), ('STAFF_REVOKED', 'Staff Revoked'), ('STAFF_REACTIVATED', 'Staff Reactivated'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REINSTATED', 'Account Reinstated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('COURSE_ASSIGNED', 'Course Assigned'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('COURSE_PUBLISHED', 'Course Published'), ('AVAILABILITY_UPDATED', 'Availability Updated'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated'), ('QUEUE_PREFERENCES_UPDATED', 'Queue Preferences Updated'), ('ACTIVITY_LOG_EXPORTED', 'Activity Log Exported'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_CONFIRMED', 'Withdrawal Confirmed'), ('APPEAL_SUBMITTED', 'Appeal Submitted'), ('APPEAL_APPROVED', 'Appeal Approved'), ('APPEAL_REJECTED', 'Appeal Rejected'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('MFA_CHALLENGE_FAILED', 'MFA Challenge Failed'), ('MFA_RECOVERY_CODE_USED', 'MFA Recovery Code Used'), ('MFA_RECOVERY_CODES_REGENERATED', 'MFA Recovery Codes Regenerated'), ('MFA_RESET_BY_ADMIN', 'MFA Reset By Admin')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='category',
            field=models.CharField(choices=[('AUTH', 'Authentication'), ('PROFILE', 'Profile'), ('ONBOARDING', 'Onboarding'), ('COURSE', 'Course'), ('SUBMISSION', 'Submission'), ('APPROVAL', 'Approval'), ('PUBLISH', 'Publish'), ('CONFIGURATION', 'Configuration'), ('PRODUCTION', 'Production'), ('ALERT', 'Alert'), ('KYC', 'KYC'), ('WALLET', 'Wallet'), ('PRIVACY', 'Privacy')], help_text='High-level category of the activity.', max_length=30, verbose_name='Category'),
        ),
    ]
