# Generated by Django 5.2.14 on 2026-08-12 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text="Contact phone number, optionally with a leading '+'.", max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +2348012345678 or 2348012345678.', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='Phone Number'),
        ),
    ]
