# Generated by Django 5.2.14 on 2026-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_track',
            field=models.CharField(blank=True, choices=[('ALL', 'All Tracks'), ('CREATOR_TRACK', 'Creator Track'), ('AI_TRACK', 'AI Track')], help_text='Production track a reviewer is assigned to, set by an admin. Read-only to the reviewer - distinct from their own QueueBehaviourPreference.track_filter, which is a personal queue filter they control. Null for users the concept does not apply to.', max_length=20, null=True, verbose_name='Assigned Track'),
        ),
    ]
