# Generated by Django 5.2.14 on 2026-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sissl_date_of_birth',
            field=models.CharField(blank=True, default='', help_text='Date of birth exactly as returned by SISSL (format varies by source).', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='sissl_document_image',
            field=models.CharField(blank=True, default='', help_text='Private Spaces object key for the government ID photo; served via presigned GET.', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='sissl_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='sissl_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sissl_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
