"""Replace QueueBehaviourPreference.track_filter with the design's three
toggles, and widen the sort-order options to match its dropdown.

Hand-written so the boolean columns are **populated from the old enum
before** it is dropped. The autogenerated version removes the column
first, which would silently reset every reviewer's track preference to
the defaults.
"""

from django.db import migrations, models


def enum_to_toggles(apps, schema_editor):
    """Carry each stored filter onto the equivalent toggle combination."""

    Preference = apps.get_model("users", "QueueBehaviourPreference")

    Preference.objects.filter(track_filter="ALL").update(
        show_both_track=True, show_ai_track=False, show_creator_track=False
    )
    Preference.objects.filter(track_filter="AI_TRACK").update(
        show_both_track=False, show_ai_track=True, show_creator_track=False
    )
    Preference.objects.filter(track_filter="CREATOR_TRACK").update(
        show_both_track=False, show_ai_track=False, show_creator_track=True
    )


def toggles_to_enum(apps, schema_editor):
    """Reverse: collapse the toggles back to a single filter.

    Mirrors QueueBehaviourPreference.effective_track_filter, except that
    "every track off" has no representation in the old enum and becomes
    ALL - the only non-destructive direction to err in.
    """

    Preference = apps.get_model("users", "QueueBehaviourPreference")

    Preference.objects.filter(show_both_track=True).update(track_filter="ALL")
    Preference.objects.filter(
        show_both_track=False, show_ai_track=True, show_creator_track=True
    ).update(track_filter="ALL")
    Preference.objects.filter(
        show_both_track=False, show_ai_track=True, show_creator_track=False
    ).update(track_filter="AI_TRACK")
    Preference.objects.filter(
        show_both_track=False, show_ai_track=False, show_creator_track=True
    ).update(track_filter="CREATOR_TRACK")
    Preference.objects.filter(
        show_both_track=False, show_ai_track=False, show_creator_track=False
    ).update(track_filter="ALL")


def retire_sla_urgency(apps, schema_editor):
    """SLA_URGENCY is no longer an offered option; fall back to the default.

    Left as a data migration rather than a constraint so an existing
    preference does not become unreadable.
    """

    apps.get_model("users", "QueueBehaviourPreference").objects.filter(
        default_sort_order="SLA_URGENCY"
    ).update(default_sort_order="ALL")


SORT_CHOICES = [
    ("ALL", "All"),
    ("NEWEST_FIRST", "Newest First"),
    ("OLDEST_FIRST", "Oldest First"),
    ("LAST_30_DAYS", "Last 30 days"),
    ("LAST_7_DAYS", "Last 7 days"),
    ("LAST_24_HOURS", "Last 24 hours"),
]

TRACK_CHOICES = [
    ("ALL", "All Tracks"),
    ("CREATOR_TRACK", "Creator Track"),
    ("AI_TRACK", "AI Track"),
]


class Migration(migrations.Migration):
    dependencies = [("users", "0021_user_assigned_track")]

    operations = [
        # 1. Add the toggles alongside the old column.
        migrations.AddField(
            model_name="queuebehaviourpreference",
            name="show_ai_track",
            field=models.BooleanField(
                default=False,
                verbose_name="Show AI Track Courses",
                help_text="Include APE-produced courses in the reviewer's queue.",
            ),
        ),
        migrations.AddField(
            model_name="queuebehaviourpreference",
            name="show_creator_track",
            field=models.BooleanField(
                default=False,
                verbose_name="Show Creator Track Courses",
                help_text="Include human-submitted courses in the reviewer's queue.",
            ),
        ),
        migrations.AddField(
            model_name="queuebehaviourpreference",
            name="show_both_track",
            field=models.BooleanField(
                default=True,
                verbose_name="Show Both Tracks",
                help_text=(
                    "Include both AI and human-created courses. Wins over the "
                    "two toggles above when on, matching the design's third "
                    "switch. Defaults on so a new reviewer sees the whole "
                    "queue rather than an empty one."
                ),
            ),
        ),
        # 2. Carry the stored preference across before dropping it.
        migrations.RunPython(enum_to_toggles, toggles_to_enum),
        migrations.RunPython(retire_sla_urgency, migrations.RunPython.noop),
        # 3. Only now is the enum column redundant.
        migrations.RemoveField(
            model_name="queuebehaviourpreference", name="track_filter"
        ),
        migrations.AlterField(
            model_name="queuebehaviourpreference",
            name="default_sort_order",
            field=models.CharField(
                choices=SORT_CHOICES,
                default="ALL",
                max_length=20,
                verbose_name="Default Sort Order",
                help_text=(
                    "Default view applied to the review queue - an ordering, "
                    "or a recent-window filter sorted oldest-first."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="assigned_track",
            field=models.CharField(
                blank=True,
                choices=TRACK_CHOICES,
                max_length=20,
                null=True,
                verbose_name="Assigned Track",
                help_text=(
                    "Production track a reviewer is assigned to, set by an "
                    "admin. NONE is deliberately not offered - it is a "
                    "queue-narrowing outcome, not an assignment. Read-only "
                    "to the reviewer - distinct from their own "
                    "QueueBehaviourPreference toggles, which they control."
                ),
            ),
        ),
    ]
