# Generated by Django 5.2.14 on 2026-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_sissl_date_of_birth_user_sissl_document_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='document_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'National ID (NIN)'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_ID', "Voter's ID"), ('BVN', 'Bank Verification Number (BVN)')], help_text='Type of identity document submitted.', max_length=32, verbose_name='Document Type'),
        ),
    ]
