# Generated by Django 5.2.14 on 2026-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_kycverification_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='sissl_request_summary',
            field=models.JSONField(blank=True, help_text='Summary of the request sent to SISSL for this submission.', null=True, verbose_name='SISSL Request Summary'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sissl_response_summary',
            field=models.JSONField(blank=True, help_text='Summary of the response received from SISSL for this submission.', null=True, verbose_name='SISSL Response Summary'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='sissl_status',
            field=models.CharField(blank=True, default='', help_text='Status returned by SISSL for this submission.', max_length=20, verbose_name='SISSL Status'),
        ),
    ]
