# Generated by Django 5.2.14 on 2026-09-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_queue_track_toggles'),
        ('users', '0023_kycverification_sissl_request_summary_and_more'),
    ]

    operations = [
    ]
