# Generated by Django 5.2.14 on 2026-09-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20260903_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sissl_document_image',
            new_name='kyc_document_image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sissl_first_name',
            new_name='kyc_first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sissl_gender',
            new_name='kyc_gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sissl_last_name',
            new_name='kyc_last_name',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='sissl_request_summary',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='sissl_response_summary',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='sissl_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sissl_date_of_birth',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='kyc_provider',
            field=models.CharField(blank=True, default='', help_text='The KYC provider used for this submission.', max_length=100, verbose_name='KYC Provider'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='kyc_request_status',
            field=models.CharField(blank=True, default='', help_text='Status returned by the KYC request for this submission.', max_length=20, verbose_name='KYC Request Status'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='kyc_request_summary',
            field=models.JSONField(blank=True, help_text='Summary of the request sent to KYC provider for this submission.', null=True, verbose_name='KYC Request Summary'),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='kyc_response_summary',
            field=models.JSONField(blank=True, help_text='Summary of the response received from the KYC provider for this submission.', null=True, verbose_name='KYC Response Summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_date_of_birth',
            field=models.CharField(blank=True, default='', help_text='Date of birth exactly as returned by KYC provider (format varies by source).', max_length=50),
        ),
    ]
