# Generated by Django 5.2.14 on 2026-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_sissl_document_image_user_kyc_document_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='kyc_entity_id',
            field=models.CharField(blank=True, default='', help_text='The entity ID returned by the KYC provider for this submission. Applies only to verification by YouVerify.', max_length=100, verbose_name='KYC Entity ID'),
        ),
    ]
