# Generated by Django 5.2.14 on 2026-09-04 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_kycverification_kyc_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2026, 9, 4, 15, 57, 55, 985336, tzinfo=datetime.timezone.utc), help_text="The user's date of birth as provided in the KYC submission.", verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
