# Generated by Django 5.2.14 on 2026-09-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_kycverification_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='id_number',
            field=models.CharField(help_text="The identity document's number, as entered by the user.--will be stored encrypted.", max_length=255, verbose_name='ID Number'),
        ),
    ]
