# Generated by Django 5.2.14 on 2026-09-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_kycverification_id_number'),
        ('users', '0028_alter_useractivitylog_action'),
    ]

    operations = [
    ]
