# Generated by Django 5.2.14 on 2026-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_merge_20260908_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='kyc_request_summary',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='kyc_response_summary',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='kyc_failure_message',
            field=models.TextField(blank=True, default='', help_text='Failure message returned by the KYC provider for this submission, if any.', verbose_name='KYC Failure Message'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='kyc_entity_id',
            field=models.CharField(blank=True, default='', help_text='The entity ID returned by the KYC provider for this submission. May be needed for future reference.', max_length=100, verbose_name='KYC Entity ID'),
        ),
    ]
