# Generated by Django 5.2.14 on 2026-09-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_merge_20260908_2107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Profile picture reference. Holds the file_key (or full CDN URL) returned by the upload presign endpoint; the value is backend-generated, so it may exceed 200 characters.",
                max_length=500,
                verbose_name="Avatar URL",
            ),
        ),
    ]
