# Generated by Django 5.2.14 on 2026-09-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_kycverification_kyc_request_summary_and_more'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS sissl_configurations CASCADE;"),
        migrations.RunSQL("DROP TABLE IF EXISTS sissl_logs CASCADE;"),
    ]
