# Generated by Django 5.2.14 on 2026-09-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_avatar_url_max_length_500'),
        ('users', '0031_drop_sissl_tables'),
    ]

    operations = [
    ]
