# Generated by Django 5.2.14 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_20260912_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liveness_passes',
            field=models.BooleanField(default=False, help_text='Indicates whether the liveness selfie is confirmed as live human presence.'),
        ),
        migrations.AddField(
            model_name='user',
            name='liveness_score',
            field=models.FloatField(blank=True, help_text='Liveness score returned by the KYC provider for the selfie.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='liveness_selfie',
            field=models.URLField(blank=True, default='', help_text='Public Spaces object key or full CDN URL for the liveness selfie', max_length=500),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], default='PENDING', help_text='Review status of this submission.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('LOGIN', 'Login'), ('GOOGLE_IDENTITY_LINKED', 'Google Identity Linked'), ('LOGOUT', 'Logout'), ('LOCKOUT_TRIGGERED', 'Account Locked (Repeated Failed Logins)'), ('LOCKOUT_CLEARED', 'Account Lockout Cleared'), ('SESSIONS_REVOKED', 'Sessions Revoked (All Devices)'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('SUPERADMIN_BOOTSTRAPPED', 'Super Admin Bootstrapped'), ('STAFF_INVITED', 'Staff Invited'), ('STAFF_INVITATION_ACCEPTED', 'Staff Invitation Accepted'), ('STAFF_REVOKED', 'Staff Revoked'), ('STAFF_REACTIVATED', 'Staff Reactivated'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REINSTATED', 'Account Reinstated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('COURSE_ASSIGNED', 'Course Assigned'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('COURSE_PUBLISHED', 'Course Published'), ('AVAILABILITY_UPDATED', 'Availability Updated'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated'), ('QUEUE_PREFERENCES_UPDATED', 'Queue Preferences Updated'), ('ACTIVITY_LOG_EXPORTED', 'Activity Log Exported'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_FLAGGED', 'KYC Flagged'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_CONFIRMED', 'Withdrawal Confirmed'), ('WITHDRAWAL_FAILED', 'Withdrawal Failed'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('APPEAL_SUBMITTED', 'Appeal Submitted'), ('APPEAL_APPROVED', 'Appeal Approved'), ('APPEAL_REJECTED', 'Appeal Rejected'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('MFA_CHALLENGE_FAILED', 'MFA Challenge Failed'), ('MFA_RECOVERY_CODE_USED', 'MFA Recovery Code Used'), ('MFA_RECOVERY_CODES_REGENERATED', 'MFA Recovery Codes Regenerated'), ('MFA_RESET_BY_ADMIN', 'MFA Reset By Admin'), ('BANK_ACCOUNT_ADDED', 'Bank Account Added'), ('BANK_ACCOUNT_DELETED', 'Bank Account Deleted'), ('BANK_ACCOUNT_UPDATED', 'Bank Account Updated')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
    ]
