# Generated by Django 5.2.14 on 2026-09-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_liveness_passes_user_liveness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_address',
            field=models.JSONField(blank=True, default=dict, help_text='Address exactly as returned by KYC provider.'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number exactly as returned by KYC provider.', max_length=20),
        ),
    ]
