# Generated by Django 5.2.14 on 2026-09-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_kyc_address_user_kyc_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth.", null=True, verbose_name='Date of Birth'),
        ),
    ]
