# Generated by Django 5.2.14 on 2026-09-16 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('users', '0036_alter_useractivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_role',
            field=models.ForeignKey(blank=True, help_text='The role whose permissions this user holds. Always has base_role equal to `role`; defaults to the built-in role for `role` when not set explicitly.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='authorization.role', verbose_name='Access role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('STAFF_WRITER', 'Writer'), ('STAFF_VERIFIER', 'Verifier'), ('STAFF_APPROVER', 'Approver'), ('AI_REVIEWER', 'AI Reviewer'), ('QA_REVIEWER', 'QA Reviewer'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='COURSE_CREATOR', help_text='Workflow role: decides review seats, MFA mandate, staff roster membership and login workspace. Permissions come from access_role.', max_length=20, verbose_name='Role'),
        ),
    ]
