# Generated by Django 5.2.14 on 2026-09-17 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_access_role_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erased_at',
            field=models.DateTimeField(blank=True, help_text='When this account was deleted and its personal data erased. Set once, never cleared: an erased account cannot be restored.', null=True, verbose_name='Erased at'),
        ),
        migrations.AddField(
            model_name='user',
            name='erased_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who deleted the account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erased by'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account Created'), ('LOGIN', 'Login'), ('GOOGLE_IDENTITY_LINKED', 'Google Identity Linked'), ('LOGOUT', 'Logout'), ('LOCKOUT_TRIGGERED', 'Account Locked (Repeated Failed Logins)'), ('LOCKOUT_CLEARED', 'Account Lockout Cleared'), ('SESSIONS_REVOKED', 'Sessions Revoked (All Devices)'), ('TOKEN_REFRESHED', 'Token Refreshed'), ('ACCOUNT_VERIFIED', 'Account Verified'), ('PASSWORD_RESET_COMPLETED', 'Password Reset Completed'), ('PROFILE_UPDATED', 'Profile Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('ONBOARDING_COMPLETED', 'Onboarding Completed'), ('SUPERADMIN_BOOTSTRAPPED', 'Super Admin Bootstrapped'), ('STAFF_INVITED', 'Staff Invited'), ('STAFF_INVITATION_ACCEPTED', 'Staff Invitation Accepted'), ('STAFF_REVOKED', 'Staff Revoked'), ('STAFF_REACTIVATED', 'Staff Reactivated'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_REINSTATED', 'Account Reinstated'), ('ACCOUNT_DEACTIVATED', 'Account Deactivated'), ('COURSE_ASSIGNED', 'Course Assigned'), ('COURSE_SUBMITTED', 'Course Submitted'), ('COURSE_APPROVED', 'Course Approved'), ('COURSE_REJECTED', 'Course Rejected'), ('COURSE_PUBLISHED', 'Course Published'), ('AVAILABILITY_UPDATED', 'Availability Updated'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated'), ('QUEUE_PREFERENCES_UPDATED', 'Queue Preferences Updated'), ('ACTIVITY_LOG_EXPORTED', 'Activity Log Exported'), ('KYC_SUBMITTED', 'KYC Submitted'), ('KYC_APPROVED', 'KYC Approved'), ('KYC_REJECTED', 'KYC Rejected'), ('KYC_FLAGGED', 'KYC Flagged'), ('WITHDRAWAL_REQUESTED', 'Withdrawal Requested'), ('WITHDRAWAL_CONFIRMED', 'Withdrawal Confirmed'), ('WITHDRAWAL_FAILED', 'Withdrawal Failed'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('APPEAL_SUBMITTED', 'Appeal Submitted'), ('APPEAL_APPROVED', 'Appeal Approved'), ('APPEAL_REJECTED', 'Appeal Rejected'), ('MFA_ENABLED', 'MFA Enabled'), ('MFA_DISABLED', 'MFA Disabled'), ('MFA_CHALLENGE_FAILED', 'MFA Challenge Failed'), ('MFA_RECOVERY_CODE_USED', 'MFA Recovery Code Used'), ('MFA_RECOVERY_CODES_REGENERATED', 'MFA Recovery Codes Regenerated'), ('MFA_RESET_BY_ADMIN', 'MFA Reset By Admin'), ('BANK_ACCOUNT_ADDED', 'Bank Account Added'), ('BANK_ACCOUNT_DELETED', 'Bank Account Deleted'), ('BANK_ACCOUNT_UPDATED', 'Bank Account Updated'), ('BADGE_CREATED', 'Badge Created'), ('BADGE_UPDATED', 'Badge Updated'), ('BADGE_DELETED', 'Badge Deleted'), ('BADGE_AWARDED', 'Badge Awarded'), ('BADGE_REVOKED', 'Badge Revoked'), ('ROLE_CREATED', 'Role Created'), ('ROLE_UPDATED', 'Role Updated'), ('ROLE_DELETED', 'Role Deleted'), ('STAFF_ROLE_CHANGED', 'Staff Role Changed'), ('PASSWORD_RESET_SENT_BY_ADMIN', 'Password Reset Sent By Admin'), ('ACCOUNT_ERASED', 'Account Erased'), ('COURSE_VERSION_MIGRATED', 'Course Version Migrated'), ('WALLET_ADJUSTED', 'Wallet Adjusted')], help_text='Specific activity action.', max_length=80, verbose_name='Action'),
        ),
    ]
