# Generated by Django 5.2.14 on 2026-09-30 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_alter_useractivitylog_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mfa_grace_period_ends_at",
        ),
    ]
