# Generated by Django 5.2.14 on 2026-09-16 22:41

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('name', models.CharField(help_text='Role name shown on the Roles & Permissions screen.', max_length=60, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', help_text='Optional note on what the role is for.', verbose_name='Description')),
                ('base_role', models.CharField(choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('STAFF_WRITER', 'Writer'), ('STAFF_VERIFIER', 'Verifier'), ('STAFF_APPROVER', 'Approver'), ('AI_REVIEWER', 'AI Reviewer'), ('QA_REVIEWER', 'QA Reviewer'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], help_text='The built-in role whose workflow behaviour members follow. Fixed once the role exists.', max_length=20, verbose_name='Base role')),
                ('system_key', models.CharField(blank=True, choices=[('COURSE_CREATOR', 'Course Creator'), ('CREATOR_REVIEWER', 'Creator Reviewer'), ('STAFF_WRITER', 'Writer'), ('STAFF_VERIFIER', 'Verifier'), ('STAFF_APPROVER', 'Approver'), ('AI_REVIEWER', 'AI Reviewer'), ('QA_REVIEWER', 'QA Reviewer'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], help_text='Set only on built-in roles: the UserRole this row represents.', max_length=20, null=True, verbose_name='System key')),
                ('version', models.PositiveIntegerField(default=1, help_text="Bumped whenever the role's permissions change, so cached permission sets keyed by it expire immediately.", verbose_name='Version')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who updated the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('codename', models.CharField(help_text="Permission codename, e.g. 'courses.approve'.", max_length=64, verbose_name='Codename')),
                ('role', models.ForeignKey(help_text='The role holding this permission.', on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='authorization.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role permission',
                'verbose_name_plural': 'Role permissions',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['base_role', 'is_deleted'], name='role_base_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('system_key',), name='role_unique_system_key'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_deleted', False)), name='role_unique_live_name'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(('system_key__isnull', True), ('system_key', models.F('base_role')), _connector='OR'), name='role_system_key_is_base_role'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['codename', 'role'], name='role_permission_codename_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'codename'), name='role_permission_unique'),
        ),
    ]
