# Generated by Django 5.2.14 on 2026-09-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_seed_system_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='version',
        ),
    ]
