# Generated by Django 5.2.14 on 2026-07-23 13:13

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('minimum_withdrawal_threshold', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Minimum amount a creator can request as a withdrawal.', max_digits=10, verbose_name='Minimum Withdrawal Threshold')),
                ('course_module_count_min', models.PositiveIntegerField(default=4, verbose_name='Course Module Count Min')),
                ('course_module_count_max', models.PositiveIntegerField(default=12, verbose_name='Course Module Count Max')),
                ('course_lessons_per_module_min', models.PositiveIntegerField(default=3, verbose_name='Course Lessons Per Module Min')),
                ('course_lessons_per_module_max', models.PositiveIntegerField(default=8, verbose_name='Course Lessons Per Module Max')),
                ('course_learning_objectives_min', models.PositiveIntegerField(default=2, verbose_name='Course Learning Objectives Min')),
                ('course_learning_objectives_max', models.PositiveIntegerField(default=5, verbose_name='Course Learning Objectives Max')),
                ('course_description_word_min', models.PositiveIntegerField(default=100, verbose_name='Course Description Word Min')),
                ('course_description_word_max', models.PositiveIntegerField(default=500, verbose_name='Course Description Word Max')),
                ('lesson_script_word_min', models.PositiveIntegerField(default=500, verbose_name='Lesson Script Word Min')),
                ('lesson_script_word_max', models.PositiveIntegerField(default=1500, verbose_name='Lesson Script Word Max')),
                ('lesson_quiz_questions_min', models.PositiveIntegerField(default=3, verbose_name='Lesson Quiz Questions Min')),
                ('lesson_quiz_questions_max', models.PositiveIntegerField(default=5, verbose_name='Lesson Quiz Questions Max')),
                ('course_duration_min_minutes', models.PositiveIntegerField(default=120, verbose_name='Course Duration Min Minutes')),
                ('course_duration_max_minutes', models.PositiveIntegerField(default=480, verbose_name='Course Duration Max Minutes')),
                ('course_final_assessment_min_questions', models.PositiveIntegerField(default=15, verbose_name='Course Final Assessment Min Questions')),
                ('topic_reservation_expiry_days', models.PositiveIntegerField(default=30, help_text='How long an approved topic reservation lasts (BR-007).', verbose_name='Topic Reservation Expiry Days')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
