# Generated by Django 5.2.14 on 2026-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="sla_amber_threshold_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Hours since submission before a queued course is flagged amber. Platform-wide default; a reviewer may override it for themselves via NotificationPreference.",
                verbose_name="SLA Amber Threshold Hours",
            ),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="sla_red_threshold_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="Hours since submission before a queued course is flagged red/critical. Platform-wide default; a reviewer may override it for themselves via NotificationPreference.",
                verbose_name="SLA Red Threshold Hours",
            ),
        ),
    ]
