# Generated by Django 5.2.14 on 2026-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0002_platformsettings_sla_amber_threshold_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="mfa_enrollment_grace_period_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="How many days an Admin/Super Admin may keep logging in without MFA enrolled before enforcement on sensitive actions kicks in. The clock starts once, at role assignment - not reset by re-saving this setting.",
                verbose_name="MFA Enrollment Grace Period Days",
            ),
        ),
    ]
