# Generated by Django 5.2.14 on 2026-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_platformsettings_mfa_enrollment_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='payment_processor',
            field=models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave'), ('PAYSTACK', 'Paystack')], default='FLUTTERWAVE', help_text='Which payment processor to use for creator payouts.', max_length=20, verbose_name='Payment Processor'),
        ),
    ]
