# Generated by Django 5.2.14 on 2026-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_platformsettings_mfa_enrollment_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='creator_agreement_policy_version',
            field=models.CharField(default='1.0', help_text='Current version of the creator agreement/NDA. Bumping this requires creators who already completed onboarding to re-accept before they can create new courses.', max_length=10, verbose_name='Creator Agreement Policy Version'),
        ),
    ]
