# Generated by Django 5.2.14 on 2026-09-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0004_platformsettings_payment_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='kyc_provider',
            field=models.CharField(choices=[('SISSL', 'SISSL'), ('YOUVERIFY', 'YouVerify')], default='YOUVERIFY', help_text='Which KYC service provider to use for identity verification.', max_length=20, verbose_name='KYC service provider'),
        ),
    ]
