# Generated by Django 5.2.14 on 2026-09-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0005_platformsettings_kyc_provider'),
        ('platform', '0005_separate_course_and_lesson_objective_limits'),
    ]

    operations = [
    ]
