# Generated by Django 5.2.14 on 2026-09-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0006_merge_20260903_1429'),
        ('platform', '0006_remove_lesson_quiz_question_thresholds'),
    ]

    operations = [
    ]
