# Generated by Django 5.2.14 on 2026-09-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0007_merge_20260907_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='kyc_provider',
            field=models.CharField(choices=[('YOUVERIFY', 'YouVerify')], default='YOUVERIFY', help_text='Which KYC service provider to use for identity verification.', max_length=20, verbose_name='KYC service provider'),
        ),
    ]
