# Generated by Django 5.2.14 on 2026-09-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0008_alter_platformsettings_kyc_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='kyc_provider',
            field=models.CharField(choices=[('SISSL', 'SISSL')], default='SISSL', help_text='Which KYC service provider to use for identity verification.', max_length=20, verbose_name='KYC service provider'),
        ),
    ]
