# Generated by Django 5.2.14 on 2026-09-12 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_migrate_legacy_kyc_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='liveness_threshold',
            field=models.PositiveSmallIntegerField(default=80, help_text="Score (0 - 100) at or above which a 'real' liveness result passes", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Liveness Threshold'),
            preserve_default=False,
        ),
    ]
