# Generated by Django 5.2.14 on 2026-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0012_alter_platformsettings_liveness_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='auto_flag_after_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours a course may await a review decision before it is flagged for admin attention. The flag is advisory - it blocks nothing - and clears when the course next enters a review cycle. 0 disables flagging.', verbose_name='Auto Flag After Hours'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='draft_minimum_hold_hours',
            field=models.PositiveIntegerField(default=48, help_text='Hours a course must exist as a draft before its creator may submit it. Counted from when the course was first created and never reset, so a course returned for revision can be resubmitted at once. 0 disables the rule.', verbose_name='Draft Minimum Hold Hours'),
        ),
    ]
