# Generated by Django 5.2.14 on 2026-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0012_alter_platformsettings_liveness_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='payment_processor',
            field=models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave')], default='FLUTTERWAVE', help_text='Which payment processor to use for creator payouts.', max_length=20, verbose_name='Payment Processor'),
        ),
    ]
