# Generated by Django 5.2.14 on 2026-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0013_alter_platformsettings_payment_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='auto_credit_duration_hours',
            field=models.PositiveIntegerField(default=24, help_text="Number of hours after course approval before the creator's wallet is credited.", verbose_name='Auto Credit Duration Hours'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='withdrawal_require_verification',
            field=models.BooleanField(default=True, help_text='Whether creators must complete identity verification before making withdrawals.', verbose_name='Withdrawal Requires Verification'),
        ),
    ]
