# Generated by Django 5.2.14 on 2026-09-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0014_allow_more_course_learning_objectives'),
        ('platform', '0014_platformsettings_auto_credit_duration_hours_and_more'),
    ]

    operations = [
    ]
