# Generated by Django 5.2.14 on 2026-09-30 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0016_merge_20260921_1115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformsettings",
            name="mfa_enrollment_grace_period_days",
        ),
    ]
