# Generated by Django 5.2.14 on 2026-10-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0017_remove_platformsettings_mfa_enrollment_grace_period_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="staged_review_flow_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Switches course review to the staged flow: courses are submitted as text only, the first seat reviews the text, the video is attached afterwards and reviewed at the second seat, and a rejection returns the course to Needs Revision and resumes at the rejecting seat. Only the Approver may price and publish. Off keeps the original single-pass review. Cannot be changed while any course is in review.",
                verbose_name="Staged Review Flow Enabled",
            ),
        ),
    ]
