# Generated by Django 5.2.14 on 2026-10-09 16:59

from decimal import Decimal
from django.db import migrations, models

OLD_MIN_MINUTES = 120
NEW_MIN_MINUTES = 30


def lower_course_minimum(apps, schema_editor):
    """Courses may now be as short as 30 minutes. Only a row still on the old
    default moves; a minimum an admin chose is left alone."""

    apps.get_model("platform", "PlatformSettings").objects.filter(
        course_duration_min_minutes=OLD_MIN_MINUTES
    ).update(course_duration_min_minutes=NEW_MIN_MINUTES)


def restore_course_minimum(apps, schema_editor):
    apps.get_model("platform", "PlatformSettings").objects.filter(
        course_duration_min_minutes=NEW_MIN_MINUTES
    ).update(course_duration_min_minutes=OLD_MIN_MINUTES)



class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_platformsettings_staged_review_flow_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='production_course_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Most the Production Engine may spend producing one course, in USD. A run whose quote is higher is blocked before any spend, and a run stops if its actual spend reaches it.', max_digits=10, verbose_name='Production Budget Per Course'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='production_enabled',
            field=models.BooleanField(default=False, help_text='Kill switch for the Production Engine. Off: runs are still created and quoted for courses waiting on engine-made video, but none starts and a running one stops before its next step.', verbose_name='Production Engine Enabled'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='course_duration_max_minutes',
            field=models.PositiveIntegerField(default=480, help_text='Longest total runtime, in minutes, a course may have. There is no hard ceiling: an admin may raise it to any length.', verbose_name='Course Duration Max Minutes'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='course_duration_min_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Shortest total runtime, in minutes, a course may have.', verbose_name='Course Duration Min Minutes'),
        ),
        migrations.RunPython(lower_course_minimum, restore_course_minimum),
    ]
