# Generated by Django 5.2.14 on 2026-10-09 21:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0019_production_settings_and_shorter_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='production_max_av_drift_ms',
            field=models.PositiveIntegerField(default=100, help_text='Largest gap between the audio and video track lengths of a produced lesson, in milliseconds.', verbose_name='Production Maximum A/V Drift (ms)'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='production_min_caption_accuracy',
            field=models.DecimalField(decimal_places=2, default=Decimal('95.00'), help_text='Lowest caption accuracy (percent of words a transcription of the finished audio gets right against the approved script) a produced lesson may have before it goes to review.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Production Minimum Caption Accuracy'),
        ),
    ]
