# Generated by Django 5.2.14 on 2026-10-10 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0020_production_quality_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='production_broll_per_lesson',
            field=models.PositiveSmallIntegerField(default=0, help_text='Most AI motion clips (8 s, faceless) a produced lesson may use in place of a still scene. 0 turns b-roll off. Each clip costs about $1.20 and is included in the quote.', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Production B-roll Clips Per Lesson'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='production_visual_check_enabled',
            field=models.BooleanField(default=True, help_text='Have a vision model look at a frame of every scene of a produced lesson (text legible and spelled right, nothing cut off, no people or faces) before it goes to review. About a cent per lesson.', verbose_name='Production Visual Check'),
        ),
    ]
