# Generated by Tses 2026-07-12T18:57:00Z
# Generated by Django 5.2.14 on 2026-07-12 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('primary_expertise_other', models.CharField(blank=True, default='', help_text="Free-text expertise when 'Others (Specify)' is chosen instead of a category.", max_length=255, verbose_name='Primary Expertise (Other)')),
                ('video_comfort_level', models.CharField(blank=True, choices=[('NEEDS_GUIDANCE', "Not comfortable, I'll need guidance"), ('SOMEWHAT_COMFORTABLE', "Somewhat comfortable, I've recorded a few videos"), ('VERY_COMFORTABLE', 'Very comfortable, I produce video regularly'), ('PREFERS_TEXT_AUDIO', 'I prefer text-based or audio content')], default='', help_text='Self-reported comfort producing video content.', max_length=30, verbose_name='Video Comfort Level')),
                ('monthly_course_capacity', models.CharField(blank=True, choices=[('ONE', '1 course'), ('TWO_TO_THREE', '2-3 courses'), ('FOUR_TO_FIVE', '4-5 courses'), ('MORE_THAN_FIVE', 'More than 5 courses')], default='', help_text='Self-estimated number of courses producible per month.', max_length=20, verbose_name='Monthly Course Capacity')),
                ('agreement_accepted_at', models.DateTimeField(blank=True, help_text='When the creator accepted the account-level NDA / content-ownership agreement.', null=True, verbose_name='Agreement Accepted At')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, help_text='Set when the final onboarding step (agreement) is submitted.', null=True, verbose_name='Onboarding Completed At')),
                ('primary_expertise_category', models.ForeignKey(blank=True, help_text='Primary area-of-expertise category selected during onboarding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.category', verbose_name='Primary Expertise Category')),
                ('user', models.OneToOneField(help_text='User this onboarding profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Creator Profile',
                'verbose_name_plural': 'Creator Profiles',
                'indexes': [models.Index(fields=['onboarding_completed_at'], name='creatorprofile_completed_idx')],
            },
        ),
    ]
