# Generated by Django 5.2.14 on 2026-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='primary_expertise_category',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='primary_expertise_area',
            field=models.CharField(blank=True, choices=[('WEB_DEVELOPMENT', 'Web Development'), ('DATA_SCIENCE_ANALYTICS', 'Data Science & Analytics'), ('AI_MACHINE_LEARNING', 'AI & Machine Learning'), ('BUSINESS_MANAGEMENT', 'Business & Management'), ('DIGITAL_MARKETING', 'Digital Marketing'), ('LEADERSHIP_SOFT_SKILLS', 'Leadership & Soft Skills'), ('FINANCE_ACCOUNTING', 'Finance & Accounting'), ('OTHERS', 'Others (Specify)')], default='', help_text='Primary area-of-expertise selected during onboarding.', max_length=30, verbose_name='Primary Expertise Area'),
        ),
    ]
