# Generated by Django 5.2.14 on 2026-07-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding",
            "0002_remove_creatorprofile_primary_expertise_category_and_more",
        ),
        ("onboarding", "0002_repoint_category_fk"),
    ]

    operations = []
