# Generated by Django 5.2.14 on 2026-07-20 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_rename_category_table"),
        ("onboarding", "0003_merge_20260720_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatorprofile",
            name="primary_expertise_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary area-of-expertise category selected during onboarding.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="categories.category",
                verbose_name="Primary Expertise Category",
            ),
        ),
    ]
