# Generated by Django 5.2.14 on 2026-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_creatorprofile_primary_expertise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='agreement_accepted_version',
            field=models.CharField(blank=True, help_text="Policy version the creator accepted, for comparison against the platform's current creator_agreement_policy_version.", max_length=10, null=True, verbose_name='Agreement Accepted Version'),
        ),
    ]
