# Generated by Django 5.2.14 on 2026-08-25 14:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_sissl_config(apps, schema_editor):
    from shared.constants.kyc import (
    SISSL_FACE_MATCH_THRESHOLD,
    SISSL_FLAGGING_FLOOR,
    SISSL_HTTP_TIMEOUT,
    SISSL_LIVENESS_THRESHOLD,
)
    try:
        #Using the full import, instead of apps.get_model, to avoid issues with migrations and model state(ensuring that SISSLConfiguration.SINGLETON_KEY is accessible).
        from api.sissl_verification.models import SISSLConfiguration
        _, _ = SISSLConfiguration.objects.update_or_create(
                    singleton_key=SISSLConfiguration.SINGLETON_KEY,
                    defaults={
                        "face_match_threshold": SISSL_FACE_MATCH_THRESHOLD,
                        "flagging_floor": SISSL_FLAGGING_FLOOR,
                        "liveness_threshold": SISSL_LIVENESS_THRESHOLD,
                        "retry_max_attempts": 3,
                        "http_timeout_seconds": SISSL_HTTP_TIMEOUT,
                    },
                )
    except Exception as e:
        print(f"Error seeding SISSL configuration: {e}")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SISSLConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('singleton_key', models.CharField(default='sissl', editable=False, help_text='Internal — do not edit. Enforces singleton (one row only).', max_length=16, unique=True)),
                ('face_match_threshold', models.PositiveSmallIntegerField(help_text='Score (0 - 100) at or above which a face comparison passes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flagging_floor', models.PositiveSmallIntegerField(help_text='Score floor for flagging — below this, the comparison hard-fails', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('liveness_threshold', models.PositiveSmallIntegerField(help_text="Score (0 - 100) at or above which a 'real' liveness result passes", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('retry_max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Max provider retry attempts on transient 5xx (502/503/504)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('http_timeout_seconds', models.PositiveSmallIntegerField(default=30, help_text='Hard timeout per SISSL HTTP call, in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
            ],
            options={
                'verbose_name': 'SISSL Configuration',
                'verbose_name_plural': 'SISSL Configuration',
                'db_table': 'sissl_configurations',
            },
        ),
        migrations.CreateModel(
            name='SISSLLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('kind', models.CharField(choices=[('liveness', 'Liveness'), ('bvn', 'BVN lookup'), ('nin', 'NIN lookup')], db_index=True, help_text='Which SISSL endpoint produced this row', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], db_index=True, help_text='Outcome of the HTTP call (not the verification outcome)', max_length=10)),
                ('request_summary', models.JSONField(blank=True, default=dict, help_text='Redacted summary of the request — presence flags only, NO raw PII')),
                ('response_summary', models.JSONField(blank=True, default=dict, help_text='Redacted summary of the response — scores/statuses only, NO raw PII')),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='HTTP round-trip latency in milliseconds')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message — populated only when status=error')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Per-call cost — populated from billing rules or reconciled against vendor invoice', max_digits=10, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user this SISSL call was made on behalf of (nullable for system calls)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sissl_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SISSL Log',
                'verbose_name_plural': 'SISSL Logs',
                'db_table': 'sissl_logs',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['kind', '-created_datetime'], name='sissl_logs_kind_4c1bf8_idx'), models.Index(fields=['user', '-created_datetime'], name='sissl_logs_user_id_09b735_idx'), models.Index(fields=['status', '-created_datetime'], name='sissl_logs_status_9f9b27_idx')],
            },
        ),
        migrations.RunPython(seed_sissl_config, migrations.RunPython.noop),
    ]
