# Generated by Tses 2026-07-09T12:37:38Z
"""Celery application bootstrap for asynchronous tasks and schedules."""

import os

from celery import Celery


os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

app = Celery("config")
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()

# `shared` is a plain Python package (not a Django app), so
# autodiscover_tasks() above never finds shared/tasks.py.  Importing it
# here forces every worker to register the @shared_task functions
# (send_templated_email_task, send_email_task, write_audit_log, …).
import shared.tasks  # noqa: F401, E402


@app.task(bind=True)
def debug_task(self):
    """Print the current task request for quick local debugging."""

    print(f"Request: {self.request!r}")
