# Generated by Django 5.2.14 on 2026-08-20 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("COLLABORATOR", "Collaborator"), ("ADMIN", "Admin")],
                        default="COLLABORATOR",
                        help_text="This collaborator's access level on the course.",
                        max_length=15,
                        verbose_name="Role",
                    ),
                ),
                (
                    "assigned_modules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modules this collaborator may view/edit (SCCS PRD Section 14: 'collaborators receive access to only their assigned modules'). Ignored for ADMIN-role collaborators, who get full-course access regardless of what's assigned here.",
                        related_name="assigned_collaborators",
                        to="courses.module",
                        verbose_name="Assigned Modules",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this collaborator has access to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who invited this collaborator.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The collaborating user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_collaborations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Collaborator",
                "verbose_name_plural": "Course Collaborators",
                "ordering": ["-created_datetime"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "user"), name="unique_collaborator_per_course"
                    )
                ],
            },
        ),
    ]
