# Generated by Django 5.2.14 on 2026-08-21 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0001_initial"),
        ("courses", "0003_delete_reviewaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The invited person's email. May not belong to a User account yet; they must sign up with this email to accept.",
                        max_length=254,
                        verbose_name="Invitee Email",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("COLLABORATOR", "Collaborator"), ("ADMIN", "Admin")],
                        default="COLLABORATOR",
                        help_text="Access level granted on acceptance.",
                        max_length=15,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        help_text="Where this invite sits in its lifecycle.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        help_text="Opaque identifier used in notification deep-links.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="After this moment a PENDING invite can no longer be accepted.",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitee accepted or declined, if they did.",
                        null=True,
                        verbose_name="Responded At",
                    ),
                ),
                (
                    "assigned_modules",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modules the invitee will be restricted to if they accept as a plain COLLABORATOR. Ignored for ADMIN-role invites.",
                        related_name="invites",
                        to="courses.module",
                        verbose_name="Assigned Modules",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course this invite grants access to when accepted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborator_invites",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent this invite.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collaborator_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborator Invite",
                "verbose_name_plural": "Collaborator Invites",
                "ordering": ["-created_datetime"],
                "indexes": [models.Index(fields=["email"], name="invite_email_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("course", "email"),
                        name="unique_pending_invite_per_course_email",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("responded_at__isnull", False),
                            ("status", "PENDING"),
                            _negated=True,
                        ),
                        name="pending_invite_has_no_response",
                    ),
                ],
            },
        ),
    ]
