# Generated by Django 5.2.14 on 2026-08-22 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0002_collaboratorinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        help_text="Email the invite was sent to; unique per workspace.",
                        max_length=254,
                        verbose_name="Invited Email",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("AUTHOR", "Author"),
                            ("COLLABORATOR", "Collaborator"),
                        ],
                        default="COLLABORATOR",
                        help_text="Platform-wide role within this workspace.",
                        max_length=15,
                        verbose_name="Role",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional demographic field shown on the roster.",
                        max_length=10,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional demographic field shown on the roster.",
                        max_length=100,
                        verbose_name="Country of Origin",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("REMOVED", "Removed"),
                        ],
                        default="PENDING",
                        help_text="Invite/membership lifecycle state.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "removed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this person was removed from the workspace.",
                        null=True,
                        verbose_name="Removed At",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The workspace/creator account this person belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_collaborators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The linked account once the invite is accepted; null until then.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workspace_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Collaborator",
                "verbose_name_plural": "Workspace Collaborators",
                "ordering": ["-created_datetime"],
                "indexes": [
                    models.Index(fields=["owner"], name="workspace_collab_owner_idx"),
                    models.Index(fields=["role"], name="workspace_collab_role_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "invited_email"),
                        name="unique_workspace_member_per_email",
                    )
                ],
            },
        ),
    ]
