# Generated by Django 5.2.14 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0002_rename_coursecollaborator_table"),
        ("courses", "0009_course_duration_estimate_minutes_course_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecollaborator",
            name="assigned_modules",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modules this collaborator may view/edit (SCCS PRD Section 14: 'collaborators receive access to only their assigned modules'). Ignored for ADMIN-role collaborators, who get full-course access regardless of what's assigned here.",
                related_name="assigned_collaborators",
                to="courses.module",
                verbose_name="Assigned Modules",
            ),
        ),
    ]
