# Generated by Tses 2026-07-09T12:37:38Z
from drf_standardized_errors.formatter import ExceptionFormatter
from drf_standardized_errors.types import ErrorResponse


class TsesExceptionFormatter(ExceptionFormatter):
    """Normalize DRF errors into the scaffold response contract.

    Projects can subclass this formatter if they want to add extra keys, change
    message wording, or align errors with a different API contract later.
    """

    def format_error_response(self, error_response: ErrorResponse):
        """Convert standardized DRF errors into a simplified list payload."""

        errors = []
        for error in error_response.errors:
            errors.append(
                {
                    "type": error_response.type,
                    "code": error.code,
                    "message": error.detail,
                    "field_name": error.attr,
                }
            )
        return {"errors": errors}
