# Generated by Tses 2026-07-09T12:37:38Z
from collections import OrderedDict

from django.core.paginator import InvalidPage
from rest_framework.exceptions import NotFound
from rest_framework.pagination import CursorPagination, PageNumberPagination
from rest_framework.response import Response


class PageNumberAPIPagination(PageNumberPagination):
    """Return page-number pagination in the scaffold response envelope.

    Use this as the default pagination class when you want paginated responses to
    match the project-wide `status/message/data` shape. Teams can subclass it to
    change query parameter names, response wording, or pagination metadata.
    """

    page_size_query_param = "size"

    def paginate_queryset(self, queryset, request, view=None):
        self.request = request
        page_size = self.get_page_size(request)
        if not page_size:
            return None

        paginator = self.django_paginator_class(queryset, page_size)
        page_number = self.get_page_number(request, paginator)

        if self._has_search_param(request) and paginator.count == 0:
            self.page = paginator.page(1)
            return []

        try:
            self.page = paginator.page(page_number)
        except InvalidPage as exc:
            msg = self.invalid_page_message.format(
                page_number=page_number, message=str(exc)
            )
            raise NotFound(msg)

        if paginator.num_pages > 1 and self.template is not None:
            self.display_page_controls = True

        return list(self.page)

    @staticmethod
    def _has_search_param(request):
        """Treat empty search result pages as valid when a search filter is used."""

        search_term = request.query_params.get("search")
        return bool(search_term and str(search_term).strip())

    def get_paginated_response(self, data):
        """Wrap paginated data in the scaffold API response structure."""

        pagination_data = OrderedDict(
            [
                ("count", self.page.paginator.count),
                ("page", self.page.number),
                ("page_size", self.page.paginator.per_page),
                ("total_pages", self.page.paginator.num_pages),
                ("next", self.get_next_link()),
                ("next_page_number", self.__get_next_page_number()),
                ("previous", self.get_previous_link()),
                ("previous_page_number", self.__get_previous_page_number()),
            ]
        )
        data_dict = OrderedDict(
            [
                ("paginator", pagination_data),
                ("results", data),
            ]
        )
        return Response(
            OrderedDict(
                [
                    ("status", True),
                    ("message", "Successfully retrieved data"),
                    ("data", data_dict),
                ]
            )
        )

    def __get_next_page_number(self):
        return self.page.next_page_number() if self.page.has_next() else None

    def __get_previous_page_number(self):
        return self.page.previous_page_number() if self.page.has_previous() else None

    def get_paginated_response_schema(self, schema):
        """Describe the custom pagination envelope for schema generation tools."""

        return {
            "type": "object",
            "properties": {
                "status": {"type": "boolean", "example": True},
                "message": {"type": "string", "example": "Successfully retrieved data"},
                "data": {
                    "type": "object",
                    "properties": {
                        "paginator": {
                            "type": "object",
                            "properties": {
                                "count": {
                                    "type": "integer",
                                    "example": 123,
                                },
                                "page": {"type": "integer", "example": 1},
                                "page_size": {"type": "integer", "example": 10},
                                "total_pages": {"type": "integer", "example": 123},
                                "next_page_number": {
                                    "type": "integer",
                                    "nullable": True,
                                    "example": 4,
                                },
                                "next": {
                                    "type": "string",
                                    "nullable": True,
                                    "format": "uri",
                                    "example": "http://api.example.org/accounts/?{page_query_param}=4".format(
                                        page_query_param=self.page_query_param
                                    ),
                                },
                                "previous": {
                                    "type": "string",
                                    "nullable": True,
                                    "format": "uri",
                                    "example": "http://api.example.org/accounts/?{page_query_param}=2".format(
                                        page_query_param=self.page_query_param
                                    ),
                                },
                                "previous_page_number": {
                                    "type": "integer",
                                    "nullable": True,
                                    "example": 2,
                                },
                            },
                        },
                        "results": schema,
                    },
                },
            },
        }


class CursorAPIPagination(CursorPagination):
    """Return cursor pagination in the scaffold response envelope.

    Prefer this when stable cursor-based pagination is a better fit than numbered
    pages. Projects can override the response body or cursor settings by
    subclassing this helper in their own apps.
    """

    page_size_query_param = "size"

    def get_paginated_response(self, data):
        """Wrap cursor pagination metadata in the scaffold API response shape."""

        super(CursorAPIPagination, self).get_paginated_response(data)
        pagination_data = OrderedDict(
            [
                ("next", self.get_next_link()),
                ("previous", self.get_previous_link()),
            ]
        )
        data_dict = OrderedDict(
            [
                ("paginator", pagination_data),
                ("results", data),
            ]
        )
        return Response(
            OrderedDict(
                [
                    ("status", True),
                    ("message", "Successfully retrieved data"),
                    ("data", data_dict),
                ]
            )
        )

    def get_paginated_response_schema(self, schema):
        """Describe the cursor pagination envelope for schema generation tools."""

        return {
            "type": "object",
            "properties": {
                "status": {"type": "boolean", "example": True},
                "message": {"type": "string", "example": "Successfully retrieved data"},
                "data": {
                    "type": "object",
                    "properties": {
                        "paginator": {
                            "type": "object",
                            "properties": {
                                "next": {
                                    "type": "string",
                                    "nullable": True,
                                    "format": "uri",
                                    "example": "http://api.example.org/accounts/?{page_query_param}=4".format(
                                        page_query_param=self.page_size_query_param
                                    ),
                                },
                                "previous": {
                                    "type": "string",
                                    "nullable": True,
                                    "format": "uri",
                                    "example": "http://api.example.org/accounts/?{page_query_param}=2".format(
                                        page_query_param=self.page_size_query_param
                                    ),
                                },
                            },
                        },
                        "results": schema,
                    },
                },
            },
        }
