# Generated by Django 5.2.14 on 2026-08-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('Local Account', 'Local Account'), ('Mobile Money', 'Mobile Money')], default='Local Account', help_text='Whether this is a local bank account or a mobile money account.', max_length=15, verbose_name='Account Type'),
        ),
    ]
