# Generated by Django 5.2.14 on 2026-08-06 20:13

import uuid
from decimal import Decimal
from django.db import migrations, models


LEDGER_DATA = [
    {"name": "Paystack Transfer", "code_name": "paystack_transfer"},
    {"name": "General Ledger", "code_name": "general"},
    {"name": "Suspense Ledger", "code_name": "suspense"},
]


def seed_internal_accounts(apps, schema_editor):
    InternalAccount = apps.get_model('payments', 'InternalAccount')

    for ledger in LEDGER_DATA:
        InternalAccount.objects.get_or_create(
            code_name=ledger['code_name'],
            defaults={
                'name': ledger['name'],
                'currency': 'NGN',
            },
        )

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bankaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('name', models.CharField(help_text="Name of the internal ledger (e.g., 'Feexeet Subscription Revenue', 'Labour Fees Ledger', etc.)", max_length=50, unique=True)),
                ('code_name', models.CharField(help_text="A short unique code name for the internal ledger (e.g., 'subscription', 'labour', etc.) that can be used in code to reference the ledger without relying on the human-readable name. This allows for safer code references that won't break if the 'name' field is updated for clarity or rebranding purposes.", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('last_withdrawal_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of last withdrawal', null=True)),
                ('last_deposit_timestamp', models.DateTimeField(blank=True, help_text='Timestamp of last deposit', null=True)),
                ('currency', models.CharField(choices=[('NGN', 'NGN')], max_length=10)),
            ],
            options={
                'db_table': 'internal_account',
            },
        ),
        migrations.RunPython(seed_internal_accounts, migrations.RunPython.noop),
    ]
