# Generated by Django 5.2.14 on 2026-08-07 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0009_course_duration_estimate_minutes_course_version_and_more'),
        ('payments', '0003_internalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, help_text='datetime of object creation', verbose_name='Created datetime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, help_text='datetime of object update', verbose_name='Updated datetime')),
                ('deleted_datetime', models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted')),
                ('reference', models.CharField(help_text='This is non-unique, so the same reference can be associated with related transactions (e.g. a debit and credit pair).', max_length=32, verbose_name='Reference')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Absolute transaction amount, always positive.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged for this transaction, if any.', max_digits=12, verbose_name='Fee')),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Whether this transaction credits or debits the wallet.', max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Settlement status of the transaction.', max_length=10, verbose_name='Status')),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of the transaction.', max_length=255, verbose_name='Description')),
                ('recipient_account_name', models.CharField(blank=True, default='', help_text="Snapshot of the payout account's holder name at transaction time, so the receipt stays accurate if the account is later edited/removed.", max_length=150, verbose_name='Recipient Account Name')),
                ('recipient_account_number', models.CharField(blank=True, default='', help_text='Snapshot of the payout account number at transaction time.', max_length=34, verbose_name='Recipient Account Number')),
                ('recipient_provider_name', models.CharField(blank=True, default='', help_text='Snapshot of the bank/mobile-money provider at transaction time.', max_length=100, verbose_name='Recipient Provider Name')),
                ('wallet_id', models.UUIDField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course this transaction is associated with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='courses.course', verbose_name='Course')),
                ('payout_account', models.ForeignKey(blank=True, help_text='Payout account this withdrawal was sent to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.bankaccount', verbose_name='Payout Account')),
                ('wallet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_datetime'],
                'indexes': [models.Index(fields=['wallet_type', 'wallet_id', '-created_datetime'], name='txn_wallet_cdt_idx'), models.Index(fields=['status'], name='txn_status_idx2')],
            },
        ),
    ]
