# Generated by Django 5.2.14 on 2026-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient_account_number',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the payout account number at transaction time.', max_length=255, verbose_name='Recipient Account Number'),
        ),
    ]
