# Generated by Django 5.2.14 on 2026-08-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_transaction_recipient_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='flutterwave_recipient_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
