# Generated by Django 5.2.14 on 2026-08-17 20:42

from django.db import migrations
import logging

logger = logging.getLogger(__name__)



FLUTTER = {"name": "Flutterwave Transfer", "code_name": "flutterwave_transfer"}



def _create_flutterwave_internal_account(apps, schema_editor):
    InternalAccount = apps.get_model('payments', 'InternalAccount')

    try:
        InternalAccount.objects.get_or_create(
            code_name=FLUTTER['code_name'],
            defaults={
                'name': FLUTTER['name'],
                'currency': 'NGN',
            },
        )
    except Exception as exc:
        logger.warning(f"Failed to seed Flutterwave transfer account: {exc}")
        
        




class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_bankaccount_flutterwave_recipient_code'),
    ]

    operations = [
        migrations.RunPython(_create_flutterwave_internal_account, migrations.RunPython.noop),
    ]
