# Generated by Django 5.2.14 on 2026-09-18 08:53

from django.db import migrations


def seed_course_payment_internal_account(apps, schema_editor):
    InternalAccount = apps.get_model('payments', 'InternalAccount')
    try:
        InternalAccount.objects.get_or_create(
            code_name="course_payment",
            defaults={
                'name': "Course Payment Account",
                'currency': 'NGN',
            },
        )
    except Exception as e:
        print(f"Error occurred while seeding course payment internal account: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_seed_adjustments_internal_account'),
    ]

    operations = [
        migrations.RunPython(seed_course_payment_internal_account, migrations.RunPython.noop),
    ]
