# Generated by Django 5.2.14 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20260918_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(help_text='This is non-unique, so the same reference can be associated with related transactions (e.g. a debit and credit pair).', max_length=100, verbose_name='Reference'),
        ),
    ]
