#!/bin/sh
# Generated by Tses 2026-07-09T12:37:38Z
set -e

python manage.py check

if [ "${DJANGO_RUN_MIGRATIONS:-1}" = "1" ]; then
    python manage.py migrate --noinput
fi

if [ "${DJANGO_COLLECTSTATIC:-1}" = "1" ]; then
    python manage.py collectstatic --noinput
fi

exec "$@"
