#!/bin/sh
# Generated by Tses 2026-07-09T12:37:38Z
set -e

# Ensure write directories exist with correct ownership (runs as root)
mkdir -p /app/staticfiles /app/media
if [ "$(id -u)" = "0" ]; then
    chown appuser:appuser /app/staticfiles /app/media
fi

python manage.py check

if [ "${DJANGO_RUN_MIGRATIONS:-1}" = "1" ]; then
    python manage.py migrate --noinput
fi

if [ "${DJANGO_COLLECTSTATIC:-1}" = "1" ]; then
    python manage.py collectstatic --noinput
    chown -R appuser:appuser /app/staticfiles
fi

exec "$@"
