# Generated by Tses 2026-07-09T12:37:38Z
from decouple import config


CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# One beat entry per recurring job. The MIE webhook sweep is deliberately a
# single minute-cadence task (not a message per event): each pass drains
# everything due in one indexed query + batched writes, so a missed run is
# absorbed by the next one and nothing accumulates in the broker.
CELERY_BEAT_SCHEDULE = {
    "mie-dispatch-webhooks": {
        "task": "api.mie.tasks.dispatch_due_webhooks_task",
        "schedule": 60.0,
    },
    # Feeds the System Health screen. Five minutes rather than one: uptime
    # is measured over a 30-day window by default, so a tighter cadence
    # buys accuracy nobody reads while multiplying stored samples.
    "operations-probe-service-health": {
        "task": "api.operations.tasks.probe_service_health_task",
        "schedule": 300.0,
    },
}
