# Generated by Tses 2026-07-09T12:37:38Z
from decouple import config

CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND",
    default=CELERY_BROKER_URL,
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"

# AI generation tasks are provider-bound and can run for many minutes, so they
# are routed to a dedicated queue consumed by a single-slot worker (see the
# worker-ai service in docker-compose.yaml / compose.prod.yaml). Isolation, not
# timeout tuning, is the fix: a slow or hung generation must never starve the
# shared worker everything else depends on (webhooks, email, health probes).
CELERY_TASK_ROUTES = {
    "api.courses.tasks.generate_ai_course": {"queue": "course_ai"},
    "api.courses.tasks.generate_ai_assist": {"queue": "course_ai"},
    "api.courses.tasks.generate_ai_thumbnail": {"queue": "course_ai"},
    # Video production renders with ffmpeg for hours at a time: its own
    # worker (worker-media), with ffmpeg and fonts installed.
    "api.production.tasks.run_production": {"queue": "production"},
}

# One beat entry per recurring job. The MIE webhook sweep is deliberately a
# single minute-cadence task (not a message per event): each pass drains
# everything due in one indexed query + batched writes, so a missed run is
# absorbed by the next one and nothing accumulates in the broker.
CELERY_BEAT_SCHEDULE = {
    "recover-ai-generation-jobs": {
        "task": "api.courses.tasks.recover_ai_generation_jobs",
        "schedule": 60.0,
    },
    "production-dispatch-runs": {
        "task": "api.production.tasks.dispatch_production_runs",
        "schedule": 60.0,
    },
    "mie-dispatch-webhooks": {
        "task": "api.mie.tasks.dispatch_due_webhooks_task",
        "schedule": 60.0,
    },
    # Feeds the System Health screen. Five minutes rather than one: uptime
    # is measured over a 30-day window by default, so a tighter cadence
    # buys accuracy nobody reads while multiplying stored samples.
    "operations-probe-service-health": {
        "task": "api.operations.tasks.probe_service_health_task",
        "schedule": 300.0,
    },
    # Its thresholds are set in hours, so five minutes is already far finer
    # than the question being asked; a tighter cadence would only re-scan
    # the same queue.
    "reviews-run-sla-sweep": {
        "task": "api.reviews.tasks.run_sla_sweep_task",
        "schedule": 300.0,
    },
    # Surfaces transfers stuck in SUBMITTED that never produced a terminal
    # webhook, so ops can reconcile them against the processor rather than
    # leaving funds in suspense indefinitely.
    "wallet-reconcile-stuck-transfers": {
        "task": "api.wallet.tasks.reconcile_stuck_transfers_task",
        "schedule": 600.0,
    },
}
