# Generated by Tses 2026-07-09T12:37:38Z
from urllib.parse import urlsplit

from decouple import config


def _origins_from_env(name: str) -> list[str]:
    """Return browser origins, stripped of paths and trailing slashes.

    `FRONTEND_URL` is already required by staging for verification and reset
    links. Using it as a CORS fallback prevents those two deployment settings
    from silently drifting apart when `CORS_ALLOWED_ORIGINS` is omitted.
    """
    raw = config(name, default="")
    values = raw.split(",") if isinstance(raw, str) else raw
    origins = []
    for value in values:
        value = value.strip().strip("\"'")
        if not value:
            continue
        parsed = urlsplit(value)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            continue
        origins.append(f"{parsed.scheme}://{parsed.netloc}")
    return origins


def _unique(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))


CORS_ALLOWED_ORIGINS = _unique(
    _origins_from_env("CORS_ALLOWED_ORIGINS") + _origins_from_env("FRONTEND_URL")
)

# Credentialed browser requests that use Django's CSRF protection need the
# same trusted origins. This is intentionally derived from the allowlist and
# never widened to `*`.
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
