# Generated by Tses 2026-07-09T12:37:38Z
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "includes.helpers.PageNumberAPIPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    # Not applied globally (DEFAULT_THROTTLE_CLASSES intentionally omitted) -
    # only the specific auth views that declare throttle_classes/throttle_scope
    # (signup, login, forgot/reset password) are rate-limited, so unrelated
    # endpoints aren't silently throttled by a blanket default.
    "DEFAULT_THROTTLE_RATES": {
        "signup": "3/hour",
        "login": "5/min",
        "forgot_password": "3/hour",
        "reset_password": "5/hour",
        # Tighter than the rest because this is a public account-creation route.
        "superadmin_bootstrap": "5/hour",
        "resend_verification": "3/hour",
        # MIE Endpoint 1 - per-developer idea ingestion.
        "mie_ingest": "30/min",
        # MIE open self-registration - tight, it creates rows pre-auth.
        "mie_register": "5/hour",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "TSES COURSE BUILDER",  # project name
    "VERSION": "1.0.0",
    "SORT_OPERATION_PARAMETERS": False,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
    # Tag list controls both the order Swagger UI shows groups in and the
    # description shown under each. Every tag follows the
    # "Audience - Resource" convention (see swagger_standard.md), and every
    # endpoint carries exactly one.
    "TAGS": [
        {
            "name": "Public — Bank Accounts",
            "description": (
                "Bank lookup endpoints (no authentication required): the "
                "supported-banks list and one-off account-number verification."
            ),
        },
        {
            "name": "Auth — Signup & Verification",
            "description": (
                "Account creation (Course Creator and Reviewer signup), email "
                "verification, and verification-email resend."
            ),
        },
        {
            "name": "Auth — Session",
            "description": (
                "Login, logout (one device or all), token refresh, and active-"
                "session listing/revocation."
            ),
        },
        {
            "name": "Auth — Password",
            "description": (
                "Forgot-password, password reset, and authenticated password change."
            ),
        },
        {
            "name": "Auth — Email Change",
            "description": (
                "Requesting and confirming a change of the account email address."
            ),
        },
        {
            "name": "Auth — MFA",
            "description": (
                "Multi-factor authentication enrollment, verification, recovery "
                "codes, and disable, for the caller's own account."
            ),
        },
        {
            "name": "Auth — Super Admin Bootstrap",
            "description": (
                "One-time claim of the platform's single Super Admin seat using "
                "the deployment environment."
            ),
        },
        {
            "name": "Auth — Staff Invitation",
            "description": (
                "Accepting a staff invitation to set a password and activate "
                "the invited staff account."
            ),
        },
        {
            "name": "Creator — Profile",
            "description": (
                "The signed-in user's own profile: retrieve and update "
                "(excluding email)."
            ),
        },
        {
            "name": "Creator — Onboarding",
            "description": (
                "The multi-step onboarding profile for Course Creators, "
                "resumable via partial updates."
            ),
        },
        {
            "name": "Creator — Courses",
            "description": (
                "Course authoring: create, edit, delete, and submit Draft "
                "courses, and read courses the caller owns or collaborates on."
            ),
        },
        {
            "name": "Creator — Modules",
            "description": "Authoring modules within a Draft course.",
        },
        {
            "name": "Creator — Lessons",
            "description": "Authoring lessons (scripts, media) within modules.",
        },
        {
            "name": "Creator — Assessments",
            "description": (
                "Setting and editing the quiz attached to a lesson, module, or "
                "course (final assessment)."
            ),
        },
        {
            "name": "Creator — Topics",
            "description": (
                "Browsing the topic taxonomy to narrow a course during creation."
            ),
        },
        {
            "name": "Creator — Topic Reservations",
            "description": (
                "Requesting a brand-new topic: file, view, and manage the "
                "caller's own reservation requests."
            ),
        },
        {
            "name": "Creator — Categories",
            "description": (
                "Browsing the category taxonomy (with prices and status) to "
                "pick where a new course belongs."
            ),
        },
        {
            "name": "Creator — Collaborators",
            "description": (
                "Course collaborators: invite, list, change role, and remove "
                "people with access to a course."
            ),
        },
        {
            "name": "Creator — Platform Settings",
            "description": (
                "Reading the live platform-wide thresholds (module counts, word "
                "limits, withdrawal minimum) the builder UI displays."
            ),
        },
        {
            "name": "Creator — KYC",
            "description": (
                "Submitting and reading the caller's own identity-verification "
                "documents."
            ),
        },
        {
            "name": "Creator — Notifications",
            "description": "The signed-in user's in-app notification preferences.",
        },
        {
            "name": "Creator — Activity Log",
            "description": (
                "The signed-in user's own activity history, including CSV export."
            ),
        },
        {
            "name": "Creator — Wallet",
            "description": (
                "The creator wallet: balance, payout accounts, and the two-step "
                "withdrawal flow (request + OTP confirm)."
            ),
        },
        {
            "name": "Creator — Transactions",
            "description": "The creator's own wallet transaction history.",
        },
        {
            "name": "Creator — Bank Accounts",
            "description": (
                "The creator's saved bank accounts for wallet payouts: list, "
                "add, retrieve, delete, and set default."
            ),
        },
        {
            "name": "Creator — Uploads",
            "description": (
                "Requesting a presigned URL to upload files directly to storage."
            ),
        },
        {
            "name": "Creator — Appeals",
            "description": (
                "Filing and tracking the caller's own appeals against a course "
                "rejection."
            ),
        },
        {
            "name": "Reviewer — Review Queue",
            "description": (
                "The course review queue: browse, claim, approve, and reject "
                "submitted courses."
            ),
        },
        {
            "name": "Reviewer — Availability",
            "description": (
                "The reviewer's availability settings that gate whether they "
                "can claim new courses."
            ),
        },
        {
            "name": "Reviewer — Queue Preferences",
            "description": (
                "The reviewer's default queue sort order and track filter."
            ),
        },
        {
            "name": "Reviewer — Topic Reservations",
            "description": (
                "Deciding creators' brand-new-topic requests: approve (creates "
                "the topic and reserves it) or reject."
            ),
        },
        {
            "name": "Admin — Overview",
            "description": (
                "Aggregate platform counts and wallet totals for the admin dashboard."
            ),
        },
        {
            "name": "Admin — Users",
            "description": "Listing, filtering, and managing user accounts.",
        },
        {
            "name": "Admin — Staff",
            "description": (
                "Managing staff: invite, list, revoke, and reactivate staff accounts."
            ),
        },
        {
            "name": "Admin — Categories",
            "description": (
                "Managing the category taxonomy: create, reprice, activate, "
                "and delete categories."
            ),
        },
        {
            "name": "Admin — Topics",
            "description": (
                "Managing the topic taxonomy (including pricing) and manually "
                "releasing topic reservations."
            ),
        },
        {
            "name": "Admin — Wallets",
            "description": (
                "Platform-wide finance: every creator wallet, the transaction "
                "ledger, and all withdrawal requests."
            ),
        },
        {
            "name": "Admin — KYC Review",
            "description": (
                "The KYC review queue: list, retrieve, approve, and reject "
                "identity-verification submissions."
            ),
        },
        {
            "name": "Admin — Activity Log",
            "description": (
                "The platform-wide audit trail of user activity across every account."
            ),
        },
        {
            "name": "Admin — Platform Settings",
            "description": (
                "Updating the platform-wide thresholds that govern course "
                "validation and withdrawals."
            ),
        },
        {
            "name": "Admin — Courses",
            "description": (
                "Admin-only course actions such as publishing an approved course."
            ),
        },
        {
            "name": "Admin — Appeals",
            "description": (
                "Deciding creators' course-rejection appeals (approve reopens "
                "the course for review; reject is final)."
            ),
        },
        {
            "name": "Admin — Bank Accounts",
            "description": "Suspending a creator's bank account.",
        },
        {
            "name": "Admin — MFA",
            "description": (
                "Super-Admin lost-device recovery: resetting another user's "
                "MFA enrollment."
            ),
        },
        {
            "name": "Admin — Audit",
            "description": (
                "The platform-wide audit log (OTP events, administrative "
                "actions), filterable by email, event, and date range."
            ),
        },
        # ── MIE (external-developer pipeline) ──────────────────────
        # Tags are ordered as the integration is actually used, step by
        # step: the developer self-registers, the superadmin approves,
        # the developer submits and tracks ideas, and the superadmin
        # works the queue.
        {
            "name": "MIE Developer — Onboarding",
            "description": (
                "STEP 1 — The developer registers themselves (email + "
                "webhook URL, open endpoint). The account starts PENDING "
                "and can authenticate nothing until approved."
            ),
        },
        {
            "name": "Admin — MIE Developers",
            "description": (
                "STEP 2 — Superadmin reviews the pending developer: "
                "approve (issues the API key shown exactly once), reject, "
                "or suspend; plus the developer directory."
            ),
        },
        {
            "name": "MIE Developer — Submissions",
            "description": (
                "STEP 3 — The developer integrates. Submit course ideas "
                "(Endpoint 1) with the issued API key (X-MIE-Api-Key) and "
                "track every idea's state in their own queue."
            ),
        },
        {
            "name": "MIE Developer — Account",
            "description": (
                "STEP 4 — The developer's reference material: account "
                "snapshot (/me) and generated integration documentation "
                "(/documentation) with webhook samples and HMAC "
                "verification."
            ),
        },
        {
            "name": "Admin — MIE Submissions",
            "description": (
                "STEP 5 — Superadmin works the pipeline: the cross-"
                "developer queue (filters: developer, status, date, "
                "search), reversible approve/reject with immediate "
                "webhooks, recommendation signals (demand score, "
                "estimated earnings), payout-bypass toggles, and the "
                "rejection-reason taxonomy."
            ),
        },
    ],
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
        },
    },
    "SECURITY": [
        {"bearerAuth": []},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "ENUM_NAME_OVERRIDES": {
        "CategoryStatusEnum": "api.catalog.enums.CategoryStatus",
        "CourseStatusEnum": "api.courses.enums.CourseStatus",
        "TransactionStatusEnum": "api.wallet.enums.TransactionStatus",
        "CollaboratorRoleEnum": "api.collaborators.enums.CollaboratorRole",
        # CategoryRequestStatus and ReservationStatus share identical choices
        # (PENDING/APPROVED/REJECTED) so drf-spectacular treats them as one
        # component; give that shared component a single explicit name.
        # KYCStatus has the same three values and folds into it too.
        "RequestStatusEnum": "api.catalog.enums.CategoryRequestStatus",
        # Surfaced by the admin serializers, which are the first to expose
        # these choice sets in a response body. Without explicit names they
        # collide with the other "status"/"type"/"role" fields above and
        # drf-spectacular invents suffixed names that churn between runs.
        "AccountStatusEnum": "api.users.enums.AccountStatus",
        "WithdrawalRequestStatusEnum": "api.wallet.enums.WithdrawalRequestStatus",
        "TransactionTypeEnum": "api.wallet.enums.TransactionType",
        "UserRoleEnum": "api.users.enums.UserRole",
        # MIE enums are exposed through admin and developer serializers;
        # pin their component names so runs stay deterministic.
        "DeveloperAccountStatusEnum": "api.mie.enums.DeveloperAccountStatus",
        "MiePlanTypeEnum": "api.mie.enums.MiePlanType",
        "SubmissionStatusEnum": "api.mie.enums.SubmissionStatus",
        "WebhookEventTypeEnum": "api.mie.enums.WebhookEventType",
        "WebhookDeliveryStatusEnum": "api.mie.enums.WebhookDeliveryStatus",
    },
}
