# Generated by Tses 2026-07-09T12:37:38Z
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "includes.helpers.PageNumberAPIPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    # Not applied globally (DEFAULT_THROTTLE_CLASSES intentionally omitted) -
    # only the specific auth views that declare throttle_classes/throttle_scope
    # (signup, login, forgot/reset password) are rate-limited, so unrelated
    # endpoints aren't silently throttled by a blanket default.
    "DEFAULT_THROTTLE_RATES": {
        "signup": "3/hour",
        "login": "5/min",
        "forgot_password": "3/hour",
        "reset_password": "5/hour",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "TSES COURSE BUILDER",  # project name
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v[0-9]",
    "COMPONENTS": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
        },
    },
    "SECURITY": [
        {"bearerAuth": []},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
    },
    "ENUM_NAME_OVERRIDES": {
        "CategoryStatusEnum": "api.categories.enums.CategoryStatus",
        "CourseStatusEnum": "api.courses.enums.CourseStatus",
        "TransactionStatusEnum": "api.wallet.enums.TransactionStatus",
        "CollaboratorRoleEnum": "api.collaborators.enums.CollaboratorRole",
        # CategoryRequestStatus and ReservationStatus share identical choices
        # (PENDING/APPROVED/REJECTED) so drf-spectacular treats them as one
        # component; give that shared component a single explicit name.
        "RequestStatusEnum": "api.courses.enums.CategoryRequestStatus",
    },
}
