# Generated by Tses 2026-07-09T12:37:38Z
from decouple import config

EMAIL_PROVIDER = config("EMAIL_PROVIDER", default="smtp")
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="")
# Django's SMTP backend reads EMAIL_TIMEOUT automatically (socket-level
# cap per SMTP operation), so a hung provider cannot stall the whole request
# past Cloudflare's 120s Proxy Read Timeout.
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", cast=int, default=30)
# Cloudflare Email Service REST API (EMAIL_PROVIDER=cloudflare). No SMTP egress
# required — delivery happens over HTTPS to api.cloudflare.com. The API token
# needs the Email Sending: Edit permission, and DEFAULT_FROM_EMAIL's domain must
# be onboarded for Email Sending on the account that owns the token.
CLOUDFLARE_API_TOKEN = config("CLOUDFLARE_API_TOKEN", default="")
CLOUDFLARE_ACCOUNT_ID = config("CLOUDFLARE_ACCOUNT_ID", default="")

if EMAIL_HOST_USER:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = config("EMAIL_HOST", default="smtp.cloudflare.com")
    EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
    EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)
    EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
