# Generated by Django 5.2.14 on 2026-08-20 17:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category display name.",
                        max_length=150,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier derived from the name when omitted. Used for lookups and discovery.",
                        max_length=160,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the category shown to creators.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "creator_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed price paid to a creator for an approved course in this category.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Creator Price",
                    ),
                ),
                (
                    "track_preference",
                    models.CharField(
                        choices=[
                            ("CREATOR_PREFERRED", "Creator Preferred"),
                            ("AI_PREFERRED", "AI Preferred"),
                            ("OPEN", "Open"),
                        ],
                        default="OPEN",
                        help_text="Which production track this category is best suited for.",
                        max_length=20,
                        verbose_name="Track Preference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        help_text="Whether the category currently accepts new course submissions.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Requested category name.",
                        max_length=150,
                        verbose_name="Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Whether this request is pending, approved, or rejected.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Creator who requested this category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "resulting_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Category created when this request was approved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.category",
                        verbose_name="Resulting Category",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved or rejected this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Request",
                "verbose_name_plural": "Category Requests",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Topic display name.",
                        max_length=150,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier derived from the name when omitted. Unique within its category.",
                        max_length=160,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "creator_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed price paid to a creator for an approved course in this topic.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Creator Price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        help_text="Whether the topic currently accepts new course submissions.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reserved_until",
                    models.DateField(
                        blank=True,
                        help_text="Date the current reservation expires.",
                        null=True,
                        verbose_name="Reserved Until",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this topic belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Creator this topic is currently reserved for (PRD BR-007), if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reserved By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TopicReservationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="datetime of object creation",
                        verbose_name="Created datetime",
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="datetime of object update",
                        verbose_name="Updated datetime",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Proposed name for the new topic.",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        help_text="Whether this request is pending, approved, or rejected.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why the reviewer rejected this request, e.g. a duplicate name.",
                        null=True,
                        verbose_name="Rejection Reason",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category the proposed topic would belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_reservation_requests",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Creator who requested this topic.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_reservation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin/Reviewer who approved or rejected this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed By",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Topic created once this request is approved.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_requests",
                        to="catalog.topic",
                        verbose_name="Topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Reservation Request",
                "verbose_name_plural": "Topic Reservation Requests",
                "ordering": ["-created_datetime"],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["status", "track_preference"], name="category_status_track_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryrequest",
            index=models.Index(fields=["status"], name="category_request_status_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["category", "status"], name="topic_category_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="unique_topic_name_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("category", "slug"), name="unique_topic_slug_per_category"
            ),
        ),
        migrations.AddIndex(
            model_name="topicreservationrequest",
            index=models.Index(fields=["status"], name="topic_reservation_status_idx"),
        ),
    ]
