# Generated by Django 5.2.14 on 2026-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_default_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Why this category is needed and what belongs in it. Carried onto the Category created on approval.', verbose_name='Description'),
        ),
    ]
