# Generated by Django 5.2.14 on 2026-09-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_price_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Whether the topic currently accepts new course submissions.', max_length=10, verbose_name='Status'),
        ),
    ]
