# Generated by Django 5.2.14 on 2026-09-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_topic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_datetime',
            field=models.DateTimeField(blank=True, help_text='datetime of object deletion', null=True, verbose_name='Deleted datetime'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is deleted', verbose_name='Is deleted'),
        ),
    ]
