# Generated by Django 5.2.14 on 2026-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrequest',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Why this category is needed and what belongs in the request.', verbose_name='Description'),
        ),
    ]
