# Generated by Tses 2026-07-09T12:37:38Z
from django.contrib import admin

from api.users.models import KYCVerification


@admin.register(KYCVerification)
class KYCVerificationAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "document_type", "status", "created_datetime")
    list_filter = ("status", "document_type")
    search_fields = ("user__email", "id_number")
