# Generated by Tses 2026-07-09T12:37:38Z
from django.db import models


class UserRole(models.TextChoices):
    """Primary role used for role-based permission checks across the platform.

    Extend these choices as new operator roles are introduced (e.g. AI Track
    Reviewer, QA Reviewer) once the corresponding review pipelines exist.
    """

    COURSE_CREATOR = "COURSE_CREATOR", "Course Creator"
    CREATOR_REVIEWER = "CREATOR_REVIEWER", "Creator Reviewer"
    ADMIN = "ADMIN", "Admin"


class UserActivityCategoryEnums(models.TextChoices):
    """High-level buckets used to group user activity events.

    Extend these choices when a project introduces new audit domains such as
    billing, security, or team management.
    """

    AUTH = "AUTH", "Authentication"
    PROFILE = "PROFILE", "Profile"


class UserActivityActionEnums(models.TextChoices):
    """Concrete user actions that can be stored in the activity log.

    Teams should add project-specific actions here as new tracked flows are
    introduced, while keeping values stable for reporting and analytics.
    """

    LOGIN = "LOGIN", "Login"
    LOGOUT = "LOGOUT", "Logout"
    TOKEN_REFRESHED = "TOKEN_REFRESHED", "Token Refreshed"
    ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED", "Account Verified"
    PASSWORD_RESET_COMPLETED = (
        "PASSWORD_RESET_COMPLETED",
        "Password Reset Completed",
    )
    PROFILE_UPDATED = "PROFILE_UPDATED", "Profile Updated"
    PASSWORD_CHANGED = "PASSWORD_CHANGED", "Password Changed"
    ONBOARDING_COMPLETED = "ONBOARDING_COMPLETED", "Onboarding Completed"
