# Generated by Tses 2026-07-09T12:37:38Z
from django.db import models


class Sex(models.TextChoices):
    """Self-reported sex, shown on a user's profile (e.g. course-collaborator
    detail panel)."""

    MALE = "MALE", "Male"
    FEMALE = "FEMALE", "Female"
    PREFER_NOT_TO_SAY = "PREFER_NOT_TO_SAY", "Prefer not to say"


class UserRole(models.TextChoices):
    """Primary role used for role-based permission checks across the platform.

    Roles fall into three groups, and the distinction matters:

    * **Public** - COURSE_CREATOR is what public signup assigns. Anyone can
      obtain it by registering.
    * **Staff** - STAFF_WRITER / STAFF_VERIFIER / STAFF_APPROVER are the roles
      offered in the "Invite a staff" dialog. They are invitation-only: no
      public route assigns them. They mirror the authoring pipeline
      (write -> verify -> approve) and are deliberately kept distinct from the
      public roles so a self-registered user is never mistaken for hired staff
      in permissions, reporting, or the Teams page.
    * **Privileged** - ADMIN and SUPER_ADMIN. SUPER_ADMIN is bootstrap-only and
      unique platform-wide; it is the only role that can invite staff.

    Extend the staff group as new operator roles are introduced (e.g. AI Track
    Reviewer, QA Reviewer) once the corresponding review pipelines exist.
    """

    COURSE_CREATOR = "COURSE_CREATOR", "Course Creator"
    CREATOR_REVIEWER = "CREATOR_REVIEWER", "Creator Reviewer"
    STAFF_WRITER = "STAFF_WRITER", "Writer"
    STAFF_VERIFIER = "STAFF_VERIFIER", "Verifier"
    STAFF_APPROVER = "STAFF_APPROVER", "Approver"
    ADMIN = "ADMIN", "Admin"
    SUPER_ADMIN = "SUPER_ADMIN", "Super Admin"


#: Roles a Super Admin may hand out via the "Invite a staff" dialog, in the
#: order the dropdown shows them. SUPER_ADMIN is absent by design - the seat is
#: unique and claimable only through the bootstrap endpoint - and so are the
#: public roles, which are not staff positions.
INVITABLE_STAFF_ROLES = (
    UserRole.STAFF_WRITER,
    UserRole.STAFF_VERIFIER,
    UserRole.STAFF_APPROVER,
)

#: Every role that counts as staff for the Teams page: the invitable roles plus
#: the privileged roles, which are staff too but are not handed out by invite.
STAFF_ROLES = INVITABLE_STAFF_ROLES + (UserRole.ADMIN, UserRole.SUPER_ADMIN)


class UserActivityCategoryEnums(models.TextChoices):
    """High-level buckets used to group user activity events.

    Extend these choices when a project introduces new audit domains such as
    billing, security, or team management. PRODUCTION and ALERT are retained
    for forward compatibility with the SCCS AI Auto-Production Engine and SLA
    alerting subsystems (neither is implemented in this backend yet) - same
    "reserved, unused for now" idiom as TrackPreference.AI_PREFERRED.
    """

    AUTH = "AUTH", "Authentication"
    PROFILE = "PROFILE", "Profile"
    COURSE = "COURSE", "Course"
    SUBMISSION = "SUBMISSION", "Submission"
    APPROVAL = "APPROVAL", "Approval"
    PUBLISH = "PUBLISH", "Publish"
    CONFIGURATION = "CONFIGURATION", "Configuration"
    PRODUCTION = "PRODUCTION", "Production"
    ALERT = "ALERT", "Alert"
    KYC = "KYC", "KYC"
    WALLET = "WALLET", "Wallet"


class UserActivityActionEnums(models.TextChoices):
    """Concrete user actions that can be stored in the activity log.

    Teams should add project-specific actions here as new tracked flows are
    introduced, while keeping values stable for reporting and analytics.
    """

    LOGIN = "LOGIN", "Login"
    LOGOUT = "LOGOUT", "Logout"
    TOKEN_REFRESHED = "TOKEN_REFRESHED", "Token Refreshed"
    ACCOUNT_VERIFIED = "ACCOUNT_VERIFIED", "Account Verified"
    PASSWORD_RESET_COMPLETED = (
        "PASSWORD_RESET_COMPLETED",
        "Password Reset Completed",
    )
    PROFILE_UPDATED = "PROFILE_UPDATED", "Profile Updated"
    PASSWORD_CHANGED = "PASSWORD_CHANGED", "Password Changed"
    ONBOARDING_COMPLETED = "ONBOARDING_COMPLETED", "Onboarding Completed"
    SUPERADMIN_BOOTSTRAPPED = "SUPERADMIN_BOOTSTRAPPED", "Super Admin Bootstrapped"
    STAFF_INVITED = "STAFF_INVITED", "Staff Invited"
    STAFF_INVITATION_ACCEPTED = (
        "STAFF_INVITATION_ACCEPTED",
        "Staff Invitation Accepted",
    )
    STAFF_REVOKED = "STAFF_REVOKED", "Staff Revoked"
    STAFF_REACTIVATED = "STAFF_REACTIVATED", "Staff Reactivated"
    COURSE_ASSIGNED = "COURSE_ASSIGNED", "Course Assigned"
    COURSE_SUBMITTED = "COURSE_SUBMITTED", "Course Submitted"
    COURSE_APPROVED = "COURSE_APPROVED", "Course Approved"
    COURSE_REJECTED = "COURSE_REJECTED", "Course Rejected"
    COURSE_PUBLISHED = "COURSE_PUBLISHED", "Course Published"
    AVAILABILITY_UPDATED = "AVAILABILITY_UPDATED", "Availability Updated"
    NOTIFICATION_PREFERENCES_UPDATED = (
        "NOTIFICATION_PREFERENCES_UPDATED",
        "Notification Preferences Updated",
    )
    KYC_SUBMITTED = "KYC_SUBMITTED", "KYC Submitted"
    KYC_APPROVED = "KYC_APPROVED", "KYC Approved"
    KYC_REJECTED = "KYC_REJECTED", "KYC Rejected"
    WITHDRAWAL_REQUESTED = "WITHDRAWAL_REQUESTED", "Withdrawal Requested"
    WITHDRAWAL_CONFIRMED = "WITHDRAWAL_CONFIRMED", "Withdrawal Confirmed"


class KYCDocumentType(models.TextChoices):
    """Identity document types a user can submit for KYC verification."""

    NATIONAL_ID = "NATIONAL_ID", "National ID (NIN)"
    DRIVERS_LICENSE = "DRIVERS_LICENSE", "Driver's License"
    INTERNATIONAL_PASSPORT = "INTERNATIONAL_PASSPORT", "International Passport"
    VOTERS_ID = "VOTERS_ID", "Voter's ID"


class KYCStatus(models.TextChoices):
    """Review status of a KYC verification submission."""

    PENDING = "PENDING", "Pending"
    APPROVED = "APPROVED", "Approved"
    REJECTED = "REJECTED", "Rejected"


class UnavailabilityReason(models.TextChoices):
    """Why a Creator Reviewer marked themselves unavailable."""

    VACATION = "VACATION", "Vacation"
    SICK_LEAVE = "SICK_LEAVE", "Sick Leave"
    PERSONAL = "PERSONAL", "Personal"
    TRAINING = "TRAINING", "Training"
    OTHER = "OTHER", "Other"
