# Generated by Tses 2026-07-09T12:37:38Z
from django.contrib.auth import get_user_model
from django.test import TestCase

from api.users.enums import UserRole

User = get_user_model()


class UserRoleTests(TestCase):
    def test_default_role_is_course_creator(self):
        user = User.objects.create_user(
            email="creator@example.com",
            password="testpass123",
            first_name="Test",
            last_name="Creator",
        )
        self.assertEqual(user.role, UserRole.COURSE_CREATOR)

    def test_role_field_accepts_all_enum_choices(self):
        for index, role in enumerate(UserRole.values):
            user = User.objects.create_user(
                email=f"user{index}@example.com",
                password="testpass123",
                first_name="Test",
                last_name="User",
                role=role,
            )
            self.assertEqual(user.role, role)
